nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/homedirs-other-2020-07-29/highschool

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool

    config:
      JupyterHub:
        authenticator_class: GoogleOAuthenticator
      GoogleOAuthenticator:
        hosted_domain:
        - berkeley.edu
        # See https://github.com/berkeley-dsep-infra/datahub/issues/1529
        - achieveprogram.org
        # moved admin users to protected directory

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
