jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    enabled: false
    # service:
    #   loadBalancerIP: 34.72.13.135
    # https:
    #   hosts:
    #     - highschool-staging.datahub.berkeley.edu
