apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rebalancer
  labels:
    app: rebalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rebalancer
  template:
    metadata:
      labels:
        app: rebalancer
    spec:
      nodeSelector: {{ toJson .Values.rebalancer.nodeSelector }}
      serviceAccountName: rebalancer
      containers:
        - name: rebalancer
          image: {{ .Values.rebalancer.image.name }}:{{ .Values.rebalancer.image.tag }}
          command:
            - python3
            - rebalancer.py
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rebalancer
  labels:
    app: rebalancer
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rebalancer
  labels:
    app: rebalancer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rebalancer
  labels:
    app: rebalancer
subjects:
  - kind: ServiceAccount
    name: rebalancer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: rebalancer
  apiGroup: rbac.authorization.k8s.io