jupyterhub:
  proxy:
    https:
      letsencrypt:
        contactEmail: yuvipanda@berkeley.edu
  hub:
    extraConfig: |
      from kubespawner import KubeSpawner
      from tornado import gen
      import yaml
      import os

      class CustomAttrSpawner(KubeSpawner):

        @gen.coroutine
        def start(self):
          with open('/etc/jupyterhub/config/custom.memory') as f:
            custom_attr_lists = yaml.safe_load(f)
            for attr, users in custom_attr_lists.items():
              if self.user.name in users:
                self.mem_limit = attr
                self.mem_guarantee = attr
                break

          return (yield super().start())

      c.JupyterHub.spawner_class = CustomAttrSpawner

      c.JupyterHub.extra_log_file = '/srv/jupyterhub/jupyterhub.log'

      # HACK: this is temporary and will go away soon (~0.6)
      if 'HUB_USERNAME_MAP' in os.environ:
          # expect badname1=goodname1:badname2=goodname2
          c.Authenticator.username_map = {}
          keyvals = os.environ['HUB_USERNAME_MAP']
          for keyval in keyvals.split(':'):
              key, val = keyval.split('=')
              c.Authenticator.username_map[key] = val

  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - chench
          - vinitra
          - gunjan_baid
          - acheema
          - zdehkordi
          # sp18 data 8 Professors
          - adhikari
          # sp18 data 8 GSIs
          - fhdkmrn
          - wumadeline
          - austenzhu
          - supadhyay
          - v.oikonomou
          - scott.lee.3898
          - abala
          - adnan.h
          - akritisingh
          - amrosenthal
          - ashahatit
          - alinxie
          - averyyip
          - clairezhang
          - dcroce
          - echang7
          - emmajaeger
          - chenge
          - fmcquarrie3
          - hsubbaraj
          - howardki888
          - jwarnagieris
          - j.hu
          - huangjiayi0922
          - jwhughes
          - michelleyang
          - nwang97
          - namushegian
          - niraj.a.rao
          - nskh
          - ravi.singhal
          - narain.rohan
          - ronald.walker
          - rjoshi
          - rroggenkemper
          - s.mani
          - tanaynathan18
          - vienannguyen
          # connector instructors
          - miladm
          - cmason
          - feehan
          - yasminal
          - samyag1
          - michael.eickenberg
          - ericvd
          - shobhana
          #DSEP Staff
          - ryanedw
          - ericvd
          # Physics 77/88 Spring 2018
          - ryansmith63
          - ygkolomensky
          # LING 243 Spring 2018
          - terry.regier
          # COGSCI 131 Spring 2018
          - ddbourgin
          # ECON 101B Spring 2018
          - jbdelong

  singleuser:
    memory:
      guarantee: 1G
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/primary-user-image
    commentedstorage:
      type: hostPath
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/{username}
        - name: cogneuro
          hostPath:
            path: /data/homes/_cogneuro
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
        - name: cogneuro
          mountPath: /data/cogneuro
          readOnly: True
