jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:OTS1aNHdUkHu5+4V8neRCada8MtixVVJIRTl/7JZI9Kl+vmUnxh9SavWBkn6vIv8xrRrDJSy/GqPTpb6vXwPPg==,iv:5qufB4ReUQ7xsB4V5FSI8WHAGdthYWownyqbHDsTZ28=,tag:FiuvcwGrr/IkzIv/lV9SrQ==,type:str]
    hub:
        config:
            CanvasOAuthenticator:
                #ENC[AES256_GCM,data:SVoZ6qAjchDyekCvJiybXEDRUl4Sx2I=,iv:4pDkVfVEy/xM6v7NMiyVS4EhIJ4mrPYNZ05lDlnoVuY=,tag:nzmPjDxl8RqhSHIwPpYS5A==,type:comment]
                client_secret: ENC[AES256_GCM,data:Gt61/j2oHAGWjdRzwR8+lkz11btc97plJdQUR7o8cghejnlyL86tM+zC80wgQtJotSqzf45shbbKpsGhMcbSUw==,iv:lU32BWVTYU+c/PG47As1Gf2k9+SeoUxOQTz2w2okl2w=,tag:mM+NYEsPZpdhnUsaWcJ+fA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:22Z"
          enc: CiQA67O9AGNQTRyJE9Lb9/hgQRYknJyphVkvy9+ST4eEmG/eZIQSSQDmhpq8571wxOluYqvghL/P2vXrl5ZqH+K27srlXM4QLDdsWUo4OFPUL20sgaHucuraI+2HhDzL1C3CEhtgNaiY7ueJF707fBo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:24Z"
    mac: ENC[AES256_GCM,data:COnidjadob0d8WoVxahDykH8PCdWypwshx+EcyNdWlrHbqMhDJwBwhbPuRSpcYwq5bsOo3PASFTBpWlH4H/nZs9k11qOkP0vzGJl1IQwdmzjfnnGsafWZu8c3XvDIY/4H5SGpyOedB0tnQPwXjz2JFZwAxMP9drwr8QFQ+cYrNU=,iv:4KABjoEyEu56LqjwxoW1zPdkWml5MEyixGiBFDJRe+0=,tag:lyiDKXk0b58KEKzvaGxA7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
