jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:P/mftvfhS3gAXCbRppF29dVlzkVBfiFjKVRI97jgND+1PcMuoocLOKLXcGtSgov04OwH7OHxSyjWAgUEOxopSA==,iv:VN0uqXddDiUP/Wr1qCUFVKRt2LNsiwKn0Yi3xMDB7CM=,tag:jXXNNTlmXjc+e1wlvNiCnw==,type:str]
    hub:
        config:
            CanvasOAuthenticator:
                #ENC[AES256_GCM,data:EyGG2Z6i0IkbZmiUMpzUMvRp9YZAXdY=,iv:oTQ7GCcQsO/bq85XpzCDSO7aN7jYqrSI4caEOJwDOFw=,tag:grjjrrTKBlN+SUucRiiTbg==,type:comment]
                client_secret: ENC[AES256_GCM,data:P/GKz07RH4KS+qGG+X2oMJTUnYrf/HCExlLYl7pgAaKZOzTCKJMecp6t0wvyPsr41yX/EIp1D1Um5hyiarr5zA==,iv:+eqmXqGZt09r6tm9vBvtr9Vj3/2NN1vPcljuSgIFv2U=,tag:XoLEqSbMzbi/RAF4jamcNQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:06Z"
          enc: CiQA67O9ABBxbcCB/8M06UDvP/2GYPWoYK2jicrWAJ7/V8wrjb0SSQDmhpq8ly40ncQvvSKw+r7upK8722H+SF0j8imhlMNGaiJ08ucIeYjAHuVb7YmumyGHWGcDajf3fpnFjaqFzvMfyKxh1O+wALI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:08Z"
    mac: ENC[AES256_GCM,data:Hlcq3HUj3A+c5u3LxYaZWdYkp8ITjYTUxYupVXkuBLmpIDFJ6Go3AdNtsCVVGHzrOS+EtLimY2Gac8CoBdd5+3GsvLX6t3T56MzIx1/WQMMkG2o3qOFQjeyIWFhKtd55S4a7nU7oSD6qM3N7huwLVLMeT9GZ6B2rPFmzowgugUE=,iv:Igw1gDlhtWi1hCX6QC1NL+1qShdeyspR6jhAkn8Ve+w=,tag:4R2fEUmewJpFP6GTAPjB4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
