jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:V/nlSiY5gV/Ght8Q2izMBcz55T72Nzb3F02Q/QIxlctbRMNz3CtL9UvBWlCocz0a+9rz1kZl0UiZV48O7UrfOg==,iv:wh27rk0tUNFKllTnutIbagmLmRrnPH/Ni64XhfLsHxE=,tag:rA06xZGgPzAQ5FMXgXea9w==,type:str]
    hub:
        config:
            CanvasOAuthenticator:
                #ENC[AES256_GCM,data:0pb3dNCWhFM1Eiwt2/PnbE1GSjWbzJ8=,iv:vftTmk2jRgnfEzb7l20m4d7KmbmAI9jSluYfj5rKiIs=,tag:ARBwJQxw3MgHVDD5TXsqfA==,type:comment]
                client_secret: ENC[AES256_GCM,data:fmk6EIRihi5drS0d9FrIkoQcbWAyK/PPQC0xaQzkgGQ82a9bPs9wDjKl7ZlV55CflGictNL+30SGl0ePs2f2tQ==,iv:fh3tXpEefocJ/Ik5oHAH64kMDr1iJTtmXsONu/T0l2Q=,tag:1aHccvhtVbKaK6w10Q5s4w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:06Z"
          enc: CiQA67O9AJXrH859c/y6VaVmzLzPp5buTkUvYn4tQRy2Sz8NuYUSSQDmhpq8uOjQmlo+RYWXNqATL5x1vcUtwZTZbtTV4B+wXmiJiwNbJFOnSCiunJVS/EbsXzcgScxB3DeIcIHpXMyiMMJMRO7Nsv8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:08Z"
    mac: ENC[AES256_GCM,data:APmlRDqCw/8XO/3nGNjFmWbrsU3Xi28DQhGrIeBLTrpMZct5EzrIspEJDWM99AkRH1PgR/ETGcB/JcMtaGIfM9Vb/oDRi8u8LXedYHJMuGDq0ns67EUISrt7fyMtVhyqRRVwzXVAV5OLJUSsxTk081eX+4e1JlKMcB58v5/iwqI=,iv:ETL7BAHKAhXx/knBPApjD34VYmhn2N9mH5kv9xHCMpo=,tag:gkAAx14tnsvouDIsEmWFaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
