jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                #ENC[AES256_GCM,data:MBMxsnRqKa5r8qZphgARCwGUasRdhE8=,iv:817K6QXVvvRnuqjGzcD8E29y97hO1PTI9XHvsyv92ec=,tag:qPD7QW+GVk7+vTKYUavf3Q==,type:comment]
                client_secret: ENC[AES256_GCM,data:yWwSW1X/yrZRIy1IB7bpXuIsfq5U/x/xlrbQpUTWtCDe7N16FJUjf+azWyLuwuY/6zUEUDhY2p1BW3/kMpGfpw==,iv:+0kE8mXWLD94lRhtYX28On2WOTv3+l1T8pTdVSkHYug=,tag:tva7jZPWL43SBsMzwEQhXw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:01Z"
          enc: CiQA67O9AI0YvAK0oiXREYKlnoDxA6nsPk61G0qftvkyx+031yESSQDmhpq8yxdw5t6D4gDWckUZjNcZUsYOmrCyrWpapmf0aV9NnkRQauuqQYSCznyOWrX5UsfyiKd7oqcPJEJ782fflP/fqQNLqXY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T22:47:05Z"
    mac: ENC[AES256_GCM,data:46Vrlb97SrqLbWOZg0bP7DLo2ScOL5lyqnnlUeDD45bc+YgRsi3G+PYK7lk0t8OToQSEg0ylLozX/I6W5hNPm2b7NmFaq4DwqjeJjwoLQJBBmGQWKS2o9grnt8mGM3bhNaaHdzaGHnoJ0/BgBiEcQeAW3zrOCvnQAcvyWF8oxDw=,iv:HFWIlYK7JgUmIpCU89cQajRXmkwM3e7VGDyNbXus0uA=,tag:O7e1psY2qDivug1138Mo8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
