jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          # instructors
          - adhikari
          # dsep staff
          - bacon
          - ericvd
          - ryanedw
          # s19 prob140 gsis
          - alanchuang
          - dibya.ghosh

  singleuser:
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/prob140-user-image
    storage:
      type: hostPath

  hub:
    extraContainers:
      - name: fetch-course-emails
        image: berkeleydsep/fetch-course-emails:v1
        volumeMounts:
        - name: hub-db-dir
          mountPath: /srv/jupyterhub

custom:
  profiles:
    2019-spring-25622:
      placeholder: waves
