jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          # instructors
          - adhikari
          # dsep staff
          - bacon
          - ericvd
          - ryanedw
          # s19 prob140 gsis
          - alanchuang
          - dibya.ghosh

  hub:
    extraConfigMap:
      profiles:
        2019-spring-25622:
          placeholder: waves

  singleuser:
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/prob140-user-image
    storage:
      type: hostPath

# this will be supported later
#custom:
#  profiles:
#    2019-spring-25622:
#      placeholder: waves
