nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver1
    shareName: export/pool0/homes

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
  proxy:
    nodeSelector:
      cloud.google.com/gke-nodepool: default-pool
  auth:
    type: custom # Uses canvas auth
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          # instructors
          - adhikari
          # dsep staff
          - bacon
          - ericvd
          - ryanedw
          # s19 prob140 gsis
          - alanchuang
          - dibya.ghosh

  hub:
    nodeSelector:
      cloud.google.com/gke-nodepool: default-pool
    extraConfigMap:
      profiles:
        2019-spring-25622:
          mem_guarantee: 576M
          mem_limit: 1088M

  singleuser:
    nodeSelector:
      cloud.google.com/gke-nodepool: user-pool
    initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: home
          mountPath: /home/jovyan
          subPath: "_prob140/{username}"
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "_prob140/{username}"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/prob140-user-image

# this will be supported later
#custom:
#  profiles:
#    2019-spring-25622:
#      placeholder: waves
