dependencies:
 - name: prometheus
   version: 11.16.9
   repository: https://prometheus-community.github.io/helm-charts
 - name: grafana
   version: 5.5.5
   repository: https://kubernetes-charts.storage.googleapis.com
