dependencies:
 - name: prometheus
   version: 11.16.9
   repository: https://prometheus-community.github.io/helm-charts
 - name: grafana
   version: 6.2.1
   repository: https://grafana.github.io/helm-charts
#   repository: https://kubernetes-charts.storage.googleapis.com
