dependencies:
 - name: prometheus-statsd-exporter
   version: 0.3.1
   repository: https://prometheus-community.github.io/helm-charts
 - name: prometheus
   version: 11.16.9
   repository: https://prometheus-community.github.io/helm-charts
 - name: grafana
   version: 6.24.1
   repository: https://grafana.github.io/helm-charts
 - name: cert-manager
   version: v1.9.1
   repository: https://charts.jetstack.io
 - name: ingress-nginx
   version: 4.2.1
   repository: https://kubernetes.github.io/ingress-nginx
