jupyterhub:
  hub:
    services:
      gofer_nb:
        url: http://grading.data8x.berkeley.edu:10101
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 104.198.75.230
    https:
      hosts:
        - staging-hub.data8x.berkeley.edu
