jupyterhub:
    config:
        GenericOAuthenticator:
            client_id: ENC[AES256_GCM,data:9qWs3XLKmBXYk22IsShd8Gs2x/yDtE70lju4rDJycVoiu25w3bvDKIgywAh0cluxfFjBEJzNfKFQEwTEF2dFmw==,iv:AxXDSduGXH20XjnGjT98X5mX7WDfgHP2JPdVkZgEtHQ=,tag:OaZM6/Hb9TeTB0s11RCuaw==,type:str]
            client_secret: ENC[AES256_GCM,data:NnvkorgjVCAuYCYvR6cJOQjvKCA9pmVVQEnd06R1dwNTAx0G3/vHuCV0n8NnDpj4QpL7aEm68meO0c6hHGZUzA==,iv:WY7oQSMXD3BIWimWV3fOp7XglLC/ymzLPWcEa3ANGlg=,tag:IV1d88mF/Z8EHZJ122ohmA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9AK2027WGYGTzywa01Cz+Ez7sOTk/d9payovyK5pg8g4SSADmhpq89bbIWFjlGg79o/iupJ4anLU5Ab9VL+qNzhu6e83JtJ7wSv6sK+cDiEfVSaKQ1YIcadDXFt4WUKRt7MFvAa1sLqp2LA==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-04T05:48:53Z"
    mac: ENC[AES256_GCM,data:/htucajanDLvI4FT7Fb3rXgpQbrbWDhbkxCssbdGn+JnMEursIRZFgaJL0rBZOJsoNrID3QnKO2ALGVyyxBMxwZGBZ5EDRPfwE7AHqi7KZYUtt9ewrO9YgdnTvDe09L6n5NbfZN3OBI3kE2s42MD9CVnMSQOTvXqoP/JkIQr6ho=,iv:7P6NuTRUKXxvcM0G2Ab46prmaAljFU2NjiRglbMdSjw=,tag:eCnstVTXuFb8Wuv5eonvMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
