jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/node-purpose: core
  proxy:
    nodeSelector:
      hub.jupyter.org/node-purpose: core
  hub:
    nodeSelector:
      hub.jupyter.org/node-purpose: core
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users
          # Professor
          - mahoneymw
          # GSIs
          - krinsman
          - theisen
          # UGSI
          - wqixuan

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/stat89a-user-image
    storage:
      type: hostPath
    defaultUrl: "/lab"
