jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users
          # Professor
          - mahoneymw
          # GSIs
          - krinsman
          - theisen
          # UGSI
          - wqixuan

  singleuser:
    nodeSelector:
      hub.jupyter.org/node-purpose: user
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/stat89a-user-image
    storage:
      type: hostPath
    defaultUrl: "/lab"
    lifecycleHooks:
      postStart:
        exec:
          command: ["gitpuller", "https://gitlab.com/stat-89a/spring-2020/spring_2020.git", "master", "STAT\ 89A\ 2020"]
