nfsMounter:
  mounts:
    - nfsserver1:/export/pool0/homes/_stat89a=/data/homes/stat89a-staging

jupyterhub:
  prePuller:
    continuous:
      enabled: false
  proxy:
    # service:
      # make the IP static in google cloud console so we won't lose it
      # then specify it here so if we redeploy we get the same stuff
      # loadBalancerIP: <IP of stat89a.datahub.berkeley.edu
    # uncomment once DNS entry has been made
    # https:
      # hosts:
        # - stat89a-staging.datahub.berkeley.edu
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/stat89a-staging/{username}
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
