jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:TqM5FatwQxPfUXTVTgh6gSfQl+obZ4ojTz72LEGj58HoMR/hwG6pfqga4I44QnFNcuBW7mhfcnZOIoxQJxAjOA==,iv:cMEBRV0v8HyJrmLJNFs27azm+uR+79LU4ng3tS0jROk=,tag:hYXfC9xio6vRnquBRidKGA==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:tf54qMRGba6lv7dMVNg+gEr1o1nFKNW7hpV71cPAeS+4km+y7pXV22EZ2mNf8i3BRLGMhKjJM81OcOmLBxY9dw==,iv:qGBXRZBG/M7a5G+5ucdhcEpz8AcmgvKU3P1xiu5TwPo=,tag:aUPrMISOFZGMi3DwLmzNYw==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:gGASt5CzgRUJsW2See+PpEI=,iv:dIQsFud7YhquUXApew93lHaz7XutOlm0YTLDBU8nhpk=,tag:ELIvMj/qmxEkBAOlFteG/w==,type:str]
                client_secret: ENC[AES256_GCM,data:uqQH2TGA+HtzqsZ6DG3RuIQO0RJ0mBnQjGh7oBCdIr2oV6ZFX93DgQABc3n/rhTq4YrUeftwapMI95B3dJlmYQ==,iv:ptqerRI2YKhgk+DuAtW0MaEKs2BfOIyLbN9+YONhm9k=,tag:k1+vnZ80wzTGKD/BOd8h4w==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:ZsshpaX3PQy/G61+FY0+07OZ3O2ZSd5xe4KtJ/Gr4+bPMoxCWSrBXlSmgAg895LuopZodqbl/g==,iv:e/byRGsBKv9nK2FmO/SI4pWRUdV0JA88yll75PO2MV8=,tag:h3goWSFbbcvTOZ3rOiJ1/Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:17Z"
          enc: CiQA67O9AEpHcG+Ke+g4Lh+wEQYMfWCJQyyIOnEtINCE1pYTxIoSSQDmhpq8p+lDeuqpFOUPES4y96EK+puWWi/Tw4lDEa4mS4udO8Unh+t393lKr7LVstnCrE8nH3IzYKXBzr/hj/xtss8n5LrcHwU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:21Z"
    mac: ENC[AES256_GCM,data:5NKNIN7fn7mvDH33sUuUH0h+QkBU8snnfGPHbo/Pbd34MVugMddxEKa7LvOA8cbd3ZH9HSKxCJHkppLeH5+JbP5Ck4dCq/tHghOSvmQw2UILpXHb+PfHpqsafUhfsunCvM3jhVOgjiWI5WIKjHaWsImTLW0JeC5Hz1FIvTdkVR8=,iv:Z4cRvUcoVvp7DDsp8bxYW1I32e8jZ00646C72rIE41E=,tag:rormrjm1ERS2ZzrNy8nfpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
