jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:VGeisaAUFNnlUKzNJNpl/cuz9fVVOFR6T5XLc3QQs7U3+9iSO+KYvMFp9MHX20dlnXmlexk/bZ/RqQOkmsODHA==,iv:DLQsWQlM3YvWx43jglI04fhUDQcmtXEvrxSjLWdhjuo=,tag:i4m5yL50O0baNnr2iC28lA==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:KdPTz9vSnIkV1pRrD5q4651lB+diGB0ZedSRZvDGX8rEKWDF5OAMKpw+E8T3oxeSx8dwXQ0ZGOK8Zmnyb6BXNg==,iv:Z9Xswoq8P5wA72ZtV0JfETNR5IFZtomlgoso2N8Q4Do=,tag:OLSxPSdvF1qTRCq+IglyHw==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:tnU5vIcm/ZCvE2gf6QkbpNg=,iv:iqF2BkXoe4uvl37uiLSfKIbNejR+paRARg38Npfkaw8=,tag:AJ4+s3Grh/bGt0VReGZ2MQ==,type:str]
                client_secret: ENC[AES256_GCM,data:+ZtquYOD5NdAkwoYh7eTSjaeXXLxhxD6OBTqW0RgsX+E6BRrlTXBPwnkJayNah8X0gh+8Ujiqv4VvUIr80b5xA==,iv:tSf3Xyehlnit0Fx9NN54DfX0FBWwHUza1SZN6M+OsAw=,tag:tGA2TiZMN8a32r6YnOISIA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:DnyLT3FXP6XBtJZHLhtxchMbCszYybhytS7Wk7stId2xjWWwWms0JE/gWqPHELkITwGvWn7OAQ==,iv:pAEi0fvzxLIR8PgdlFO41kUbTZV15zetBAzA4pZKb9U=,tag:tPgx3bH7jAtKO7bfrYI4Tw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:04Z"
          enc: CiQA67O9ADReluoHz6lm3WPGfk//AUH5s8CCJbSyZCNyv5aYNo0SSQDmhpq8D5lirmJX8ABRt83z38LzCka02dVsKLE37QmHQXQiOIFFRm29rEvuHEyL/O+Q0kaB/NsALO465itM6u3WgW6+dW+SuEg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:06Z"
    mac: ENC[AES256_GCM,data:yV84o4znKpXCvy9gjL4rS5fA0cOyvZtbsTOfUK9M/6CrWTqXQctjW61p5rngWblT2ZKwaGQbWzMcKljqmAgo9FvBIbmAjjsIg2yFbcPqCxIKOghoWP2R8q3GSNxnQ85PwiV5z6pRiZbGMncL2BgZcwvEMg51CnvuzWsmVuL5cxs=,iv:dQMCgOX6KY9mOspZ5JGH9Y5M+dAo4h50mj3v+R/uIak=,tag:ep2hKI9H0vssE9444q4/eA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
