jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:fo5dV02EBN6eSfM2ks1rfno=,iv:FmUEfcCwFPzolCz4sLA59Ne2mYBOzrfyksrabtEufXQ=,tag:eMG/GEdXhYccfsnMDq0EfQ==,type:str]
                client_secret: ENC[AES256_GCM,data:Oq7tHZvyPH/jWK+x0G8wTdRVqUIi3wmYSX+2LSJ37h1W2yrV3JAwXrfsTvpNH1jQW9DUWKpuUU4TNDEong0txg==,iv:f+29iS7LbmzDN88h6vPN983HbQbl06a5wjUg4O27igY=,tag:Wn8PcwGLHQNLDA2lD+XIEw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:Vmcu1/CTi1e/EE3dx8uI4yz3mIhyCLzcBdj+aVlKrh3DzEOMB79mea3BStFvRviOH3gWhUPArg==,iv:xSwwGZjpAsG6E0BEgYjHrhA+Cn5uKTTlrB+6g/V3coY=,tag:6HSjpI/NZZetn4Vxw0oYKA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:59Z"
          enc: CiQA67O9ADf5U4Y74W9LAxlt56HEcyJN0hs83MuGhyp90I6GT7YSSQDmhpq8HbSO0rr3l3iLylB7dM4d5g76RaYkTkxvwGSRkTW79tNcnMSuTXl+eyRfd32FCtGYzgYJbavwnd5CyNdV/y/ktGu8Mq0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:02Z"
    mac: ENC[AES256_GCM,data:TVuj7qeM9G8k5/MxfPOMtIibzcQJYQaBP0JOJ1QR8HRX0oFX1AHiZROov4pwxdcugk1ne/HRy++CebqjGRDQBLAfGTO/gs96ZaIvTVfnz/pECfJox5ozEXbZgmaYc5h++1KUAPpyPkHx09SWRJYvRsqL/0tcxaIU0Y8/1HzvWXA=,iv:9Rab7rQ0BJD2i/D+QvhB89HUiLuEWqwazoWPSctbSy0=,tag:L3WafEX1StmnlbVoVjj97A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
