jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:yuWYn9CFpMgAAqn4RruJldQ=,iv:58Y5bukVIFcU0pjBy9ZSSB3RZPdmmRzDU1eiwHcXRxU=,tag:+9jhTOpUDNVpJQjyKNNT3A==,type:str]
                client_secret: ENC[AES256_GCM,data:zRQhSoYOBsZOMpT6k0UKpFr4PUNqvEBTMFTnw9SdqIo8p+Bd1LHKxup/WfViYDdPvS9ZD5c33cS5+j4CfCgmiA==,iv:PPItATuj8Eo1Il1KQh89Y2nkPYd+OEDL5G7g2pPyKKM=,tag:CUQk80ZI4DqsuRYro4tAJQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:z1DDDQqlLRcaouqLKbDTS1sI5eE9H/bCi7VxY22ijbH/vt7Xit60k8p6MIOxKVlfu5PJbDiXI1dUklJbtWaO,iv:YO7w5RaFzZq3WqP2VI355QPaRDtauiCy7/yNiK4t60o=,tag:1ILKpcdpNuT57rS4hjnbpQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ADDJlFgW4XiaIRmUJGiXBwI+YZDUCUKmMXQcw87ZAkUSSQDmhpq8gcMvibcWzCfV8KSh+VjEib6Ojv7MQVSa4w7jG8VCSr475pm/+fp5WcUu/RbRPWruQ9DG0OLGTSCeasWsO8uf9e03bxA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:01Z"
    mac: ENC[AES256_GCM,data:WV4mzzFlTX8l0iCzRg1cjHVlW6qnzk5XBq31Bwa8HE/gf2CEu2TGuYqGgqVjXWpjz5nYWGisWeHdo2xqbEp8HlucE1GzQZsWMrJ34SqVLuTn3sEix2YtaSlX95XbbiRgO3GV8xk2w3wGLb8gORfFfalPFQx1Xyftv7t3MHzDe78=,iv:sqwq80oCff9N5RfXtnZwfuX7Puj+APIjc+o91ZtfJog=,tag:M8yGxo2alTA1rkufVBA3Kw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
