jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:KGKXwzeJMcXReVvfuiK+DREoO4LUsYzjl12QMV7yUfcraWjMUu1J4Na/sNqh7x8X2mF6sk+nKZBq5B8JKqvZqw==,iv:ljruofqrNaayDS9RIao2t4QukR28bacYf4st9rCgrDs=,tag:JJe8HmTYPyJt+Ap6GJYotw==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:KWPyzgubUOpHyGB36zC5p/mHnyjQ/ZissSiO869wcXO0m+CPESHgfR//J72G5JCdH5jz2Hm133055uFZkgmSlw==,iv:mdHygxMH8DWmrZddkOEfS6Tv/fXqN8/w++/1K8E6INE=,tag:tBZoyVozUKHjvl1G5pLSoA==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:KEaDCMBZhiJ/syFQQdlxrwE=,iv:GWfGOoScdrqLJ1gL6ZpP+soE6FBkx0qgyL8qYs+iiHI=,tag:fuZ+yKFpMdIIzv1q/TY4+g==,type:str]
                client_secret: ENC[AES256_GCM,data:MF9tcri4zy6nrICxhyla4XfeYC/VUKBtoQKkgdI6Oa2bNgja+FfEMFdCsrx7dzm4fYep8J2C0EW3J4fS3mMatA==,iv:58KVeB7e13qhisOp+/r/1h3DWgLJOFJje/aDbCJG/7w=,tag:ORst8766rrKRVlPcKcAs/Q==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:VnFeKCRoVtTXsZfN1HDmN8In4H+XoGfSaBV0486xlYTpYOGiMzjqiPRYiGqKfWRrue2RfBGFrfIZigNecz7W,iv:tVRomzkvoBv3zVoYNlh2WS6tBKpwkszqFxzFxaqUcRE=,tag:HFj4UEhj1tq8PCSdt52n8A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:04Z"
          enc: CiQA67O9ANFGA/QGincpn8bmsyt3Cpd7fiC0xzSeaL83rKE7ttkSSQDmhpq8YaRo4JPuqJOt1Px9VAhuZpcbvtxkKUXwYX0t5isnUqvD9wET94tawKppMt5UNrW8wNWXxvrAyM2j9Rx0EjSgMcIu6/4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:06Z"
    mac: ENC[AES256_GCM,data:sd84bPFd58LvYS3Fc9/aQ9tMvw1qt+vsRLEkGEm4WSLNSAhzErc9T1QCPxNgtiDa/DmNDPAXK9S3ib0YgCNQX3g6eQjoKkdc/gJhTlaXw5aizwv9v7qYtBNg/xogcqnSgSmx8CUA2iKsBHS83bB4ABY3zU884O6O6yvtJTbOqTE=,iv:uj2cGpmrHleNuuljuPQJr3Ymo5GhilbeQz9i5mLZinU=,tag:PJgHTsc2dx6ZZu2VSVELcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
