jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:4+DV0hb1V0WVwYzahVgOUwI=,iv:hOX1Gt8k6/9V9Pd+OkWT629O3iXjJmirXaZyqhiS1go=,tag:NvhjBoOoHi/C0PlI1kMftg==,type:str]
                client_secret: ENC[AES256_GCM,data:goO9VWUdl2nI+w1UnqAgu0S0E0amZiD09rqDAt4RWUtDttgIyHo5Aqe4/3J87xpj1RFnKkVBGeu8JUblD2go2Q==,iv:4NP46wWQmwZFE8rxBByIkAjQ4LdvVC4Ox2eAvpq7jD0=,tag:h7D16eqI7iqr61J/QSe/qA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:IrHwZtu00heL0e0Hn5Z5EdA2Fw8OFHvre7iHIEx40xW2OIhOhVnlx0vxXVmHOrNJSJjXTJD0+F8wfFZhKVsW,iv:0f8PwSF3gar5FYj8FZeVjOP8/g6J8bwXqUBK203aoOI=,tag:RSrTUxsj16yXM/D1a+SJYg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:17Z"
          enc: CiQA67O9AAyPw7Yd0jWMKXW602Dx6jT18L2ABbEFl+GvcTNP+vkSSQDmhpq8jDf7o5nvNr95OP/A9zwlRYc0npdyKLMumcDueqq/naJnstbiVPuBQnaWaqOJRteMS5JjBLP7sNwwfjwOU/8BFXwr80w=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:19Z"
    mac: ENC[AES256_GCM,data:fYnllqJGdqJBr1YSXUHFBJiYJt9SOFRG/TwJWEtt1kvsKEXq2ntw0vHRBLQoEHBZiCO4A4eRlT6swgAtWTEvDmle9jSs9lqDhQW79VMhLFI12mqBc9PaS/9YxhU3ZoGrA7hksrqHYmo2JpC1Z7UOMFbcNyNbJCFFXlu6wS/cEdA=,iv:HrkGA1uPRB9m4bIMDbbcoWpzWIdwTKW1KHF/LkkHzHE=,tag:gU/eHbiaPpXLyBQDq1J3AA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
