jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:sJ/d9Xsc8w1VUzWFwCn71CNYeohIi/FtdxzWjEyZ+PZxh//L6nclxEQ8TokM52o79PaaeBmPen6gKGFUPWSChQ==,iv:ucXWua3Cd8zHGTFKO8HoPSp5+7+mpsbV39wcbZ601ck=,tag:2lzctAp+1x61XxCB3B9B9Q==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:6rcePqNRIaAWQaGMxwc7/VvRwtHssJ5qiUcVbV8o2mzZLuz/vsu6pQdMc11Z/ffrb6V4nwXxa2xsd7p31GJlkA==,iv:5Xdyvv/TDIxp+5kehvrvpbdFUfFmqSfiRGV7e/+Luas=,tag:58N2vNFXEGYQJdAZygaTfA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ADDJlFgW4XiaIRmUJGiXBwI+YZDUCUKmMXQcw87ZAkUSSQDmhpq8gcMvibcWzCfV8KSh+VjEib6Ojv7MQVSa4w7jG8VCSr475pm/+fp5WcUu/RbRPWruQ9DG0OLGTSCeasWsO8uf9e03bxA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:47:24Z"
    mac: ENC[AES256_GCM,data:RZEfds7rns6eCgNiv48bikPB2tdN3Bj/GWHGaZEr9CYWroxlXunykC+I8j3aURmfYPFeW7mOpyvwqxgCBM5XLqBHae+kE4Tb37AP26vGb3O4MTXhs+27vn29XNvWc7ie/DDcTglGxQhcnxlmeEHb1FOprERNCpVs+7QcrBTxa9g=,iv:qjzZo3+NwYyRT3Uiaze/0n/NUQt9G3z4nK6VhQNuyhE=,tag:6ByNFvI1Fhp/LfZX/5pLVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
