jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:pRwAKEuHBRrVfyyDI1cp5ks=,iv:VZLkLuVjxwEySss/BW2ORZEXnYGl3tRW4gxsMb+Qyx0=,tag:vuYIywZju++N3DvrNPz9/w==,type:str]
                client_secret: ENC[AES256_GCM,data:NeMUpsCf0RwmY0tfTNltRwg1W3xw3ACtcFOUwEMARL84R/P2+BNRF7mSc3JZcLWgBzkOqR5wMLIhNyhepKsdpg==,iv:EjaSaJbAZ8lrM/5+XXn9ABsZ3XlMOvSkarUUzZO5VvU=,tag:5a3ti587e9+f0WpWlR6Xmw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:z1DDDQqlLRcaouqLKbDTS1sI5eE9H/bCi7VxY22ijbH/vt7Xit60k8p6MIOxKVlfu5PJbDiXI1dUklJbtWaO,iv:YO7w5RaFzZq3WqP2VI355QPaRDtauiCy7/yNiK4t60o=,tag:1ILKpcdpNuT57rS4hjnbpQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ADDJlFgW4XiaIRmUJGiXBwI+YZDUCUKmMXQcw87ZAkUSSQDmhpq8gcMvibcWzCfV8KSh+VjEib6Ojv7MQVSa4w7jG8VCSr475pm/+fp5WcUu/RbRPWruQ9DG0OLGTSCeasWsO8uf9e03bxA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T22:54:04Z"
    mac: ENC[AES256_GCM,data:LvT7kWdrCbXaWJgwqMu1DqMoxoaVQI7RcBkMVAHNgSSyrHrM4I/5nOlYzOAPl3RUv9OG9tK1tKYKAAVJRJzzXOPLLlR+CGFYsURF47zueh+CnYwE5VeIPdlJqTLkOghkDWV2MzS1jdKYsgk/MmF5PihkU6B/QdWZOSfaKsDNfPc=,iv:6M6ohTz4G64e3EwpxaMR03jzq50ot7+PBjQHwCA6k24=,tag:C/h1SyJ8YU88QaTm+xXJsA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
