nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/homedirs-other-2020-07-29/data102

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    config:
      Authenticator:
        admin_users:
          # infrastructure
          - felder
          - rylo
          - yuvipanda
          - balajialwar
          # instructors
          - fernando.perez
          - michael_jordan
          # gsis
          # data102 spring 2021, #2138
          - anna-nguyen
          - erika.n.mack
          - yiwendai99
          - ramesh_s
          - rroggenkemper
          - xingyu.jin21
          - yanshuo


  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 1G
      limit: 2G
    image:
      name: gcr.io/ucb-datahub-2018/data102-user-image
    defaultUrl: "/lab"
