nfsMounter:
  enabled: false
nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver1
    shareName: export/pool0/homes

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/node-purpose: core
  proxy:
    nodeSelector:
      hub.jupyter.org/node-purpose: core
  auth:
    type: google
    admin:
      users:
        # infrastructure
        - felder
        - rylo
        - yuvipanda
        # instructors
        - fernando.perez
        - michael_jordan
        # gsis
        #- placeholder

  hub:
    extraConfig:
      09-lab-availability: |
        # Overrides values.yaml, until jupyterlab is upgraded in other hubs
        # See #1468
        c.Spawner.cmd = ['jupyterhub-singleuser']
    nodeSelector:
      hub.jupyter.org/node-purpose: core

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: home
          mountPath: /home/jovyan
          subPath: "_data102/{username}"
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "_data102/{username}"
      extraVolumes:
        - name: etc-jupyter
          configMap:
            name: user-etc-jupyter
      extraVolumeMounts:
        - name: etc-jupyter
          mountPath: /etc/jupyter
    memory:
      guarantee: 1G
      limit: 2G
    image:
      name: gcr.io/ucb-datahub-2018/data102-user-image
    defaultUrl: "/lab"
