jupyterhub:
  ingress:
    enabled: true
    hosts:
      - data102.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - data102.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    config:
      GenericOAuthenticator:
        extra_params:
          client_id: service-data102.datahub.berkeley.edu
        client_id: service-data102.datahub.berkeley.edu
        authorize_url: https://datahub.berkeley.edu/hub/api/oauth2/authorize
        token_url: https://datahub.berkeley.edu/hub/api/oauth2/token
        userdata_url: https://datahub.berkeley.edu/hub/api/user
