jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:HK/mXFE11Bhap0X7d+RUHELD5xhJZ6ObIzGmZr5N6BiLxI5Ysem1svNPdDtk+xr5dH0XaFk9pS/Krl3qqIrQOw==,iv:8ubxy8toqEm2TQp0+eleIyHlkEGwB1D0qSZyNzTFt4s=,tag:J04CmwinwTW+PQSxGKriTg==,type:str]
        services:
            gofer_nb:
                environment:
                    LTI_CONSUMER_KEY: ENC[AES256_GCM,data:/k7hGBc3K9hJryKOhRxAttwR+ezLfbn7EO/7MV9LZct/mfEmR85LwkfEs9TTqnggh0cJHcH5WE/1fDLR/5fKkA==,iv:HiYpxEXpK2TZd0a9jRtxwAyE2p9MPnkWRz8czsvQAOA=,tag:7nxFLlXC0MOJO2Tl/WI6Sw==,type:str]
                    LTI_CONSUMER_SECRET: ENC[AES256_GCM,data:u6ktmK0PqpNT+QEu48h+IFVGvm2A7LyexkU1+nSI0KDN/swYKSYYZ7KxzIclqtGaJQikEa6sfryK3dykco8eYg==,iv:NIWSHSSXkNNOsdArW1otcB3SB8ThQ0wf0g/Wx2pSgOs=,tag:NcPycsNsGlNejjDKoCIrew==,type:str]
                apiToken: ENC[AES256_GCM,data:vQ8GGb/HIS2Br4qdHYthLt2yhLhFO06wg0FMUKXgmsZqmaEHLs1L2HivT5REBIQIpobZim9JEmAFQGZuTIBHQA==,iv:RvSkyzNdwYrxzhTdJ1gOrwjj6wRgM7QIFGUG1z4foqo=,tag:8bwf/fULIBVKIiY7w1vDHg==,type:str]
        config:
            LTIAuthenticator:
                consumers:
                    b34eeb75dca9b467b1e074fb3eaeed4717a6aefd28d5e7e2c8c633fb016b2f39: ENC[AES256_GCM,data:ALYihH9l8dQUEUlgaOou+HCOCFqb9Ykz9t8OaLkNrm9lxUiYfn3gCk2Cjb6zwRIJ4cZEYIMZpIFRYAw5wy8qAQ==,iv:vhYRnDpSwXrIN1DrMy6vac59nVK9ZB5vEDjOGtK3nGY=,tag:EPszPIlj91Ls9cH2Y2gaSg==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:XqFvBJY0uJ1NPtELlYgriwWdmzmUE86LYdfyycL5Cn4n9/HpGXtuJBEZNq02FXgpcOOJKJ7opd/2SjlbQx/NAg==,iv:+oVqcsr/DCc2GXfMt9i9AxV4h2n1bPItEHtJw/KIDnU=,tag:12EdveWN4zz6Fgz7hTW95g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:05Z"
          enc: CiQA67O9AEUe6Zno6nozkJZ4+mJBPz/RT0wQc1sAfMvA03Y/4n0SSQDmhpq8lEu7zJ4LPwPsHNBLTa76vOp2q1g/Oi0agcGk4DC+coTGVlMuBdcJvpJ81gJ8/z6K33uU9PeJrDY4Ru/jAL6YLqtLvvQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:06Z"
    mac: ENC[AES256_GCM,data:TtcYOSOCsdowVWKqsV1f4+8Lp5AsqSnfWxz/1VxFIWhGerq4gxGpSMoXrKODr1FwbWlrVg/y6jnaaQFeZHkYNPThJuh3fW3LOE6k+a8p5TdOrO0ui1rZx2EeS6cydNmcUChaMHJv6cxfLlHc24YwF69sBnlmz7wuP3S+Rd08e7U=,iv:ZfWTydnhza4jvQZ8ZOcc+632RDPHcNvr995olcf9W20=,tag:THls3cCwrPNmT9EOMgfw1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
