jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:5NPEPhPbKBFXh8nLw4rhlkFrU1hOpV8t5R9iVz2C5Fv40m5Li4wgiFnUyFffhIkIcM78Nouv8FZPTFwe3bUpJA==,iv:Om0DQik+Qfb6rRaJfBZ1wh6GOBgPixG+nzBnWM/ZEb0=,tag:62CoQJUI4UvIMp/3GMBltg==,type:str]
        services:
            gofer_nb:
                environment:
                    LTI_CONSUMER_KEY: ENC[AES256_GCM,data:Rhh/6NBM6otqsKywgbnjOirYrQqym91G5mV5NSjXEW8Hd+dmna5Hvgpxu2SkbNdoCszG+cCClK9Kmhxu18EOxA==,iv:73HLxTU8iPP19NkMy+V+/DTIXaYkA6VM78thc+CqXUY=,tag:ttIe00zgvLuGUz+hgVANrQ==,type:str]
                    LTI_CONSUMER_SECRET: ENC[AES256_GCM,data:KkoE2T/l1PTs3QDswwGQh5eutDvUUlzAFaZeKxkhw4gHFvVjW1dsXczXvwP9Wo3wxHT7SJodhECSUUrs5eP1Mw==,iv:bmu6lGUShxA+uO1vaX4nKpjGtehLzpR0rXUagUzoBYo=,tag:NDNj60izsOROKaZ0bdF7IQ==,type:str]
                apiToken: ENC[AES256_GCM,data:2zBGcIZY+QWt2LgJssW7yUWQurFMwjWs2dyCW+noej1S7DODe/43jJdmHYD6q5Yt7E5RVIqshkyo7+KV6rOivg==,iv:97X8tQa70On4az0jrYKoFBdS/okabGK4rIaD4MhTO/A=,tag:c9SyOEu5DvVF4/ILJde8Cg==,type:str]
        config:
            LTIAuthenticator:
                consumers:
                    b34eeb75dca9b467b1e074fb3eaeed4717a6aefd28d5e7e2c8c633fb016b2f39: ENC[AES256_GCM,data:4LwbN4RqKk2KCEmc86rr9io+xAbW3qe4AGD+5rWb0kVkdT7aEF+v0s/g0CClLgKR//iePIy4WhCKdQkMORstGA==,iv:vmJIaMGil+wkfLfhRUZTVeVBv+NpNftzTpPS/Ts9+vs=,tag:FgZCP0hTjW1CXgeYvndKMg==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:9Mirmhd5voQJd1Wgdt0ThQcDFWu9V7CpFL3+6ebv2gq9cEAagN479Khn/m+TkvpefTNBYILfNub54GDI7E1Fxg==,iv:jrFy3HecKhtC8t+J0X+0zEAy0fkvOIcfopHnQFsK51U=,tag:2XoxMFZpLydPGWPvWz/ihA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:19Z"
          enc: CiQA67O9ACSdNVUkEX4/fAf3SuC/SfYnPEr7FGBJRVyrSeJfiQkSSADmhpq8p+qqcgBoOvKsjb9wBNubmxMZPlssZmgpoPFJoFaFdoMsVll/mr846Db1F2hH71fRzyUAIyl4eb043ZSVF5JXP+/C3g==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:22Z"
    mac: ENC[AES256_GCM,data:oWas8KxpMTQUHDF3H93YSHMyqIta0YAELSjoKR3bTX2lTjOBvL7ubzFNs5turNO4tEGxOVyZBto+TlImbtlyAebsegVlvsDUQzn+Jei5e6r0Ki0RlDCBBlVRqSwcDZFi/azpgzByiI+6HuqHd0142HdniRoMS2puYTUr32dhay8=,iv:535+PsCS15jGKZGKwq6qxZgbcS8o6VHjuyJOM0oi/u0=,tag:FNJlwTmDWwICgqdSmGw0Uw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
