jupyterhub:
    hub:
        services:
            gofer_nb:
                environment:
                    LTI_CONSUMER_KEY: ENC[AES256_GCM,data:ohhqyZ7fBGdvgi8mUDMCnaID2alXnfzL8GQYMRRUDyHqh7qE+WQqgNapKBGvP4ZWL0tJMQqZbLku5oin3obCOQ==,iv:HdxlkVjTC4cbX0e+8L3fAHoy3lHFDmycOZlBOsYoYDM=,tag:btQ/GiMml354StZ1Q6oTKQ==,type:str]
                    LTI_CONSUMER_SECRET: ENC[AES256_GCM,data:/X9M63GWo0SZGw6DsBIHXnxq1+BXZ2r9anCk1KPEaDo8ChULksCuQZzI9q9S62pIbB35AGaBbezbnZk++ww9pA==,iv:tEwADN7Lfai6ws7i3khSunx/ItBaSQmWNUHMOaVBd8Q=,tag:OnB+SyoLJ7DEbETMtL5whA==,type:str]
                apiToken: ENC[AES256_GCM,data:3kM8OxKN69ZJaU77BjMEVTbljlvUTAI5AK67HYpcesA6lbgYsXw41UR87hhUyWfaw5Rt2lo0ZjUgMQcZ4KX6SQ==,iv:nu//IMO6M0mbYUX43Z7zt9aY7C/Fhncjh/uO9lCfph0=,tag:+KN9ZV/Yr2I0TH4v7KhuuQ==,type:str]
        config:
            LTIAuthenticator:
                consumers:
                    b34eeb75dca9b467b1e074fb3eaeed4717a6aefd28d5e7e2c8c633fb016b2f39: ENC[AES256_GCM,data:nJ7C8D7c9lo2Z61h19KVUW3G+uHnOP54vjIPeJGzQFeNvZoHJ6TQl8VEDZHKJEzsmWhPau31lpGIpw2ub1zy+Q==,iv:fFiHRivMIBRT0oaD7Dw08ba51Et+AVSiNJvUw37M8/I=,tag:OmTlpclWMtD/mAKUtDU5/w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:00Z"
          enc: CiQA67O9AKbjDg17FXlVs70AlTSxJlS7V5WHVGNZFP1+oxk+1BkSSQDmhpq8in3GxTmGnIYlWdH62HNhlVgnzfrPRgahWi2uzxxVWfkY0z+vgiEKX6ScHEOPkD7jMnvUZ2OMJl9Nzyeh0uMIQlpBpko=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:01Z"
    mac: ENC[AES256_GCM,data:MwrPDvcuw7ygN4wg/MrsRv/bd367y2y5HXc9UB2QsBf53FqVuRBKj1oIIingtbBOgY3dUAdV7/GBiwMQzcE1OgDsBJe2WDxZ+oRWPTfgY1o54IuZaOCeQq0AZpkFeFQnqGM2GGgM5ubgdsZ/rJSMJK+IC2PueMzgV2uL68hbsTo=,iv:yRZkY+6kalYniRGoCLiJuXMURUWWQRwPLZpymmMXXw4=,tag:WvDrfnozzUYzZltQWjz9MA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
