jupyterhub:
    hub:
        services:
            gofer_nb:
                environment:
                    LTI_CONSUMER_KEY: ENC[AES256_GCM,data:OBCHgkmqG/gkBtcJIjffVugOtZAy1vGVGlFDhLUR5W7UpTV67akc67rM61lpAKQDbqTxUajmuNWkBsaRfIJffg==,iv:KK55jKu2r7mOKgizS8FJqDwV844heP54qtssnE3udTk=,tag:ZrRvlgqEQx41YtntsODvSg==,type:str]
                    LTI_CONSUMER_SECRET: ENC[AES256_GCM,data:XW97RLTtKaNrj8cNeP+kyrP5LWfIiQ9VYhZxdXA0jf6ghbc96OuG4OxXNM5jTsNNRr8yiuZPDnVmRcTIrHvgAQ==,iv:Qpkqvvt9z5M+N/TeQVlhBwyo19qpdTUa+taRRImEFZI=,tag:hvFk53w4UZ8Ry8cJV55g5g==,type:str]
                apiToken: ENC[AES256_GCM,data:n1iTF8WDx7HShTQ20nCPNwqzEA7UfQOIwSmGYiL5hKXWsq1qezl77tWHe/ifi39kqKl451LdMuxbgSBVgTV4Dw==,iv:Put1GuPDm7/itS4LUcdrByyjVD8r1FjgAp8UOTSt7XE=,tag:SX/WSxniJbccbdVrSEPd/g==,type:str]
        config:
            LTIAuthenticator:
                consumers:
                    b34eeb75dca9b467b1e074fb3eaeed4717a6aefd28d5e7e2c8c633fb016b2f39: ENC[AES256_GCM,data:dPwkcvFo8mIt12yq715cqBQQk7m+TAgsH2e8ftt5MpJ9U/OgGAfhTQk/cm6MuY+ZOLIyu7LwcwMjXZx5Fd/Nng==,iv:/sulZH/vIJheDO/7bDySAbXbYNCgfPzK7bqeNuedeK8=,tag:ix0K1yHY6iYIUljRq0OpFg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:19Z"
          enc: CiQA67O9AKnLg6TqolG6HKXWqt9mRM4ZwT0Ex7qtHjRpO46OQ7MSSQDmhpq8EETKH9Gq2hfaMlaWU9Lr/YQ1WB5kX6EldJV76WPjEfRUqcq98KIy05p+dF5rRnWlDo3w8WfYCruNJkaY2sfSFkNzFhQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:22Z"
    mac: ENC[AES256_GCM,data:uYqo65OBwh+nvliKhNLSZRMRlUo7u4lV86y5eXAu4TgUbojqJzT75olUSatR/jHGFJAGqSHNv2YVV88WvXnu+pUzh0isRbJ944UJLYgtaRttrs+hpxV1e+ThsXvqJYd0cuB0ekze2BvnxCuQaxTK0pC41i1cgB6qXzna9PxmN0c=,iv:kW7So52cx9fNV6vejkzJ+iTnBnly0/NbFmB5jqQ4pvU=,tag:RWnl1eqU+SXP3vkW3RaCYA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
