jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:5u77/HjXdjVQ/gxuxHkc17MrOXnvJIwEhSxrFfT+F9zamKp8fFPRtX1Q97ghQ4el2vmC3EEtUfb0znjt6Epr8w==,iv:UqLQLjnx96K8anUDULOA5usBFwaO0m5mXboMJIVueb4=,tag:t2k0Qg4EmlXxzEMldFhgQg==,type:str]
        services:
            gofer_nb:
                environment:
                    LTI_CONSUMER_KEY: ENC[AES256_GCM,data:BZelSFkfF9ySrbiy5FCPSw89zq/KkExUc9gVpGP3QYA/DhsFTPMJbWYvG0wLgc35OdWvMSRXScagFO3GLumYtg==,iv:mXDFRD7fCf+7LffyiD16NzBGcOR8jFumdH1zUeBT7gw=,tag:Km6rt0XesET6f5EOSsS5nQ==,type:str]
                    LTI_CONSUMER_SECRET: ENC[AES256_GCM,data:NfgJJ7ljTuFlu+JcLJtTAvRRpYpD1vxHUDJjJC/VUO0YxqCKOupu2nb8ovbyv1+1EAt+DQgd6hIiKttEP91yWQ==,iv:AEXSNF5xeZ+Zapxn9TdjGpW1dJqSZd+ttBcQPCrU0iQ=,tag:iSIEjyBNGcPg8Qt5xe1xXw==,type:str]
                apiToken: ENC[AES256_GCM,data:5qC+NLGC8OGpVGnBgQAzmX94V6FHyrarYdvicZMvlz9Y6YyHKvaIRnZvVLPhFptOBB03iop7sBj+2Gv9yPduXw==,iv:9unBrabs6wrB9dAptCC5vQLLrJtT65rUHxKinxBFX8k=,tag:jb7rJhEJEkVBWhDaRUnQZA==,type:str]
        config:
            LTIAuthenticator:
                consumers:
                    b34eeb75dca9b467b1e074fb3eaeed4717a6aefd28d5e7e2c8c633fb016b2f39: ENC[AES256_GCM,data:U5Ba+8zSxJtJHuTw9fjJrk0LxYr6Kmpy1sk0fc39Q2HLc/Xb5YOBtAkYPzMdK28RJomaoIrbVWXWTlF7uCqKGQ==,iv:lkQ5wVJV0JtsFGjORLKargxqsdpS+aYASSZRy7gURaQ=,tag:kuaJG/NZXaUM0AFR+lF+yA==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:1DdWRVGdiCtyCLNKmn1ixJReQWzU8NQN5p+Eq1VOPvNv5xRSe22In2MAJ6O2czI70aglHJMqKCFZXqGX9MG1YQ==,iv:lxf98M0UB5uZDc6q+ag846CVNO6rnh6usrR6ZPGhlCE=,tag:cs99XobucNHFL+CyVoESOQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:05Z"
          enc: CiQA67O9APdfOoP/y+Vd8x0vRDJj6mPBnooLgO8NlSGsKaq2t+MSSQDmhpq8f3lEbQNW7VmfzD7mqlg0zYSd0kFnovFIdJ6yPzXKXxYSH098cug5p/Dnoz+0gNAEED0xU6kOsS26rJipUej8i8bs+Xs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:06Z"
    mac: ENC[AES256_GCM,data:kt8oii9Qe3d/SMwEIIf5xUHWLPJlrnoVaPxwTgEwCv2h5T/5ygxUJby1Td3vLvnGfyC8AGsyhznOLvBCZMzrKKscrQmmdaKcPHPNqflBDEMtS/BRkov4yZDEpR5qs3+4s+nvNvnQAsBAqxoMW21fj6rPo0R4VnC+1sF0/ENIo+s=,iv:PKKj3ffuC0S7M0lTJUgC9vvnJV3URvAjgtsRRWbyEQM=,tag:As9W4zYzOLi6nAUh1s2i0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
