jupyterhub:
    hub:
        services:
            gofer_nb:
                environment:
                    LTI_CONSUMER_KEY: ENC[AES256_GCM,data:6wXOYey1qcNRq3IYtSt8J0rgIrpc6W8cMlwBDk/y5O0VJZPE4GP02M/06tPYiHPJjsY708Q9/ZZh7ZnaxEhPnQ==,iv:DjqadRigPpZbNfsMZ9VAzmcYRZfzccasTHot32Oo6No=,tag:6V87NCqE7NKInRslVZWNMA==,type:str]
                    LTI_CONSUMER_SECRET: ENC[AES256_GCM,data:S2iWkqutnUrzQCKf33KnvtsLXesQOmPqTBnKdLg5/wGrtX6tVk/HLk/bkFCvJRwVbzQLjh6DXn9aMpNkd3MEkQ==,iv:LBav7amMSRcrFSYzVCS1pRfJRjBOUGOV1Etwk1Jsa4w=,tag:EcOCUZZDu+1Zml++wG0GXw==,type:str]
                apiToken: ENC[AES256_GCM,data:4WlN/BfI9h3Tjk0YNVBNI+rVsnHZrRjWBjYzw1G9f3jl+P89nYsgML2G2kqYOmLccxkKKN/MH/R+mVBqTBs/dQ==,iv:pDih9wuBbfKkzxmIQsRlPtJbfcfHNMD0BrD6x3Eo4ok=,tag:xt6orHM08pO9TtmDj2zFww==,type:str]
        config:
            LTIAuthenticator:
                consumers:
                    b34eeb75dca9b467b1e074fb3eaeed4717a6aefd28d5e7e2c8c633fb016b2f39: ENC[AES256_GCM,data:v4Naet8qrw5WKtgsinP5G1WRPGiF6WxtW1HVAt5JnYOohXuRKUK3+1k18Si1Owaue1p78w+SF+rurj+tx080qQ==,iv:sM6UOgg7winnuhK7QLwKvl+cOzNQezhZnady1pPhXFo=,tag:LQF0CJBk8Sl3FZfhr6KpRA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:00Z"
          enc: CiQA67O9AK7FKPbzwZHhJhZ6uy28ZG6Bo3qUi0FWf3xILqEWfH0SSQDmhpq8xydBxxTSY+PkfyrKHjgSUSl81BHgHPT0vs0+o2KhLv8WJ62inT8/yFDJn7Bx4kViWaDX15vNN1RkgaOI9ggDOi6HeYo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:01Z"
    mac: ENC[AES256_GCM,data:Hxuxzxatt9p3pK9oCsYz7k5uQydxSxaA3so3Gyyew04YsEBoNmyRGhS2vbRUPQmqph1LRmgVvhXn+vt/B9dC1IE5LOf48FG8XiLPGxqqM1eCovNz1cy5Va/XbN3IHIOxh+Oh6rYG7GNGMNnJknoj2R+6FlFgWKCfpp7KugM/HI4=,iv:glE4Tg2cRQyWSWzAPdwGm4zxKMuWYpJcIRVODQmmE5g=,tag:zRdcV3NY/naSnK5Qfxc7yg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
