jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:AGJNthSHfhv/jeNHiVVaNzmLzgwO+cgAUjZh2YYFhh/JeV94x0YabxTM2Do7HnWsAz4HdM+NKI9XztuEPx4zkw==,iv:3u30KeL7j2oVzOo7Z7X9Mbgdb/fCdsH4XaWjCikcRvU=,tag:cfxgu+4BXuy/Ce4K3no5gA==,type:str]
        extraConfigMap:
            memory:
                4096M:
                    - ENC[AES256_GCM,data:c8+vrz4u6g8S,iv:mi0N8aY7Yy34Nq0zg87V4Ap32xq2dRJAoCB1eWJQ5bI=,tag:siYf/S8s79iGdQh8Zi9q6g==,type:str]
                1536M:
                    - ENC[AES256_GCM,data:BcR3MQ==,iv:J3XU17OxzISzCVaIqwiQLT7DmoyOH/E9gMx7LIghjcU=,tag:BMkokX1eKv1m4A/eMuOtcg==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:1U5hPMga51dTK5TB7jNOWtQ=,iv:kb+Yfy7u3mi9ifB44kZK+R1Q6V510/NA+bHQXoYAf7A=,tag:pR0dPx3830uFYnRmZu3O0g==,type:str]
                client_secret: ENC[AES256_GCM,data:ibUc3oEfQC3yrQzAbjXIyKHSCkTMlRVFuYiWXxMtgUYuKBYuKo6dQJ9SRNiN41IaJHlzCXMzO41Z1g/UgIreRQ==,iv:sgDAcv2X1WbD2yqOmrfQV3+hDztU6BpsrLp1OFFPACw=,tag:7+pcak0KxPjcoX8fIoNwLQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:NFqLwg9eD1TbOoEkRebhF7s3qnthayEscyGl1wSGaze+gtEENEAdeoYaqT6BFLvxdT8QiTgu7Q==,iv:vlgTc3SpmANBP6JeRgFtR0I45NwbEuU9EBeRjRmzEro=,tag:wsqhMmUECmqli4kq5/UIxw==,type:str]
        extraContainers:
            - name: ENC[AES256_GCM,data:PwyF6+/L0wqx0m0iJcxy+K7ecQ==,iv:5cTtez/mm2Ftu1SeqGzlMC301gfbzqVK3xghg6ieO6k=,tag:oGLpfvNtCw4KOpMh+Zo07g==,type:str]
              image: ENC[AES256_GCM,data:BKmrgbAmmPtrJyEWYVHQi7HXn+oH63LBfhBgDAXxmj9my6c=,iv:tf4VpNO9COaWomgf+qxpFrovmYaKhK8WHvJPZ7Hb7V8=,tag:97Uw6AP7vil7vxmzDoCgSA==,type:str]
              volumeMounts:
                - ENC[AES256_GCM,data:klT7Wn2X/PMwuq7+FZpJgDkQkMo3/mJQ9QQDDHXP6j3udc14bmlXS6+UbEZbSbm1XV0=,iv:XivZ7o3xzMfYC2cjBPqp/0mW/dBlwSAqKxfyjNoCYI4=,tag:R4dkl4DFT1sax8BgcCjcvw==,type:comment]
                #ENC[AES256_GCM,data:Uc8RKYp8isRMq+JYCg/UKvh/npc0V8vo/FtexxQ+Fn/JH6ZEKuyQKpqrTiQpqEhxw/g=,iv:W1vFHVC4e8RnS+cg6WguVK8gn9NUnlBt47CEpnyaZ34=,tag:nT3d563Ab0v5AyPEAYBLvQ==,type:comment]
                - name: ENC[AES256_GCM,data:j/RX,iv:L32BOnzYVn6sE/YJ1EzCKHImZPuB4Xj+iUYTC+hIkdI=,tag:hqM5M560msRd8D2VdPLhjw==,type:str]
                  mountPath: ENC[AES256_GCM,data:i3I88uy12twZDDkXWPGE,iv:Jja9OSNf4XhjBCXt66JELYRGBc6KbMacvcAtc4u7lRc=,tag:CseMIUH5oNzmz8/k5xyMsQ==,type:str]
                - ENC[AES256_GCM,data:J2k5p5exD2qXySmaoCv6Ln7ieke8TEGO,iv:F+jUq+Y8Imp2NPlKJUW+h6RA2ZQBSR5+MWNWANZrXu0=,tag:/lrb2HAev1HSmCDEk7EZ5w==,type:comment]
                - ENC[AES256_GCM,data:DdgVE7ccWr4uMW+Pa0sQiYhiIMhGEsrL,iv:5zX/O0kfTenYElXHxAyKUmjnz85Zx4IC4K7YRp2+zfE=,tag:xhSMU38Ne/GmXLQ2B3vWWA==,type:comment]
                - ENC[AES256_GCM,data:fT2BuQdxiueaCIotQ4FXfQQNJQ2M08wf,iv:HtC1USvxu4+Y6z8P0gu7/L96JD2gGcs/+hGTNf93exw=,tag:DXDwQwfx3UByoBKrDRkwdQ==,type:comment]
                #ENC[AES256_GCM,data:lJ6H6N1ownBjxneOHeUgeOuhKAO+nhFW,iv:ZkFkuPccRtfFzlgmAahvsViB7+XYvIGlXBq+wrXSCqI=,tag:jxVOvhcIzpCbLQWWekpXTA==,type:comment]
                #ENC[AES256_GCM,data:vl3JG1+7OuqNX/z1ov6qJGAjOO7FneLX,iv:wQ4flNH/jMXsAed4TM8c1kpAc6HH6J3+2/EU3tMCRl8=,tag:iryF573t9T8aWE/w358ByQ==,type:comment]
                #ENC[AES256_GCM,data:Gcp0LgAO/V1IFqC5naAwMV5pF4iCTBYJ,iv:RsVqQm8fMBpNSRH7R/zKpSjmmD97sZpM59ZJs9tkoN8=,tag:MKOQbduXV8vk4TodQkjwEg==,type:comment]
                - name: ENC[AES256_GCM,data:umDiF7Cy,iv:Mw6AKuoQtSEqKXwhJU9ltSota8HcTOCZATykuvEvl3g=,tag:bqi/dAFM5dfDcw+z99Klvw==,type:str]
                  mountPath: ENC[AES256_GCM,data:osEF5m+L0p54DfO8KW3Ay11kB27+IQ==,iv:dRgVzB6q+O8LZD+JYaI1KEGD9giEME39ZeJdCIOXZJ0=,tag:pfEUvKG1nWYC2kSgaLfZyQ==,type:str]
              env:
                - name: ENC[AES256_GCM,data:hwUmVkwI3Io3,iv:o2DGQohoY8MPsfYCIOxBzX8n9sRpd5yKDKXJdfg8Mhk=,tag:QPpKw6q4SMElFdGJGDSf8Q==,type:str]
                  value: ENC[AES256_GCM,data:iJz+mSx8qAA=,iv:+rXuNzg5V7ARTubrz31jjJ8ZjXbfdZjPfLxSV1lx56g=,tag:VkAkCL5kbEAq90ATn9suWg==,type:str]
                - name: ENC[AES256_GCM,data:H6RKT6CBFjdxGw==,iv:ysK/gbnBtV7nSEhOZCQaU7IkdobYvMEPQUvwPApXG5s=,tag:K0dJOjmNTYz+wjh2eW9hMQ==,type:str]
                  value: ENC[AES256_GCM,data:encoX0J0gJWDq3HtwJD5rKXrtlgZek1UIpBsVg74mYA=,iv:CYgsoP0IeBtCkRB7/RTT6aoVBLgYtu14yeaLvv7KUxo=,tag:PjTaHsnQ15ycWvvklT8m1A==,type:str]
                - name: ENC[AES256_GCM,data:v2/svYz0NmsFdy/HoFs=,iv:TMbYeEl6o/+cvMjG8ucdHaSrpgSpKNVO3OxYnTpXOkA=,tag:8P8mDLZwZ6uSW+T/kpV2lg==,type:str]
                  value: ENC[AES256_GCM,data:TEkUiuK5+8o=,iv:0WRULQ5qvaSysuuELlI4YwoIDS+L28Jy/4xkuuuE5Kg=,tag:KsGzWjzlJcTJzmf2HqdZZg==,type:str]
                - name: ENC[AES256_GCM,data:x+iB6rvrdpJgJDrV8wlh,iv:S26hkjHVxWbc7fYUDRaOAjCNJfhMwEyvdKXpitSFpak=,tag:PfPEM1S+GfpIAV0OMbQf7A==,type:str]
                  value: ENC[AES256_GCM,data:YnErPgtwr7B1MHY2L3MYQOEPY0d7aGuxh3NRx3q0VlU=,iv:DoUOeYqzAVkgCx9SphCm4s63xcWVAFk5/Tu8qXHBDN0=,tag:AL7l+RU4wXPZS6dYoFv9ng==,type:str]
                - name: ENC[AES256_GCM,data:F00ooesTlZIgerHt7Glsru/K,iv:i+LkZrjPZBf6AsoeLNTCbRyUtNRbnl+Vj4bM/cR+fHU=,tag:0zP4jAlW40XvJoSBUy3h5Q==,type:str]
                  value: ENC[AES256_GCM,data:dBpw7xp9nM0=,iv:T7fmTNrhb9cBL6VjXNhacwCeT0y4Hq1FYdqmDDtWYt0=,tag:ZK18Hh11Ij01AgxcnQ978w==,type:str]
                - name: ENC[AES256_GCM,data:Udde040+0GMRcK5temgtZa/8Aw==,iv:FpXUrEF4d/u3QCEVLaKhzhy/CjbWkpMPiMN35rz45TM=,tag:9vyJ+n7lZLVtg2NBfIvZAg==,type:str]
                  value: ENC[AES256_GCM,data:Yrsq+oz9f0cVK84/JZkBg6vK/qG2GQ6y5eZR8+Qc/oY=,iv:abl5XOd0rHONjoDsYtyaXQM2r3gx+QUE6KSeXbQLkCk=,tag:eiGHQu4H963ZsldhgIKxUg==,type:str]
                - name: ENC[AES256_GCM,data:ipZiocscDCIBgW8t,iv:tRL/XkQW7+Gu0YzGpwpKObsTv3O9j6++mnubsJitRnQ=,tag:fzwZuXn7s0zlSUFMg65jBg==,type:str]
                  value: ENC[AES256_GCM,data:cuHq32/QBSw=,iv:S9U7vUUGC+ntTPlAuNumh3kuGrV9aOoN3w4yF4zJXKo=,tag:bzUjE30whSodO0bhwdlidQ==,type:str]
                - name: ENC[AES256_GCM,data:H4PHHmkebWtjV8ui+g==,iv:rGQYgfNCIFraZckCOBGzQ/PIyJXKkRAbpFCBnpbHY7U=,tag:bspPgs067PnOA5yb7lDA1w==,type:str]
                  value: ENC[AES256_GCM,data:qtwTp61e2HQbYRrdFqtmTfHCBNkTWRSJRM1dYGbMg1M=,iv:xd55UBS9bj45xB+EFlwaQCNAQ2z7E6t6tChqfPgwC0E=,tag:OrOrSEOPcLI55RTbhxq3sw==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:BATSIiuXx1mr16PpQkPML5yMwUfg6C/U11xdZlpCb13etuhF7E9CzngghmpoTtP5xyiE+w5cqIL76VZSydaJ+Q==,iv:8wvItHeTeug3iWU2ajgXmX2naG4xupmMf/vmr6w2MbU=,tag:ZtcgmCxibq0NdcQa/amOjg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:04Z"
          enc: CiQA67O9APt4TDSOivq23KdPvL5skpRMrVtQ3RzmDjaSkUxe8o8SSQDmhpq8G2B71Ymg3tXE24itL9fzffgsboswyLmuV4NWuXJuN6nzZ4BPLzw7W5LjZ02ZkQxf3svU+1JjVd3/8Vlc/Yd2aqM3Ew4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:06Z"
    mac: ENC[AES256_GCM,data:tM2A9fY0q94jczoagidxTevgB6Cfr3Hf3ZQk4wC5jwBkHA1TmPBdxN2Bpfr+I3aLVL5B4N/FIX3hwpHViA//9hV2SlWSt59xC4IibksgDW0BQLohiESnPGsT5OD/AYrBVAdbR577Vm0ZjTBJUufKheSTY08LrycYjWL6NBSdheY=,iv:p55G0q8TF6DvX0wQ6YZ5eXEsopBePYKP/hpyPkoYfD8=,tag:bEImlXEiTGl30OfiLOASuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
