jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:zsjm04gm5pren7Hab0jZu8akkYsUSHOqbbZ2ymqlrXW7I61pBGFePvOIsZ60Hbu5XVbhBE67GXF2UT3+zEWM4A==,iv:Rn3ZTybXg5HlsQ7MCoHfldYKjes5AC1ts9ZqhPeUGe8=,tag:1aoh8vxMl2zMKj641TMKOQ==,type:str]
        extraConfigMap:
            memory:
                4096M:
                    - ENC[AES256_GCM,data:ExGr4o9WZPfz,iv://v27hCO6yBdIVQ8ghH7uPnJDpwfx2cFcSfhkNAOJrU=,tag:4eK9ddP+xAQ0bOqGXq994A==,type:str]
                1536M:
                    - ENC[AES256_GCM,data:/rBMcQ==,iv:JEOuQMyfee5Ei/CAv+CRoQwSL6iXyVndQm1B99Qft58=,tag:06XZ70YMbJNZZzHioXIZmw==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:hMjDEtSjqTe+UygKV/o2weA=,iv:ug6pfioduwYkGrm/pZCZQFAdMNv7ww+suNiikrGDR8A=,tag:r/tnBzhPRApj66tSnoXmcA==,type:str]
                client_secret: ENC[AES256_GCM,data:lmeX3uFBzA89ABmeyF23c/TcfhPD8jaZU4xnWwXEBH/CBrcZZV5c0f9tBERVkRq3wv+otQNdasE+1NC/9Mnf+A==,iv:zvuPlv/XToj/AOM/ogO+noPPhPBcNubRAOmpORmG1wQ=,tag:L88lThAwUkpsmPT5c+pXrQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:4/mhZG1Jq2l4bUg/Lvh6LtQYbIZzBQEk88YnEkyvq6XsBVtLoY/loSS95M00iMCCOhVggLbW6g==,iv:G12x6jjAG6EEzs+71XGzJegdfRpVrR4KKdu7TPcr/GU=,tag:OtePr+PkCbQV3eV0A0STLQ==,type:str]
        extraContainers:
            - name: ENC[AES256_GCM,data:hgbEZTBGgCy0AUzQssLH3EN2uw==,iv:fm6OL6MkJnfvxJ1AQTxBeaB38MyHmK/jkd9C3aCvSFk=,tag:KwIEtB0dw7bWLLhtQJBsnA==,type:str]
              image: ENC[AES256_GCM,data:KmBTyoLo0Noe13uqRZBnOVSX9NbC9Zdwix7JGsYQezc/k5o=,iv:9CZVJg70AIK593crkzw581AiNPMdqDJWxmYZGy7Bb6U=,tag:okSKaQ8n8Yg9jIYyeM93wA==,type:str]
              volumeMounts:
                - ENC[AES256_GCM,data:Rls5vpMZ3oYg9hrJubyOfZqlxn4WTwrigt86X7OvdhF6xIMkfkO0JOXzcoKfB4X2oD8=,iv:21564LC2J6p/saZHUSXua3kKsSGb2TT+JOPrZHpmzCo=,tag:eK46lryEoSQ5ehDrrhNOZQ==,type:comment]
                #ENC[AES256_GCM,data:AJA0EaCSmFFYX43QSHdXLq3QmIgEd5TjQiGfTqfXVCYtltohR9TWkMIdmUYJoKQOSk8=,iv:hJxs4aTPWgw1zRrkVKP7sIzYLoi1SADtbZL6L8AStfQ=,tag:OUdlarRQh7rfEYDj+z6uzQ==,type:comment]
                - name: ENC[AES256_GCM,data:W+EW,iv:MSHwel/cfXB+Qa4Tdt4MMUtqG3ucsufti1poXESK2Mo=,tag:xOk7jGDPSJQEgC8jdoqmqw==,type:str]
                  mountPath: ENC[AES256_GCM,data:dCVwbVH4YJs7m4Gk4xgC,iv:eIOGkNpovut339YSQXzpSRzqinRsn5qDp5RJn7Yn37w=,tag:5JVhIFmb/NPm435ai2YX1w==,type:str]
                - ENC[AES256_GCM,data:EJcBayuiDvggidOizO1Kvzcn4M/L1wBV,iv:QMoi4+Jv6gNDnfyk9RSXSTl3s1/AdKiZ1sGaFdXguOU=,tag:9RwKGtJ1/id+nWLtOkJEBA==,type:comment]
                - ENC[AES256_GCM,data:oblPVVRWdxp8Y6w4fskbetYk7wd5/r+I,iv:9LDzPxg/YCWvrQrXgTTOKHVZ6EdlNvx5lkKGJa0IcME=,tag:cHla34IrjW7iYDKU32kGcw==,type:comment]
                - ENC[AES256_GCM,data:0rhCHE0Vp7EcyLHbAmYRst+pT4Rvs8JT,iv:Uf+krqrD8OL+lzr1TlmKKfuXtRdQ5drXS9Fqg9P7rbI=,tag:FR9cCbOpwmoRvOdlnqHImw==,type:comment]
                - ENC[AES256_GCM,data:4hGwkaj9A364lgNzyRAsuMVjEkyowQFu,iv:MBfE3QKqGjKT5+Rl9nDJWynhzuvIAGFaxyMv+GIcuPw=,tag:7HBkeH+fKxVo17WeODT4KQ==,type:comment]
                - ENC[AES256_GCM,data:xQPjnjU2pgvBl4JOC2lFcA/otz6P7mqO,iv:7bfPPn4iikSmsn6h7sBTU8TRp1uS9z/iTZaM4d8hIaY=,tag:oq2K9UgOcsIjVoctPxuXug==,type:comment]
                - ENC[AES256_GCM,data:xKbYN2Mt1wc4T/DHRa11h7NFURcFPZJ2,iv:aWRHFKAN/J4cPS10gs5E/1h6yqHg667r+wKhr//s9DQ=,tag:9n+cyTStaoTfVaEPJnz8qg==,type:comment]
                - ENC[AES256_GCM,data:lv2yrqaK90BBxWdAVU+I5/Py41zKng5q,iv:1kYGKy1DZVLn/WBz3JrGnVOiYHXw+SNIH4Jbscpv/lk=,tag:rOeuNe54TXSZ9SYmz72kTQ==,type:comment]
                - ENC[AES256_GCM,data:INYzPX0XOnc9FJUjI9HbmBcAhh7frqb7,iv:P2uayt9nvK88nbd2xK5ah+AcGi8MQAwsGJx8YPuNolI=,tag:AW8bAE3dc95nTuMtIyyxCA==,type:comment]
                - ENC[AES256_GCM,data:exxpN34RcT803G5TPUJ2JiOoYpQeg2Wq,iv:LaE9zeKWybMU4AEv2A+FH7R+VFL7HFkY/KXPYiOXVc4=,tag:AFxoQXV1fnzjUrq9FQKarQ==,type:comment]
                #ENC[AES256_GCM,data:VXe+D/1MkftFegdgkPC7A44akjruBcnp,iv:HBg0LsT3eW7iDzkR+/pHdKELVB9XNOmpknpuyDiz7yM=,tag:Qhbficg615pcLzRkzPVkqg==,type:comment]
                #ENC[AES256_GCM,data:WG+huMxFJqMkGS1avfxA5JnCgMDToH3L,iv:u+iUF9nMRSiaKFvDiWbFXFSTRmADQF8xGbdWnREcjMc=,tag:JbM1evVOvFU2NOgk876jCw==,type:comment]
                #ENC[AES256_GCM,data:RLBbTDPjUrji8AkV8qcIcn6AkwE1DErJ,iv:7eZLGINlA8+f8JjkKFResOCgUN7UOWZPTA+0R2QENBM=,tag:NRm3Z8R+lPbua0uAEXTZHA==,type:comment]
                #ENC[AES256_GCM,data:MDFnZ/jPO0YqnjQ+UuLbqZLg7TsGq21m,iv:3BC2dw/ZAbYKMUM+m/btQmHmAH5MGC5B422vAn+tCEU=,tag:Je+0iuj6CWoMjU13hej5wg==,type:comment]
                #ENC[AES256_GCM,data:eQO9vM5Jt8XD6/v9/Sczs8ArPmBWdKKA,iv:tLkkEKgd8vi6Eczwp8JSUpaJbYWmqaK5+8ej7OjXsy0=,tag:lS6gf0dAc+S1clnzFw0rhA==,type:comment]
                #ENC[AES256_GCM,data:3r7BDRQz+7Iq361l9YdIG7KZLTazLeeG,iv:TEV1Lo5IZ067g4ysjNv9XCTeIqmb9+T0wwEsauLNcVA=,tag:GA4lstmzLjNlhSV2/gGZMg==,type:comment]
                #ENC[AES256_GCM,data:vB0pwhncAFi/Wx+tO8iqBM8FDY5lwtOU,iv:33JbP1Qva/X8o/58UVCb6veoBQCqWFwM1WK/X0PLStI=,tag:acRuwryYxCE0WPRS0yePvg==,type:comment]
                #ENC[AES256_GCM,data:40VpMJGJVg+7YNyJKSmmpNGl6mE5G8Bt,iv:/US23D9SawH+iCPqcLKW0ld4DgXr+4CTznP3fE2VV1o=,tag:TolocwtZcDh4t4yDN9ZQ6A==,type:comment]
                #ENC[AES256_GCM,data:1RpuYwzU1Dj/WWYuIlKm/EKyiqxYQx8C,iv:Sfh1lRAgOILJ3cFRqlvtVHEkietHQ/U+7ZkAI6NU5hM=,tag:pe7aUTYfvI+WSFd0Ky0dmQ==,type:comment]
                - name: ENC[AES256_GCM,data:LAUJU2lQ,iv:SkYbJjZfjIrQjEHp6Je0bGinCgsFY7KeeY7O5/bFR7Q=,tag:26v7DDLechOt9rCE2uldAg==,type:str]
                  mountPath: ENC[AES256_GCM,data:nD6nQY/GKN+C2p+LXQxIJ7eHvlkJ8Q==,iv:hR/UfJO0e6l2saP5hIY2XxSZotdPEIZfOaRzE1QRevA=,tag:+djvvE6ELCimefnVtBmSrg==,type:str]
              env:
                - name: ENC[AES256_GCM,data:OmGB/Oxr486x,iv:s26P5Jp8MSLCgMo/q9XONt2KSj6TXK8Y/LYvwDN+ULw=,tag:U7QI4gkcY+VXIFW4cj/bJA==,type:str]
                  value: ENC[AES256_GCM,data:daxy1idsznA=,iv:NkKIhhrYYjU1t1z7TntbUMoVL1LZdDyVhmUBo/HRwCg=,tag:eQBD381BNmRMhS08DJwVnA==,type:str]
                - name: ENC[AES256_GCM,data:VaUA5lHNRKgvKg==,iv:AtwRX79BCPiB/+f8sjndRYHTR8yDdBspjd/qY49JmEo=,tag:J5VU8nKaHN0JY0qcB5uWjw==,type:str]
                  value: ENC[AES256_GCM,data:oXgyR7sK0fRbaLs5POQcxKF6xXK5sYAxIzXs0a7eHoY=,iv:xwZEd4vkoFuMmHNRBM3TRNhXAEQC6PgAg/fSv16SzGg=,tag:QscF3cobhMH9HZK0z3u44Q==,type:str]
                - name: ENC[AES256_GCM,data:a+Vf4FStxkMTCNTEAtY=,iv:MLiVvllxb95qi8mrLoGc6S9kGGeFW8HbxbynBcQ1DwI=,tag:/TbLqoGGWc9qe0JEQEHFIg==,type:str]
                  value: ENC[AES256_GCM,data:IfMz8v4m73I=,iv:JmBVI1ovHN8YyOnXhc4swH86jKJ7JFd+pA0/OFLyhRc=,tag:+seB84XCqHRolVXRSWhNZw==,type:str]
                - name: ENC[AES256_GCM,data:tZIerdqxB2B9if1xYfzd,iv:byK4KeMVh3mPN1yOO5kDvRbhus9/8G6YBCyiG+XFWGA=,tag:r0GiAyoyf235hBYgmdEZZA==,type:str]
                  value: ENC[AES256_GCM,data:qa5+lxWREUdXQpI17CMsUPEL19pvjzvdn6xcos7RsIs=,iv:sOkqWKzYc+3CBvpd+TrkQ7wNeTxg04KBCJoNoMTQSws=,tag:qduXFugPnRxbtiY51DBOAQ==,type:str]
                - name: ENC[AES256_GCM,data:Uz+Ni3zSEsGXbTFNp0iYndxh,iv:vXYGypUE/4JodYPMXgjGWVIxwsx83aQQCJH5O9TNzuc=,tag:Rr+AqwxI1/rG4HQSThinqg==,type:str]
                  value: ENC[AES256_GCM,data:PKwAiwGfIuY=,iv:JMjBJeaH5gzg/8eWCbCji4+0SmmUyHOPe08zJ+xXjhc=,tag:HZ2+DkkbFOVXptafhWswTw==,type:str]
                - name: ENC[AES256_GCM,data:BpxqblMgRSmBqqk2MBPs5jWLBA==,iv:h2Sh0vRTMDzxDF2R+ZxmN+QLoy++NDIlmejqriVx0dw=,tag:iKmcGyZ8XdR+On5RQyyaFA==,type:str]
                  value: ENC[AES256_GCM,data:4/eSHX3jJUuRnpkp/OhlqGtnF9Cq5pE1rKRBMEs9Ou8=,iv:CcEDdPH6Kq1kvbfi3fvLOINVRqfMC1k4Ogp/O3A0pKk=,tag:HQ9AiX0nBYqfA7N84bhqOg==,type:str]
                - name: ENC[AES256_GCM,data:2U1bNjUy8dHhNArI,iv:QtT9ihXlGcQQJ7754Noo3JjNaOuqfcbjO/sTpvV0gSE=,tag:uDMcYZNlR6bUVPYI1o7m2w==,type:str]
                  value: ENC[AES256_GCM,data:7JuT4yYeZkg=,iv:HWBBWrg9JHVt8MYoSeoJA19qx9XMY4ENKz1cz0hHdqI=,tag:QrZNec2AAnFk1iIZaTcvEg==,type:str]
                - name: ENC[AES256_GCM,data:mFe8uljiC1YVxfT8Sw==,iv:v149boCv0dlSdQhHAxY4rLSTer1UbfnElScTTJdsCoc=,tag:BrMBl8Ma3kbAX3JRYlrjYg==,type:str]
                  value: ENC[AES256_GCM,data:wAdAnBHuup6sQg2zhJFxtcCciYhtuGFhSCuDzu2EdRA=,iv:9N5Zsrk0odpnFrx6EmOZbCCAP2ahHrmRl9QFVknirwA=,tag:RHmyY3GdGxcyoit4umc7Vg==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:RYk01RnfKzqRgBuNWf0qq5xNn7EXLFhZg7IPHu/31lLk35vHyHFi8Fq1BK9FCVuOAV9IYvGOkT2TnIUiH0XbxQ==,iv:aKmMSz7Jt9Huhv/ZPCGlYjoH8sSehKgzMJaABoT3UwM=,tag:WMZigs8mDV/S1vdReWeGLA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:19Z"
          enc: CiQA67O9AJwytf/cj9J5dnpRNiTYeJ6ejLS+Jdca8/jdAm5h8AcSSQDmhpq83ZEevrPxl0/S+WyrR84Ih16rET7LyaUQYmFbpit8HHVNAFpQzbTzTz3Kogdh8BDAIsITRBTGHg0h7jfUUujnQGaz53s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:21Z"
    mac: ENC[AES256_GCM,data:5ybst7nF2XP7scWiGH7LO6q8emc/rfzh3DgY7mXM5oTWCns/TtoBpLCBX8lPiILwBfK3hmKlZNcAQzuFNdZNr9aYFvrw2AGga+gYM4EWJLzD2M/7IwDmU+qbTEcrIcUXHl209Ej1rKrM0iNuUmhzqmQNC9LXpHkOhwlGaC3FlQo=,iv:kvQqafN6VtOV1cc570v5+Ir4ol+f4msNGel/THkFBkU=,tag:xr6muQ4x2fEdf27ahRE7bQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
