jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:CTmdlmVpOgkd5+tFeJvSQtfF53fvg/ztEQ4dPHB7ITYqWLgTqCKZWysEO9zZN/Qh6ttRWx8OSydonho+n3mfIw==,iv:JvkE1mx58pLOUSAXLve3rnMsDptyukrGZAAfIPQa8BE=,tag:DBlw/HG5jDnwOTE59H4EOA==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:tX4lMWxAA5nZydf/nlMk6mqfpUUc4P/KgWqdWxE21xoIA6WB/CVhbx+MzulM8m+fYHI7Ix4DSt9sVAyc3Yy7gQ==,iv:Vwb66yc9ofyipQqWxgb58UaF46XUaF+c4Tw7PtMhsKc=,tag:9yAsRQ7VKO5uf9yqS9VAEA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:00Z"
          enc: CiQA67O9ALpoZQdDjz4LYoS02B/Pf+TZfImPg6v2Q0Xnbd7r1cQSSQDmhpq8qcl0J95ZZpcyBAwzpB6AMCEtjhkrX8dOvb+nGfyWYSBMi9xeakYuwrbRiblRrhDyvnj1sdSs0OmwiQ8YQ0eD7/G1StM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:52:14Z"
    mac: ENC[AES256_GCM,data:oSIbIUEFv3jq6rdtCjpkVdXwHMPiqP/pVc5zUwvE09OqNwUchCCgK7o32thTDNG9XfFQOKAqyiazmrxn7D/3rrDYkqi+DQGpjMNu4iw43AGuXMG/N4q60j98kHj1kNqDeKSfh4R3Y0xvocoFdNj3zjk3glBzoUc55tOp4bp4QIw=,iv:DiTY8s4s6UxhlNu2KIJS3JzeE3qpqWlChfuufHzCwr0=,tag:Dw30efiEXNi4FX0X/Lmt9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
