jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:DIoJkA1NRHypylJ6xoompfc=,iv:vAd0CcaF8A3iTCYPoMMU41ejZkiKjRyHJJAKc3ibbIY=,tag:6UPuyXcQOvVzIO/8yBG1EQ==,type:str]
                client_secret: ENC[AES256_GCM,data:Z8HUPX2gwX6snWYXD6qLwANxqWkDmX5FDygsFvE7RofGeu4DPEcdmzsPriJxxo3BW8GFy+8mv2jYEdpe7dXdyg==,iv:nTeWIs0AaYo9ihtufW5ydwDHkcD/P740bezd22d2n1s=,tag:iAMZbnDVxBBm1ubQYTNk9g==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:wwHWlTcl/zUHjEXuXuXjFEk5aXeYZum0j6g4xYa/Tq89p9GseJb54oDhw6AV3UyOT5ovdwJ+bA==,iv:v9vDjVXNzW5NfBJ1gPbWycjL5h/1Wd6/Wwi5YOh0noQ=,tag:FtuNEr/KyIxXgYovaBh6Qg==,type:str]
    custom:
        memory:
            4096M:
                - ENC[AES256_GCM,data:ejbPjz0HXRLU,iv:juOUM+pxhWCVx0wW/9uEWZeo3ntRTClxswI6D6hfRpg=,tag:SlGcsONKHb9IZmgXYGXSmQ==,type:str]
            1536M:
                - ENC[AES256_GCM,data:9BgZlg==,iv:i93zEMJqc/SRyjlqHD6+tFMiKmob5Jzb/s/yk2U0SRY=,tag:VQvjSHgPAtCxapnmuYr0HQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:00Z"
          enc: CiQA67O9ALpoZQdDjz4LYoS02B/Pf+TZfImPg6v2Q0Xnbd7r1cQSSQDmhpq8qcl0J95ZZpcyBAwzpB6AMCEtjhkrX8dOvb+nGfyWYSBMi9xeakYuwrbRiblRrhDyvnj1sdSs0OmwiQ8YQ0eD7/G1StM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-28T05:45:39Z"
    mac: ENC[AES256_GCM,data:4vLRSwu0HK+jG7JLg0NwYWBHcvirBGnbtsR+Fe5KE8uFYErko9f+6mAViYS9pux+PkUCc4uw1GfDkbd7IBFCFNxGPS6IYYJQ4OJ4aHIILxZOjPPgjJPZWOKmh9c53Pbc4TOJ8bScn4o8O+PT0G65dwmblSA6SSdiceFGT6eRTd8=,iv:paOOaYesbMEsFxKFW4LGIFkvDiASTNCr+pbh7PjsYn8=,tag:7hTvBa6kOJcMZKcCuuvmVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
