jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:b6SA62crFiiSMYdTsr4BLLqyWJZ4Gs5ILluySLFOaeWrt9Ht8LgAwD4gtOkrURACzG9divrDdwTynsYadpvU+g==,iv:RzbD+N4RWpOK8TqOBFwf5QpqLJEXjuXG2cZz/X11LsQ=,tag:JcuCTo0zWcucEGs1N0FZ/Q==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:18xoXjAtnlhFYewG/mG99BC8OUbTT+qe0VYCxPYkH10/rLhXt1oAcc0W/mgbYLj9kHK39RDiPHM7xbb2SaCjxg==,iv:fq7BJ5GsymODL9YZbYgC1aRkDbubL0YJM8UFRFJ8zRc=,tag:+jyGkjXnGykCMH8p6ZfJ9A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:59Z"
          enc: CiQA67O9AIxTFmAaS7Bn4Z7Ajn2VoJZAViDi/WlDGi70sDj5R0wSSQDmhpq8XeOOpmygjHorUvvXdUfujdzf6cSD1IPuz3JUc900UGL5QtXFfLMsfOb2fJrV/h9xhm8Kd1Ub3WF/rSpdG2HuS7kn6PA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:51:33Z"
    mac: ENC[AES256_GCM,data:E3cGTuDMjlH7OWz32gI4fW9sgnVGJzfyEWI/zqC6v/DW2uTtwKOLtYMwF+JjSsb6a2vhyfnZi/r+4FLcpFtsNiweJjbpSu6MpbPUSdwU3MSiwMDFYjQKN5rMw2Q7P6yvHWn95d026FPdOFzkvqhhX+1oIvxRD/WhGkSiniaXwpY=,iv:4ZbMFUn8oaTTpFktzA3zk9TCFG18zlxH8HHqD6A1rek=,tag:cMWJQzIHwBI1gonKkL1dCg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
