jupyterhub:
    hub:
        extraConfigMap:
            memory:
                4096M:
                    - ENC[AES256_GCM,data:sxhEPJJ0O5Zn,iv:m/lSos7xIHJORd/wJHoeTdpPAaPJjrGVQtUSR9U+KJw=,tag:/5bW9g7q9aPIJAxRViZjEg==,type:str]
                1536M:
                    - ENC[AES256_GCM,data:pOZ0HA==,iv:YCcps1sI1PazAKB8KGRWNuJ+55hsI2EDQG04txcBKWQ=,tag:iSUkYAq1HRr8h0YvKfUoRg==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:ZtBv1WWEpLQPb60HbKatchE=,iv:HYURZeTkN8w8OESB3pl+qTL+k9oOBv0G5wldXs/926g=,tag:Bw1bzxLIWDQWa5z9O/7CvQ==,type:str]
                client_secret: ENC[AES256_GCM,data:SXd4uxJ2hcrJATQUB6h6LiH7wE4F12sGb+73x7FHrV63LDwXD/COPDVJ9Mgzo2abg4LYkGIsE/oLMZV7bW+2og==,iv:0iri1pRcEXkmdyDhRpGVR7a1o+IYsfFtjZVddEJrgu8=,tag:VWKdbGDin/AjcVYoPu6KEQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:aGlJwKNZSQ8nyoa6MJQkziAkmSEfKssfzMHNQMZmEWM3DR1a1N86jdt+Lmx4Qp7RG/C2p9X3p8/tsq0DE7O6,iv:Vv6EthBgJ0UddqwAKlmhECgBRKZs/4YI5lXrOFwBrjw=,tag:rRLkxBV/zLSZjfHZhawfDw==,type:str]
        extraContainers:
            - name: ENC[AES256_GCM,data:yLgYZO6dYlbpINQhERYYF4OiGw==,iv:92eayJR2b9vLqQbNkxWz7mdlHHRDbsrYA9JFXoA6gDg=,tag:RturrLl+ShgASXZ0NCOgvA==,type:str]
              image: ENC[AES256_GCM,data:p8SmbQcYL1BmyWB/zDfy/7EyRJzv3WbxnYaLR1PJF/mqM7o=,iv:1DBnCuBBCZ+EuT7tP/oS7QVxxVTNPToTEAmYAcxB6a0=,tag:5DH6coslbunvEmsZRvL/zw==,type:str]
              volumeMounts:
                - ENC[AES256_GCM,data:GQBStL2538Yvguif/DVt00hR2y9NaN4UndERgT2jrgJN63/lX8bGwYLjgedhcNqZ/wQ=,iv:TBuOoGQefPWkdiyaEMEfVeEEnyE2ci0khTGBOXAJrDI=,tag:J27Est0yC4WMAIKDJv1wjQ==,type:comment]
                #ENC[AES256_GCM,data:utlkblfTH5xf5w/fT9R1S/4vopXcvGPd4xjTodKQQFiDuQsSkRSQRf4Ir/nWnTXUNQ4=,iv:AiXGxycq4U1ZJIlXZxuwaZ+qQLRKzQbhilW1gHxi2bA=,tag:/GhHc6b2L2SutzJMQZwI9A==,type:comment]
                - name: ENC[AES256_GCM,data:/WeE,iv:CSHEhWmFSuIpha9ICp3YGz6g0mLPYuGAp2RAzG7XxwQ=,tag:P5gvTXu8hg6RH4COsCpmsQ==,type:str]
                  mountPath: ENC[AES256_GCM,data:TLPjDqf8JdolPMdQdUB9,iv:QB5u01x/oqzVWblx6jHTJpFbcTwF2SoR0+IPpoQpldI=,tag:eatI3+US592L3KgTgEzaHg==,type:str]
                - ENC[AES256_GCM,data:0Z+ugFAF7Kg4NrrUSXO3QdT4VTAox+nK,iv:fGw8KL8IXzHJrE3veWJ25YhXjbjZ1FBwFbIVFBVBgxs=,tag:r1bx0BMaOvkbRhd8W7Ussw==,type:comment]
                - ENC[AES256_GCM,data:N0JVI7edHUljtAzCGEMq1On7xs0oxkzK,iv:ogd68XYwl89GPiBxf87HsiYwqSLzGHimRUCOTmA7m4A=,tag:+4AkUFSOnlzzktSBDp0cbQ==,type:comment]
                - ENC[AES256_GCM,data:7uK7oS4LnVJ/oUsZrsDeVzjCMcTbTIB7,iv:Ky8rY6YK8+K7Bpewy28sa8drxw/5z3lctSs3Aop8cbE=,tag:eC4VofquVjJpYzjPpzGHvw==,type:comment]
                - ENC[AES256_GCM,data:yTyIl7gnR53uITwbLjS9JI/h5GQ6Tliu,iv:Os8n0sx5tKRrwwn802iiPiTKno6t4FWnK1OF0uGH65I=,tag:GFHE4rbANU8pmfiV6C2qhw==,type:comment]
                - ENC[AES256_GCM,data:evCj9MiUOQvHJq2vUyOiXB2uMhGIIQ6X,iv:+4/lQZmvryj8VdgLA7Etf6m3KuHrkGi8T7ftTTG9QTM=,tag:XTXUyTKhX3ArHA7LoUj6mQ==,type:comment]
                - ENC[AES256_GCM,data:5TNUboHnOWSsLWfX6w6xrV22O8QL9J4d,iv:SlVQSa9cqe1Se2j0/k/7RTroHX1x21//M+YPkaxkSk0=,tag:te+vKAauuANOlL9JH/KVYw==,type:comment]
                - ENC[AES256_GCM,data:JhxVp6wUAPqe5xzaQTfExirgqzKCIZzx,iv:jFYV22r+u3z+yHh6wDs9//BxGynySCPayLxYSqJdgjo=,tag:pVAAeZ4Po95dy5BqwfNmwA==,type:comment]
                - ENC[AES256_GCM,data:ryJY7bGBcJdmVft9CW+CMIL31Qdwcn+Q,iv:2p1ebh4zNyz8WNMtptomkLijTVKMfg1YQMN2472ld4Q=,tag:NkYvsxx1DCVT9tNhucf9NQ==,type:comment]
                - ENC[AES256_GCM,data:43cDwdWymqLCIg1dxjd1odKgj3RYxGaK,iv:p99S9uBWN9qP4CrEj/EwDw5lSiiSvL4+gX6SgIBLU88=,tag:gHnWd1zCXbvecDa2Qt3xAQ==,type:comment]
                #ENC[AES256_GCM,data:quIOniUUNdbvTQlU6MrogEK7RDFI4H2I,iv:d48jXR8Dhg7XSmfFQxWh4xsxQhl7DmgoX/jFYNzPzh4=,tag:QQiyt/4R3aG0U/Wy7e9Ygw==,type:comment]
                #ENC[AES256_GCM,data:iENZKphYE1NVBRiI0nUaP+BfhUrvfUOL,iv:n5xjJ28mc2vvYpypTqR2u8ojbmDopslPQn735FHqMao=,tag:Qhq4ZVS3gn3ONhe2khn82A==,type:comment]
                #ENC[AES256_GCM,data:4bwbcU/HPxF6oibayz0+J0GS1egQfOmj,iv:M2GMGxFTPcKLQF+5ROnBEghVQI9kd26vJOZL5tGL3c4=,tag:khonGsayFBknTjyEcyJfOQ==,type:comment]
                #ENC[AES256_GCM,data:+YWlRW09eBpK/JbFcoSDz6w0opbeiQ7+,iv:T6lka0tSZJTr5mhAJB63zqLNAxEenp8tQnyaCtsDds4=,tag:Of7Z2BQT0jLXUw+gCsDrRg==,type:comment]
                #ENC[AES256_GCM,data:T+OgSQpn1RDR8+9zvam+PVFQKvdQijux,iv:DRD7rj5z/FuXpsJ5clAzeDIo0ttMPHD9h4RagoCuWxU=,tag:qL8NA3SoPf3vuUeGfAJXaw==,type:comment]
                #ENC[AES256_GCM,data:5wlYfBORAfijEVO4DJUnZCJikz8tK214,iv:eQrFsRdQae8fFJzbqkBYq1cFwY9rsx7qTwjBCRoJQro=,tag:PHBEeuPzO/m5PwoxMU2Vaw==,type:comment]
                #ENC[AES256_GCM,data:EKSVgyZm9QjK1aQZdnWtSA1wvRb7P1e5,iv:UGU2Ai2E4uvGZUwAk3Tpm7s4EPpS89lKRm3FhazBZkI=,tag:dSA3lvv/WPBSa1kuFdi1OA==,type:comment]
                #ENC[AES256_GCM,data:NukpthaIDQbJy26qqtNezo4m6Yq8XUkN,iv:aCx2diE6O6YtAJCXZEKS15z0/FbEYjAWD/5YwLxfvr8=,tag:bGfNjxWKLjnHdcf/9y6RnA==,type:comment]
                #ENC[AES256_GCM,data:C4mWCTO+bhbnGdr15jQoHGVlZMm2kZIH,iv:MZ/LwvkBqePed6OJyjYxX58Akah4axlxIC9/T1wqADM=,tag:uYVYKPhSQl3RwV8Y3+CXtw==,type:comment]
                - name: ENC[AES256_GCM,data:OS561UTX,iv:o5JptsIckxeADu1QROHhoy4ZiF/t82Ku/v3r9YUjSqQ=,tag:CPgbN0F1bBaL+tn7TvNrMQ==,type:str]
                  mountPath: ENC[AES256_GCM,data:6o6dTnkcmj9fbVrVfCS5qCxFYeCd9A==,iv:+RunfHCAR4gkkFO4e+Pw6CmPsVec+d8TeNc0UOA2h/c=,tag:p2LJYx98SHZjD6nQ/QlPgw==,type:str]
              env:
                - name: ENC[AES256_GCM,data:erj+VNrJPnyj,iv:RINp0yi8rR1CFpqH7U9fZ9Sdp6/4uiQg9u1JCyMWCr4=,tag:Lu1uCTVjRFWdySFK/e08ig==,type:str]
                  value: ENC[AES256_GCM,data:Ol16gJBczH0=,iv:VBGugzsMrikE2QhjPzeiiKdrFEbVkirneTyJFHEatoU=,tag:N0vXpu+fdtFo3JHly/ezVQ==,type:str]
                - name: ENC[AES256_GCM,data:hMCfLZqceYJ2AQ==,iv:wfVcSOL4rAlZhips4LQgFvK4lNcaA7ixNyKjHV3m2UU=,tag:dfeoYyTFnF0BaqL7U70JsQ==,type:str]
                  value: ENC[AES256_GCM,data:2LjL+ESpXX6JVI2SZqE/84AOIRkulExCNoAXqnj5tus=,iv:BZaGSqDnFi4Ngjp4StS7JEii/twRnb9s3+pi6rK0adQ=,tag:D4xA3EmwuRPmG1hfQF+T6A==,type:str]
                - name: ENC[AES256_GCM,data:Ma0Cj+sVuskls74oYwY=,iv:aqY4zLYoetXZZlEgO+lniXeDgCynK6rZyyjxXeH/kvA=,tag:4vw8LCqDS3Mz4XDCm/vAxQ==,type:str]
                  value: ENC[AES256_GCM,data:WBYaj7b/hJY=,iv:MAiQz7enj5PkA8jq+vSSJCjCJlliY/hn9nUJyCLsWkw=,tag:xzGAZ+dYFCCLScFS1cvpcQ==,type:str]
                - name: ENC[AES256_GCM,data:loTlYT/Ge2dyOmcICXso,iv:loDjKOGgiCU5Lp+FNCDv9asusvAStu3XcGKw7woS1xs=,tag:wL0hooPDhlIgoMpj3XrEDA==,type:str]
                  value: ENC[AES256_GCM,data:yBpoVZRzVFlwc58xYeVnbxVUGRh8f2A1jWIsfhRQDeA=,iv:BfzyqVl9y7NvTcmGKM4PXTiN/ASVEboHpbSBcXx/Oq4=,tag:oJ5u0SBddp9uF2Ld1JQ+Jw==,type:str]
                - name: ENC[AES256_GCM,data:5jAd58bKnGj+QH3MiuzmO5EK,iv:glPkeHD6z17Kt7D0sdyQjs/5rIQ8ObccWAavCngYZ68=,tag:KBSCtaSHkdJlw8tw4zTqOA==,type:str]
                  value: ENC[AES256_GCM,data:/zOU95CtBCU=,iv:60zhwczRBGonF1ujqDnRwZTrPw+kgq3BInfRHdKAn5Y=,tag:dXXMbekq2isx+wwKfH8X0w==,type:str]
                - name: ENC[AES256_GCM,data:hD/p/fo2R1Ybfa6LKskIsXJvAg==,iv:+mcaE2zf4QUpF83EFtCB3imzI/mTWoIzZY7MHOnVrAo=,tag:lgNlVZBEHcvuI9oCDWKCxg==,type:str]
                  value: ENC[AES256_GCM,data:wp3ow/KNlOpmUvu0Ydn0VYEFjmQ1X+XBO5D/ANvJOE4=,iv:50VQleukNomzglaTlaNrI4ZudvfyrZwVGzM5iJOx4rs=,tag:WqOI1aYOW89AqwmNtQ/b4g==,type:str]
                - name: ENC[AES256_GCM,data:35f9MpiPNj0oAZsv,iv:yog9rJgr0Db+q11dP59M2RXXbB5y0AT4u7RKPa8zdrc=,tag:5JLUM7iYs27YgmrUqE+UmQ==,type:str]
                  value: ENC[AES256_GCM,data:VIgfgA8QAkc=,iv:Pz8YalW0n5Yesbg/GGlICleJyB0lolXUHVG6NOOUFjY=,tag:KuFWs352pSCKPR35V8V7ng==,type:str]
                - name: ENC[AES256_GCM,data:yw+qi1+c5f5SvQUcgw==,iv:ImZSZZ8tHIV976jtTQhSYI9ZTo+ltJgEWKVIZAsdRpA=,tag:btqUGMpLW6vWVrwJTpu89g==,type:str]
                  value: ENC[AES256_GCM,data:msEfiE4x3YptQh/Vbj4hTyutw6DEn8/gwBB7DnSp5WE=,iv:3icAhacywa6Jh6zF0PTrEX5Ec/MobhwSmuwj34sbnyw=,tag:93M/RP4z+T3lMVCCc2lNMg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:18Z"
          enc: CiQA67O9AEF+mGY9UwuotTComcC1zngTguQIbQgPcBuePuJuVJ0SSQDmhpq8HyToaA2ZmH/cJBVgx3rKGUQ/RnFkW9nobx41f6n+wtDO74gatUPnpV6csYj2HRMkND/mTmCxobdnZsyb3AMMXFZybig=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:22Z"
    mac: ENC[AES256_GCM,data:7ra3ZD5lzluDl4lTyF4nX1pIjFSp3MgUl5jWj/yvGYMTylHuetW2Z6ve7qW2xLn6sXfkYbigo8dKn4y8ODnL2fLM3RJAnouG1zSJXvMwE5fsNSr/BHiNCjt2NwdpvS4iRRX3if1Sa7vi8M/Ben316L7rvoRq/BfSDKmO8bC9XpQ=,iv:02VQzMGDInztSZR9Zt/sVHvc9FgnmJf7vIeau9M/oWM=,tag:MQHhxpDirfAdeHYPAuYreg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
