jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:2glsY+yYBGuiEAMjnB3lBZ2Mn90XgiYPoYDw340OncCx1122wuObcY6z0tDvkrqbhoOL8Mb1Uty7TJj4pXtjag==,iv:U2oBMfS5ErX9mPj0OAFmQgvlUnWoiquP7CwWbSwuvQE=,tag:yJtjvmjZ0HS/ZETRUMc1ow==,type:str]
        extraConfigMap:
            memory:
                4096M:
                    - ENC[AES256_GCM,data:pZn0NwyhQ4Ps,iv:Rg6dqt2jBY1sHd/ITFTwQ0NxIDVMGfJwC9V7bru70rg=,tag:+7jlWx8umt090lZnVPQdgQ==,type:str]
                1536M:
                    - ENC[AES256_GCM,data:HlQi7g==,iv:ySyKEh6LHDZGcrm4AxbF4ru/wpWmWaiDoIguLy8T1ic=,tag:9Acp5/U9CZVjrmHCYOz+ng==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:yonRF/xi6Glv36Lrb4SIHTQ=,iv:etUYlNbieMpHAo/wIMMaZuQHg2fc6GMvh/frnKHujSM=,tag:WWFx6/gO4htb8pCGzats9A==,type:str]
                client_secret: ENC[AES256_GCM,data:dZnlsDSNLEcrGWJcolaPnRh62zK00XVzS9cs4r61eWX7jQV9xUnTQZdf+RpkiCgRTP6vhJgc0Rp5Ip7Ighq42g==,iv:LeUUEIwASziposviBjSojte7cq8DXIG/oV6VKMjL/O0=,tag:mSYjtOftHtrBxfhCa07uPw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:/hfQ177CiG93Z9wpWsNSKWbsiuiQY9AVUNq0rpcQoaFjvBkGJ7nL+tvmfYW+DvMY7h+Fig/vYsTYRs4itofE,iv:/B4C2f67mDVeG1UIIjJR+nP28V6x3VeZE46u0Awjdpg=,tag:sc3jrAEPF3YsqiGwYQErrQ==,type:str]
        extraContainers:
            - name: ENC[AES256_GCM,data:PDeQHRRR+/LVYB1hnwI1EmVcpw==,iv:ICH6qvvLvNVzEhwVwkx/w5er/OLJLTckGhwgMrGuVBQ=,tag:s56QLsOvi4i3GI/C3YaJ6Q==,type:str]
              image: ENC[AES256_GCM,data:ADbnOOG2x2KCIF7ARoEk04/3jEbM9N2ZX1Utxpxc46e75VY=,iv:LIQZDRRWFgmlpnxa/OFUEj1d7/Tb2xgcLVi1xe+99Nw=,tag:dYw3yJdnxiGYh74DC5b7iQ==,type:str]
              volumeMounts:
                - ENC[AES256_GCM,data:Fqa1nU3no15v9/5krwLTEBUx2OOQpW4GmXWRMPS5k46vLDUb5ahDbYxVpv8X7LcbCBs=,iv:aAHVSHDtj8YG2/8PY5vdt02juJVeci/qPpgj0LW8Suc=,tag:eeBvO5bWTFfomh+dhzNUgg==,type:comment]
                #ENC[AES256_GCM,data:KNs+H2TS0gpKkC/+UMySK4O0hrVbe3NN00FXeTyfDPcXdYh/Z0lHvjhwWil842CdUMg=,iv:dZviyNW5g+SWza+YXjISV2A1ZzSYADfxmSwEdRJCrn4=,tag:Hc6PP2YMfidOXHQM+zL6HQ==,type:comment]
                - name: ENC[AES256_GCM,data:BlV6,iv:t31ctOEs5uw3XzrcSX1dYS64AK5I7w5VeJSpg2A9xV0=,tag:OnVUtlDxXVZP0uX2QB46fQ==,type:str]
                  mountPath: ENC[AES256_GCM,data:Uw81Vrb4nF+gPcrZoKUj,iv:SahfkZmbl9cJO9MeK884Szi/x6lKz25gC6Yl/hIM+10=,tag:HCrRbmDIx1lEigZzcXXO7g==,type:str]
                - ENC[AES256_GCM,data:G7nYY6Yfl0uAqqUfzuPBcTFWr9mR/duY,iv:efsnf4u9YD8GAhuLa10IAi90S416b3rbiQs2QSHPIng=,tag:6ICOOvCeh9IbfNVoyORWBA==,type:comment]
                - ENC[AES256_GCM,data:c2MsWia+sfzUMNF7IOGb6hQfXvJTDUSZ,iv:QIjuffPo5DJP5cJ0q8fvHQOisWmTz6/lGv+QM4rzXr4=,tag:dZwqgv+pRrzKlZwqUe/KzA==,type:comment]
                - ENC[AES256_GCM,data:NcmmNyu0VNV+swUgxMqDc+fFkXxRqzP7,iv:oP3tXRGNIN0iXgfCcu6lLBBDCFekigd4FdvSoRFHJ48=,tag:kPmyS9x+0Wr5ucgkEdEdKA==,type:comment]
                #ENC[AES256_GCM,data:8B1m76tpnNQN8t6r5ueC6NRquSB39xri,iv:D8ljnCxZuGoSxTYyrT/LPAy1BJXIZFSCCBNY8/QCJI0=,tag:lPsjcMQ7vgbzoc5dqhJmUw==,type:comment]
                #ENC[AES256_GCM,data:lz08HztByAHL+DMuzlMUw6StZ6JtArLH,iv:0DM3pHy9C0lYFwlsKoB1SHGD5ixyHWeci17JLpr6Y14=,tag:MBvGbt352cOE/a9SNN1Rgg==,type:comment]
                #ENC[AES256_GCM,data:XicM4ukdX6Cr41HVBgtoBkbQ2f/TIhkT,iv:LlE9klGkW2FznBDk+c/XZvjl0U71r0DAKuM4GCG5ZoU=,tag:4dLJAunkvtNdpgSDLhPCBg==,type:comment]
                - name: ENC[AES256_GCM,data:OKvN+9m8,iv:K7rxT2tg6pdEt6nKOexIkc2bJBb83wG5wDmk5B9ldOc=,tag:2KlrY90Icfi6xHf1lAdowQ==,type:str]
                  mountPath: ENC[AES256_GCM,data:cmrCcd603ArPYWMkzplxb0DD+vjDgg==,iv:h4k8sNiaRVVG3mNvCDLnr4LyPMCF6otBQaKjrZuUwJE=,tag:55gFD4mJVI7kB02x/aGJZQ==,type:str]
              env:
                - name: ENC[AES256_GCM,data:SZI4O/rW+ptX,iv:NSbXblP4wv8n6zqWWa3Lg++O9JFOYe9VXmbxp1X0NjQ=,tag:FpCBB3+2QDqOvqRMceYLSA==,type:str]
                  value: ENC[AES256_GCM,data:OlquHA2VEP4=,iv:c/kMlKbGwhbt+UaoNVosQT51vuZjPOMbQUSoB3601vs=,tag:grt/8zt0ZoA4cLtEUES+4A==,type:str]
                - name: ENC[AES256_GCM,data:0PaJVS7xtLcIuA==,iv:4OXTXRjYhFCktwmVmyiBg3wI7Y+hqBiu7oH4gBJuPFU=,tag:p227518u7SasrOMz9FpiKQ==,type:str]
                  value: ENC[AES256_GCM,data:tJuh5rvYSr01Xa7PJXrJjvgS26eHjMc6fYCTUqrA1WM=,iv:H0w0KtL56urq9sWgXLO7d+XvausC/mFYg017pIez9Yw=,tag:A4ibxbPyyRU8V44YupVMqg==,type:str]
                - name: ENC[AES256_GCM,data:LJqLqpgeG8XNjj505uQ=,iv:Zr6UPIp+oFcnoiKqLdPFODW2YvZ/UhHA5e5+08gIVBU=,tag:1+80Go6a3AzGM53k1U5wlQ==,type:str]
                  value: ENC[AES256_GCM,data:Q14n+JRnMuI=,iv:uk1Pe7m9nhPAmwrqB+fsyqCQNr5gURR0tbkJHvH/xfU=,tag:lPILHFBvyqldaeXJUkR7sQ==,type:str]
                - name: ENC[AES256_GCM,data:EkCJB9VFZjSMtKsIktkk,iv:+cS6/FgVCXEZu+q8wShYjKdirTPnxy83zqMR3gd2Pvg=,tag:yq1DRxzZnCJnGmZ+ZdCTwg==,type:str]
                  value: ENC[AES256_GCM,data:3xXFJL6gYM7yvdFD6mkh6ryxu1gWpbiC34oMe3sQSts=,iv:ms6cOJzGU4Mj+s23MFzesWs3NRbRaCyx2ZvnKc8GJOM=,tag:0r1g/LpwCUmKQmwtfVE5aA==,type:str]
                - name: ENC[AES256_GCM,data:XPabcMU5Lhn9iVCg1hwpmHoW,iv:ro0uRBBq87iTl1nEs79VL+OcPKHluDbzQ+FMWInqhkg=,tag:kkL0HczsKbRyWSnj7fBQPQ==,type:str]
                  value: ENC[AES256_GCM,data:xF3qxMMxuyA=,iv:hvsSh7S2AgfXfK7f/zxkCdiyh0YlNK9QbYOW7AWrpp8=,tag:awsCoABGLMf5KRxhEuShyw==,type:str]
                - name: ENC[AES256_GCM,data:0S1JXPVAEF1dcARmPZ7lS5OCrg==,iv:mT0yKwdKMRpmiwcm1H9DrXgzSYdDSPiZpbAldiYmGrA=,tag:OYX4yNz/heGo4DT9GZrUVw==,type:str]
                  value: ENC[AES256_GCM,data:BhoVxIh8yo1tknpUhebyAcRfEzrvx+eVeeyTSgffOTI=,iv:49TxZ4m6ACJFNU5HNE4hF2tmSLZXyHaPxoGpBbYmw6Y=,tag:Q5kK8ezbxZ0FQmOVDaHEaQ==,type:str]
                - name: ENC[AES256_GCM,data:cRWx9hFFjHUKA+6Q,iv:NLO2xLuwUSR1Ri4IougooXFjau3th8AXILm7Vz9Stt8=,tag:+LbxFiYywAJKcQ4poLooDw==,type:str]
                  value: ENC[AES256_GCM,data:3rMMVubbvUo=,iv:9d4RiXmAGG0ksk/MU+XvBLhu6QTE20X3A8Yy6kgVZi0=,tag:o1CqVvOJQJPeSjwAtVL4lQ==,type:str]
                - name: ENC[AES256_GCM,data:WW2zXaTvuS7mq3HM4g==,iv:c+rRX9s3RNmRDUlL+mv71QYQxNxn25EnY9rnfuRAUjA=,tag:pnOViDGWfXnu44jmipA0Wg==,type:str]
                  value: ENC[AES256_GCM,data:CWkFix0vQmxTmO8/EuwvrxmbPTLXRasKGOACWzP4Ke8=,iv:7KMzOCAOA0M2ou0khkLo/lAj/4D7IEdz5R9xhMWXbP8=,tag:phdBXyt0UUYnFbPjEa2fOA==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:tOUXcGAZNFRlabcBQ5VWjesdL4TWm1UNETXNDUO9Ij4N6RGsQRAWHHn+UOJcIVZLBqoPthOHW0n/5Lr4mY8DUg==,iv:6mtLgdSg0WYoFjuNGQQjKAotGhD4GmV7ULxWyixmt1I=,tag:4GftY1LqCEndxdCSr89kYw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:04Z"
          enc: CiQA67O9AHnPokrSsT51wbDHEg7TBrRKi0aSv75jz/ZNgskYuj0SSQDmhpq8M7FdCe0hAJMh9Xsul1+6BnaZJjFqflwLrvie/fAao94lIm0cu9VrBJmbPY1iGOqGF0Jt4C2HO6cuJR1ro35fPEnIcms=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:07Z"
    mac: ENC[AES256_GCM,data:oCeu4nD4RJLrmzvpaLbIrYCSTIXDF1nWiR8DlQyE1hb6EpqcEoVopxdjxveAczhRxuJsy0lOT1Y6Vn2tj9BhVLj0NRt6NhBRyirs3/T9U5V7vfeZiqsGv7w3u3yPgdfZJKCjAP24agYTbb5ZKtrl6T2ckIZhYfteDt1P2XaIHw0=,iv:waI705x2ykiTvlC2rzoKzGBVBER6ejY/QxRgkVA97P4=,tag:bueRMjRoGLAplEUg7osddA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
