jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:lcqU9U33f0hzQkRtH1G6oMs=,iv:yQdwYDU8aEEKQmrdBNVPb10GA6hOeDQyp/aRYw6cD3U=,tag:tHR5BCsIIgA/eSJ+FxnTZw==,type:str]
                client_secret: ENC[AES256_GCM,data:HPAfbjiMq9tpAre6x5gZE+joXJdKySohDtunORiLRn267BtRPYmymT59YsBhnHp3wrqil0BQv/l/+j/ou7dm9g==,iv:p/rEpdtw//DQiuJ/66NDwgoLHW5mIvnv9BeaovdAVaE=,tag:9BpL8ly9veaxLZRYP5omgQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:jrwgy+xmyUrBkYy+1cA7Wsmtio1xJ7xBXRffW0vLHlZb31wZmJoYlTp6njij7Ih13eQDItLggorqSV167cZo,iv:qz0tvBs7Wpx6bVZcgfGX5gW7aOYZ0QhZYmhoDqYv1bk=,tag:pGKs2wOvKvmZNguii1GzHw==,type:str]
    custom:
        memory:
            4096M:
                - ENC[AES256_GCM,data:aB8Dv+nuhl3C,iv:2OKEOCEeva1P/L2CGJqsySPpDKzaCZHiP4yeffr7jgc=,tag:lm+3PV4lq/B3GOoB+OKBlg==,type:str]
            1536M:
                - ENC[AES256_GCM,data:TCoacw==,iv:E++/mgFk+Z3kONtcU06iTBOeQZBM0o0uUzp7oTeGhak=,tag:1yhN0uQQ1nBH9agA6PAfPQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:59Z"
          enc: CiQA67O9AIxTFmAaS7Bn4Z7Ajn2VoJZAViDi/WlDGi70sDj5R0wSSQDmhpq8XeOOpmygjHorUvvXdUfujdzf6cSD1IPuz3JUc900UGL5QtXFfLMsfOb2fJrV/h9xhm8Kd1Ub3WF/rSpdG2HuS7kn6PA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-28T05:46:11Z"
    mac: ENC[AES256_GCM,data:gOu+f9oeOUs7dytwDySbJbQBbEgoMFSp8S+ilFEIVh/Ym66NQ5a0T+2njr0qZgkD7MNy+k8eV2+lEwZTuOFI3HwKgI4ra4vZS2CJU1n/uka15h63qKa5tuV4KIAPIzz1auGvDQbGIISynmHzhdTywB4WhpBiMFIe9pPwIOhEZHI=,iv:9Xphv81SKNXj/PLNYhdh9Wr8W3EFMeOtev5InWDEXxA=,tag:FC46Hzwom/dlmy6sfDx6BQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
