jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  hub:
    config:
      CanvasOAuthenticator:
        client_id: '10720000000000471'
        oauth_callback_url: 'https://cs194-staging.datahub.berkeley.edu/hub/oauth_callback'
  ingress:
    enabled: true
    hosts:
      - cs194-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - cs194-staging.datahub.berkeley.edu
