nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/homedirs-other-2020-07-29/stat159

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool

    config:
      Authenticator:
        admin_users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          - balajialwar
          # List of other admin users
          - fernando.perez
          - pbstark
          # GSI for Spring 2021
          - daniel_mcandrew

  singleuser:
    extraEnv:
      # Set default editor to something more new-user-friendly than vim/emacs
      EDITOR: "micro"
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/stat159-user-image
    defaultUrl: "/lab"

etcJupyter:
  jupyter_notebook_config.json:
    # Show dot files. Requested by instructors for pedagogical reasons.
    ContentsManager:
      allow_hidden: true
