jupyterhub-ssh:
  hubUrl: https://stat159-staging.datahub.berkeley.edu

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 34.122.233.231
    https:
      hosts:
        - stat159-staging.datahub.berkeley.edu
