nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/data100homes-2020-08-04/homes/prod/home

jupyterhub:
  hub:
    extraConfigMap:
      # this should be migrated to custom.profiles when that works
      profiles:
        # below config automatically promotes instructors/gsis to admin and demotes students
        # year-term-ccn can be found by searching for c100 in classes.berkeley.edu
        # see issue #1584 for implementation detail
        # stat c100
        # 2019-fall-24961: {}
      admin:
        mem_limit: 4096M
        mem_guarantee: 20484M
        extraVolumeMounts:
          - name: home
            mountPath: /srv/homes
          - name: home
            mountPath: /home/jovyan/shared-readwrite
            subPath: _shared
  auth:
    type: custom # This enables canvas auth
    admin:
      users:
        # infrastructure
        - felder
        - rylo
        - yuvipanda
        - cpyles
        # instructors
        - fernando.perez
        - adj
        - data100.instructors
        # gsis
        - davidyi624
        - dorx
        - ishaan.srivastava
        - kagarwal2
        - rkunani
        - snhing
        - samirnaqvi
        - suraj.rampure
        - susanhao
        - cshih
        - agnibhoroy
        - am123
        - alberttang
        - anamtudor
        - andysheu
        - brandonyli
        - waikeikong
        - ischmidt20
        - calzoom
        - jaykakkar
        - jwu19
        - julieyu
        - oliviaqin
        - parthbaokar
        - pranav.njn
        - rami.mostafa
        - shaviv
        - rain
        - violetyao
        # tutors
        - aahuang
        - guanangela
        - erika.n.mack
        - henrymaier
        - johntsor
        - kevinmoy
        - kevinyang8
        - kiranrajgobal
        - yangluanne
        - marian5566
        - pranshu
        - rikiiyer
        - rohan.hajela
        - raujla
        - sunnyshen
        - tom.kim
        - wallace.lim
        - y_liang
        - zacharywu

  prePuller:
    extraImages:
      postgres:
        name: postgres
        tag: 12.2
        policy: IfNotPresent
  singleuser:
    extraContainers:
      - name: postgres
        image: gcr.io/ucb-datahub-2018/jupyterhub-postgres:0.0.1-n2510.hd28e63b
        resources:
          limits:
            # Best effort only. No more than 1 CPU
            memory: 512Mi
            cpu: 1.0
          requests:
            # If we don't set requests, k8s sets requests == limits!
            memory: 64Mi
            cpu: 0.01
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        - name: POSTGRES_USER
          value: "jovyan"
        volumeMounts:
        - name: home
          mountPath: /home/jovyan
          subPath: "{username}"
        - name: home
          mountPath: /home/jovyan/shared
          subPath: _shared
          readOnly: true
    nodeSelector:
      hub.jupyter.org/pool-name: beta-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan/shared
          subPath: _shared
          readOnly: true
    memory:
      guarantee: 512M
      limit: 2G
    image:
      name: gcr.io/ucb-datahub-2018/data100-user-image
