jupyterhub:
  ingress:
    enabled: true
    hosts:
      - data100.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - data100.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 40Gi

  scheduling:
    userPlaceholder:
      enabled: false
