jupyterhub-ssh:
  hubUrl: https://data100-staging.datahub.berkeley.edu

jupyterhub:
  prePuller:
    continuous:
      enabled: false
  proxy:
    https:
      hosts:
        - data100-staging.datahub.berkeley.edu
