jupyterhub-ssh:
  hubUrl: https://data100-staging.datahub.berkeley.edu

jupyterhub:
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - data100-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - data100-staging.datahub.berkeley.edu
