jupyterhub-ssh:
  hubUrl: https://workshop.datahub.berkeley.edu

jupyterhub:
  scheduling:
    userPlaceholder:
      enabled: false

  ingress:
    enabled: true
    hosts:
      - workshop-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - workshop-staging.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
