jupyterhub-ssh:
  hubUrl: https://workshop-staging.datahub.berkeley.edu

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  ingress:
    enabled: true
    hosts:
      - workshop-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - workshop-staging.datahub.berkeley.edu
