jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users

  singleuser:
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/{{cookiecutter.project_name}}/{{cookiecutter.hub_name}}-user-image
    initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: home
          mountPath: /home/jovyan
          subPath: "_{{cookiecutter.hub_name}}/{username}"
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "__{{cookiecutter.hub_name}}/{username}"
