jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - {{cookiecutter.hub_name}}.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - {{cookiecutter.hub_name}}.datahub.berkeley.edu
  hub:
    config:
      CanvasOAuthenticator:
        client_id: '10720000000000472'
        oauth_callback_url: 'https://{{ cookiecutter.hub_name }}.berkeley.edu/hub/oauth_callback'