nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver1
    shareName: export/homedirs-other-2020-07-29/genomics

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool

  auth:
    type: custom # to enable canvas
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users
          - psudmant

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: gamma-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "_IB134L/{username}"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/IB134L/IB134L-user-image
