nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    config:
      JupyterHub:
        authenticator_class: generic-oauth
      GenericOAuthenticator:
        login_service: bCourses
        username_key: name
      Authenticator:
        admin_users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          - balajialwar
          # List of other admin users

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G

  # read by z2jh.get_config() in hub/values.yaml
  # formerly jupyterhub.hub.extraConfigMap
  custom:
    profiles:
      # Shared dataset volumes for astr 250
      # See https://github.com/berkeley-dsep-infra/datahub/issues/827
      # AY250 Spring 2022
      2022-spring-32366:
        mem_limit: 4096M
        mem_guarantee: 1024M
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/shared/course/astr-250
            subPath: _shared/course/astr-250
            readOnly: true
      # Read-write access to the astro shared directory
      # HACK: Different mountPath to prevent mounting two volumeMounts
      # at the same path.
      astr-128-admins:
        users:
          - yuvipanda
          - ellianna
          - joshbloom
          - felder
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/shared-rw/course/astr-250
            subPath: _shared/course/astr-250
