jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_id: ENC[AES256_GCM,data:mJDlS5KRSKYPTbGhJvDDHkP3M45DFKgwk4BTMOTn+ntHAIUZvV+8Q65tPVeB1sA4YseZ0dmjNVluSZXi5ykbDQ==,iv:fZmKX/0Wvo7015s3mQElUGg+ZJSDkRr3SqDFVyLj8WM=,tag:1miMhF43ls/yL1DnTnNCjg==,type:str]
                client_secret: ENC[AES256_GCM,data:j+NG8usu5KShVDIc8hLaXb3CV4CfCSkqiLBcDdMVAvVjzutpv0qILFY3wztAc7AaY5thulL3fE7/EFPV615rkQ==,iv:NYWuea5R2FF3nuP8zVy8CHSLnXNwdVngjx4/iys/J0k=,tag:9wkuLvyT8Qxj6bFIavihNw==,type:str]
                extra_params:
                    client_id: ENC[AES256_GCM,data:hWz0QEF7TT0u1FcEiQ16RN3llM6J1mXQBewpYj4DV0Ya6uuvUomnnef4FZtuzS9PXo0IWRCfYjB/ZAFQkjgWWg==,iv:pM9Zg4UkMjI8xgNiwL5Cd4bVgJo4CiZiRFmSRiaIcOQ=,tag:kN8tCcuAa/TTqapchHPbLg==,type:str]
                    client_secret: ENC[AES256_GCM,data:GtsyjL4MeD90JPwcCt5MTWnwyPzRKohLsEWAa0pOACh7KDj3J4qkNAExhx/fgrX9t6WaDc2zVHouqiF034bg+Q==,iv:cnoApCiv8TFANIRqTXfAxQB3i7AlGsVWTbBLWUSLsjU=,tag:a9lRqh7e/F5lpZRyaH027A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-01T16:03:06Z"
    mac: ENC[AES256_GCM,data:Qz59WYyJbrQC7XR+6roYCzuSLPZrVjMGfSbOoRNi/npMm9tT74XoJmQrlfuNEpv6ywzWpK4dc++pPXs5uxY1cNoOUdR4Ph8mYT9NkjzOB6hJk24fGTAvvQXGs+YxcRI1a7CWjOaw7kFjz+qNJkbFbjmv9iPOkt4uMHSNRgGTSq8=,iv:BFLNCYrUipRHJXxjCv2OhtgcdD3qHDlipM9h9qMOTjM=,tag:c3FIKlfjdINtshOZCL4Rzg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
