jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_id: ENC[AES256_GCM,data:pbs8ciLvagC+TsyejxmTisy9oxO7aMy8nMM97cy2CafbSGhfFvyZ7Dm65ip0xYqlqV3IbiThPyFGDGi3ZO2Ovw==,iv:L+VCBaG9IC+OTJfkIUBLLHRHTzLBt82EgiUCzXVF4Dg=,tag:xWyMAUzzuSuVMgmU2rHeNw==,type:str]
                client_secret: ENC[AES256_GCM,data:VSPUHzK01bSEEua/tZMyMvWD24sgF6F7BbytcOvjfhu4wq4O1Mne/qfv5wH5gElbRAkJJMQJbYNZY3zV3+oXug==,iv:Yb4tCBAoXagvBEAPqopqNMSThqkWgiBJ+6YIlW54JB0=,tag:aP1gzcvSbJVHIwDhu/3X+g==,type:str]
                extra_params:
                    client_id: ENC[AES256_GCM,data:V2MfrBu/JYnltAuFAtqkVqcL4UAMHNGs8jrYHVdCSAm6O5jkSVFKRKXgNA2zHyijESKsXo/yqCiK0/zP6Ii3qQ==,iv:l3uLUgg/bWmLsQFhyi936900jNgpHdPjo3lgiOUrZK0=,tag:tJTdms4jGwGjAdQPBDtwUA==,type:str]
                    client_secret: ENC[AES256_GCM,data:cvoUFN+MVKq3j/4hRMxbvW2evvBQFshMrY1aVfHJY/6WvpvKeCdXT+DycMv/ifoBg9Oz6fKCak38bRyIBS+K4Q==,iv:qTF1t51JVtJNcO+KFdUOAQDgG3KANLvTFlJHPOTOu2o=,tag:t9dziazyYvUArredzzavYA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-01T12:16:04Z"
    mac: ENC[AES256_GCM,data:w1bMP+yyiMtvONPvUWKgUnXofAB03Wzr/j8TunwkJMruHCTZvRsW5OXdQiPfYhBNAZB5qhAcisjdanXNrc6m0OCPNK/98cr5coMz8QfGOj+4hKnUn703wNtUuhtS5tz95iK2NW3Ezd8Z5XPDou6ZFkmtOhkIcxXx74aw9uwMyD4=,iv:qATyYeua7h0a7W+NSCV4jgVwKRUZyHNOkC35f5nqxdg=,tag:GQhB/ne/MHksk2ZhJfchbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
