name: CPU Request
description: Raise more CPU for students in your class
labels: "support"
assignees: 
- felder
- yuvipanda
body:
  - type: markdown
    attributes:
      value: |
        Please provide details for your CPU request! 
  - type: textarea
    attributes:
      label: Reason for the request
      description: Detail the issue faced which resulted in this request to increase CPU resources! Your request may have financial implications at our end!
    validations:
      required: true
  - type: input
    attributes:
      label: Duration for this request
      description: Share the date(s)(MM/DD)/time (if applicable) for this request. 
      value: |
    validations:
      required: true
  - type: input
    attributes:
      label: Student Count
      description: Total number of students affected by this issue
      value: |
    validations:
      required: true
  - type: input
    attributes:
      label: Deadline for this request
      description: When do you want this request to get resolved?
      value: |
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional inputs
      description: Any other additional information we need to know about?
      value: |
    validations:
      required: true