jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:broJTkoAr+KWs8AQkjvYiBDgosfDjaJxe1JYIpEmaTA4OW/3AG1AWrF6iVVG0puGE3OUgGqPdDYaCuZG3w5fZg==,iv:pdqPFghlHDFnI7+UOsdAeFyDaUdC4Iv227kx3Xk/tp4=,tag:3XiMF01rmoOSKOzEiaV3aA==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:h+FBbxz2Vti7Pmn2XTBmvDY4/dfaF1XAzEOMzIr6WEjIBVXr30TOrJCkAu5DWVytGXdwgB5ADU/VuM9M1dMBSg==,iv:91UeA/j6809OI/mOzFk794Pz0d9TLPt2kaDAwM9cNUk=,tag:P0+9Uhb64HpOdol+k4R8AQ==,type:str]
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:anu57AzxABgN1KToaIHb+K/wUfBTwcrStEFNpvFjLav94TZX11C8ZiJENuBL3ooqN1/zIhafvowcGNAh/vyKRQouw5BpQL7a,iv:IINkTy6iCgrYAst5MMV9XKRpghATD/92jEs+8NjPCzw=,tag:VPMF3NeDfgfYlDJoFYFrZw==,type:str]
                client_secret: ENC[AES256_GCM,data:AxayswKCjiQiTQ1Prvo5fw1J7zedcf4a,iv:s8g6Vjc/JehrLMaH7a9Z3WoPQamJopfsu/wOq7ghD9M=,tag:My/71JOhUrDOTgmsu8SOmg==,type:str]
                callback_url: ENC[AES256_GCM,data:QewsvIaxlbXR2+ZGVbm8x8WzVxBb+AymPijtSivkWWcTz7eda+x/EsyGi13R6XkY7bBRjKVwV5s5VQ==,iv:XTx0UNUr8/wf97iQz8EAvsgoqYK8IOC/8pC87dPjzkk=,tag:2nOeFMMKBwTCvR7JiJZGAQ==,type:str]
                login_service: ENC[AES256_GCM,data:0yzHleevn688,iv:sQTHWSG+L7VGCI7lbCZYbUTtBy6IaDfNjLiP4P4N/bg=,tag:H5K+3tw0uR5pTI7MzeIzcQ==,type:str]
            Authenticator:
                admin_users:
                    - ENC[AES256_GCM,data:GzZCW/kONaPi9/dnzMw8,iv:fwM5vRD3YwVGVpFXXpkw9EUREZDvtTfOOHOa4zV5OsI=,tag:ahtp73kaPUa8bdHrgqMKEQ==,type:comment]
                    - ENC[AES256_GCM,data:7fgd1cAWZLphKLocuEUO+xk=,iv:3AiFnhTV7piiTfRoBgnqxH+2Nyxb4zJbxpOUEdXl/o0=,tag:TUe8AMNMXBUvB6MUCODBqw==,type:str]
                    - ENC[AES256_GCM,data:A0vbNtpsPYc41fh+nc0QaVIgalUpbg==,iv:ktfM/4SwKE2rlspacl2A72wRjyegMW/Vjd2JUBpSnIk=,tag:7HlP7+n1FOZEbt0k6WvnEw==,type:str]
                    - ENC[AES256_GCM,data:QVU1GTQgodmio9yxu3uZhUmOLA==,iv:ESZk1d+CwMpESIOIMob465DXPXC/Mpf2OceomdZlHMg=,tag:RGnBb2U4+u6NiOlZz/12Ww==,type:str]
                    - ENC[AES256_GCM,data:31Q3NHi2Nvl2sc+RPk2bFhHBfA==,iv:6BxKmB9okHFHrfw0y2IUEBd8PNF5NSJSQwmS5pmf5hk=,tag:grqxi55mf27xbO5gvZcbZg==,type:str]
                    - ENC[AES256_GCM,data:l3hlv7HVYCxvYqUiVgAH2/idJv+7pA==,iv:NlmoxXy2upxAGLZSgEi8SNB0X6u+kD4PffVLPMM5Rhg=,tag:8oOrjphc0uoMlXg1HldBzg==,type:str]
                    - ENC[AES256_GCM,data:GT62Ys0YTpahkT0syfh1Ovcf4CFloLThVlM=,iv:51atAlIAqJd5sDIbVJBxmQDV28OCkzFYJggorL5Tb8k=,tag:6RBRErI8gP9zqog4Uw9d5A==,type:comment]
                    - ENC[AES256_GCM,data:19RlvSFoC8kDBob/hkCV82i4YD6pgGwxnui7,iv:/xqUTSDoDy7HE4fzlzR62YlCR2tXKVFAy5OFrtmmmzg=,tag:Y/fDeF8eLXZcBCZ2cZ3bjA==,type:str]
                    - ENC[AES256_GCM,data:32KDZM7RDBRoEVPxke13PYnC4iWHlog=,iv:PLXVBgU5kK9lZeBIF8Z3tq3Vp/C7Yjg1miOp4Q1Lxrc=,tag:Wv9rhpogm5w4PEMJPEACxg==,type:str]
                    - ENC[AES256_GCM,data:NIr39G4jyOjUN/FWVDBl1hHOMNWn,iv:6OYdxtJDzGN/k5Bz72YvqryNQw9+mEGmtBCKDGvzTII=,tag:zR/N2f7UNhRfMTwIcmNyxA==,type:str]
                    - ENC[AES256_GCM,data:Ugu9amyIQ5eca5HlFcTBdQQ4sQ==,iv:IgOryzuuamcaigOghOIQhYmMySYMtcbeWChmpaI1K0w=,tag:oLURTtsWzr9DRwLBj/noRA==,type:str]
                    - ENC[AES256_GCM,data:CB3PX1hbAH+rXrYTdpVVIn3dQeJU,iv:wIb2uQJ5I1Z4KPLEoolzC0iDByKR8P4OJ3/AAryzlmQ=,tag:f6SKdfG5hzS89UuZzDiRlA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:06Z"
          enc: CiQA67O9AEW30aFhnXwd1R7ppg/nkCDlsqV+Tr5cTyvNRB5wVtISSQDmhpq89y5w/P9jt7WfCQ9jXY147K3U5zA845MTiRZRPceuqCPsXFJsOcCFrc+4bftSUmfzQnDwP3b4wo16FdpDL//UoLk7Lao=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:07Z"
    mac: ENC[AES256_GCM,data:DvyGSP4GBEt9OD+NmnI1WIC+XPfCfAN111QfTG1t+esQCukXWTUTEmahZAkCuk3LWmLpVfibj5ULHaVmt+ramNUEAgIREe9P9oqsy94jZ7Sr6N3UrNGzC/7Osn5yN8T6bZ7g5vabit2HMrE5p/xcCyhZqg0R3Xmbdrna81RquGc=,iv:QhPHN5iCPiSidjfHIHoVA06i7oWdybC73+qoe8ioHyw=,tag:XkcbdnTy2Q31L6aKI6a9Hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
