jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:kmDkFZQXsa3IKhsoP7PlO3uy8QCxEFP7mF78ztCNeo5tRb94foPmiRsLiowCRWkVpJHJxF7m3A9qHK3+SM47XQ==,iv:7MVQnFi/ablhKqpUYDO5WBPu9zS88AseAVM5DlOiVi4=,tag:nOxxmYaU4DUO6r3d4Qz1ug==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:S60zvU4LMem1U5KFmDf+purkOUQeBape798VWk4yLu1HeQO7If53qkhxlCtGrtmLXK9Rcx8NjqbOKX+NPbeCyA==,iv:IzlM19emt0RDZJ4ywsyLxfACP1rJLloe4On3hVzaL4o=,tag:aUx/6eJhq4Zdu4/HFECVmQ==,type:str]
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:UY7gZVNOvDxKR3yUiwKCnZQsks68/LoDSxAHHHfjrDJOpd2aPnLc8qRQEyveOfVOmqD1Os25HvKj7K16YTNagHdpcFcZbpZZ,iv:3lnJVkxw+uW/KFYJ6glfQpp4jeQFOCc7TdasGrBqx9M=,tag:/VKOG52f2XiqlU0dIp+64Q==,type:str]
                client_secret: ENC[AES256_GCM,data:UD3aakLPWgVW6CymZ4SNZqcJPFBMdfvK,iv:vD+f7A8ppXXYi4EhfVr1M6MK7V1g5m6GWRqB+r4Mp8M=,tag:LDciMvNJX6onyxV62H6w3g==,type:str]
                callback_url: ENC[AES256_GCM,data:dSgeV2sKCMNAA+zSVJt6jfQhHRuluf869Y9ciB6dCgY+fvtbmSeq1XcFNc33jyN8SAdQdzbckaGf6g==,iv:vjoyiuEtvnhyg6KwZhGNj3GDs43P+ER2+BtTCbpOuac=,tag:kXpwBwvoGMgUkiAmw5qncw==,type:str]
                login_service: ENC[AES256_GCM,data:bNZt/KE4zVdD,iv:+R/CGJnmUKBed+VgXxDCyG1T7MUNfsS8JmkKnpJf0OU=,tag:VyklIX2qU/3RNyKtUezoGA==,type:str]
            Authenticator:
                admin_users:
                    - ENC[AES256_GCM,data:XgzSUDZMn/esfzKIc+RZ,iv:6o5FwRhWC2XeyiHHaso8+7P7nfN9j3xgrSmVM+QFh4A=,tag:Hh0N+ISfAeCArB3hRQOPQQ==,type:comment]
                    - ENC[AES256_GCM,data:PQVAq+h3YijCEKVrRkeu2i4=,iv:9CGSZD0kL5ABHq/RlyGUqdg3jOwB0TtmEZPsfIqjuGM=,tag:EbmZ6eHNmdoBYoc71ZVCfQ==,type:str]
                    - ENC[AES256_GCM,data:DaP/P7purJfCUtYv3GJHDEtMbVhUgg==,iv:dkd4MAJ2Be3WlNM8LHpGvUK9YezyhJ1dBBTs2dsCx04=,tag:j6O+mvxKV7OV/mk1plrriQ==,type:str]
                    - ENC[AES256_GCM,data:Fd3V3qIehV5PbqLOeLI1aO6U9A==,iv:eQbQ0Y/A4JmgiixbjOWHyQmjVfiA6IYUvsY/neV9etc=,tag:JkPcayTWmdu4/9MvSbfEPw==,type:str]
                    - ENC[AES256_GCM,data:1w1AiXHfUrlWcAkP7nnhFm1QOQ==,iv:PDTRIAekBgm3RXA23cCDbxe3EpGjM6UJKkQrbXN/rU4=,tag:Iu58Siitu0O7OFh6jsTSuA==,type:str]
                    - ENC[AES256_GCM,data:0KaWac19ciplU9eIVGnd3RwCPRqh6A==,iv:U+b7iD47aUS3lPa+X/ovcoQm2X/PSjM5VhCOXPpI73s=,tag:/Oqjcg7fSdNh4HnoPbFmnw==,type:str]
                    - ENC[AES256_GCM,data:2gWlk6p5MtacNnXLeh3lnXnSE+vnFBBUy1g=,iv:HPDGcmI77bpCpZcTN+qmjKX/4s/ehfrTbxDRHO2RR+A=,tag:dPSNC7iS73UyJUcGianGHQ==,type:comment]
                    - ENC[AES256_GCM,data:CS4h6I8cVqKAfcuWl1YozojxBbm2qEj2hrDV,iv:th4EgZCBQN10BZPDbokvwsvp9iaDlcjYZ8E/0UJtUGQ=,tag:zraRt+WNFcttIWsx2xCq2g==,type:str]
                    - ENC[AES256_GCM,data:8HssihBvj5qC9J19OwDQLsK8bsZIAV8=,iv:WzBchl8TqkweU/8zfNvqlae9VHsjS06yoDPjTAoEVds=,tag:/HENMHRhjlRcjo+lIYvjzA==,type:str]
                    - ENC[AES256_GCM,data:8DMC4C9oVUy4bC4hlxCsD3PIUctc,iv:ZqcDM5Kndld9HxsU1vg+c0USWSsltC4Cgz6Avr3RIeg=,tag:D7KJqPnEbTuplDsnY7t0YA==,type:str]
                    - ENC[AES256_GCM,data:otqrb5IYLCI8Mtg11limHIRwUA==,iv:sKhPNJm7QtVwg0I7D+it2FZC+EEScX2b2eGPKXgocj8=,tag:QOxrzC8iGg2Yz4FgTodF5A==,type:str]
                    - ENC[AES256_GCM,data:ORlbT+SFNptvldet0/p/ltp1mSeZ,iv:WgLnnCYMKc2XHJGYKvl3BwLDp5fgG5Vywy2KvC1ZzJ4=,tag:+N4aNlauShTjFt0XiInzVg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:20Z"
          enc: CiQA67O9ADtpWA/hJP60DCxhNbErCTAO/HhVaO8h/ikod8w6oGYSSQDmhpq8Ul1cjfqqWAls2BP7/mBAEOiAreYyTkOaTgv4QP8WtCuh5TAfiTyjFsyX0ful3gGA7dhjNu5NgJxx6dEmpVHNX1SdAwQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:23Z"
    mac: ENC[AES256_GCM,data:lNQpFchfP8PAS0Blv6yjYA7tIoC+wqiBNjQrlYBtY5m/soQz3Yaobjg/57OdGku0ULRAqqmrwmcdBUfYYPHeUZ329Ql7QSgK03AbvSYolk0vtCBXWncbonB11s5r78AMgBzE+zT00lZkdij+gr6zHjkxXqqVZaCIofkmIo7x8kI=,iv:uWlGcPj+h7wfvNbThSsnpTAianInq8helvmztr0EhhE=,tag:XNHyowMiDRv1bcdME47W7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
