jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:3IxSAd6JboJ5TgoasW/Frb5czbZ/6SBOub/EQOS4j+Vcxd2hZ/FZekWUufVNW5ncYO9jWFJ2PzBCAIiOQSaYFRS9hjEfH2tV,iv:gDriKXdbN8d/cXLLc56EHSt47xz+YAtSND7I1pBThHM=,tag:qPZpXGBtWOImRiIgHpBpBg==,type:str]
                client_secret: ENC[AES256_GCM,data:BC/dgIfnfnV9Zufl9DSqyGy6uXjn8UML,iv:dBU3cxaQj2cCPAoG4ob4WCypY7VpzJMBTQug91d75DE=,tag:48ib4UqI3/K1zluD1vJfrQ==,type:str]
                callback_url: ENC[AES256_GCM,data:J47JGui05CeUXXVSXYTtSx7zUO5Q1ikCcPYo/7iTYXJQJtCiS7eWV2RTj4HYcnxm53xmsZaL2iUs4Q==,iv:K9SdW+2JW0NJBwmkdYIo9ur/tslk2wge0Y/RX8oyXKQ=,tag:5SRDAOclAwYhhL+nAA8Xjw==,type:str]
            Authenticator:
                admin_users:
                    - ENC[AES256_GCM,data:coSdHRmy4EzkPYNER4o5,iv:1HXj7geRUeN3pSnojDnKTNNMIzzw2v+NJzXTNfNBmqI=,tag:POR7rG7dmunv4DBLRfEkUQ==,type:comment]
                    - ENC[AES256_GCM,data:UqOad+5+9b9LrcUVe0RrFKI=,iv:vbQdnqZrNhWx6Uru/k2otpl7mkHM1WZAR/7EmG/RJJQ=,tag:nxdulhpgrBOyDVGTExLyYA==,type:str]
                    - ENC[AES256_GCM,data:RR5uMsoEqaM3+nKnzygxQpvJln9exQ==,iv:GA4zxqxSAHEH5sUIwybSKnUEYMI+dfviPWSCy3dhYew=,tag:2CcK8RfzsEH5Kr0IMq2Qzw==,type:str]
                    - ENC[AES256_GCM,data:qW7mSWoALqoFYeDnfkyN2X0e1A==,iv:uvajUUXXQZXdXBm/6/2457jSyYsaTtgvPcaSzBIzh8w=,tag:4zm+iP/VjXHvysqOJZai+Q==,type:str]
                    - ENC[AES256_GCM,data:VSBsFTGW514ewJ9mYA1cOgvfJQ==,iv:+lrbLHB4zkZHBBAXY8ySQARnmCKpLaH+HndHp8Is/iQ=,tag:oA+zB5YU84bKCs93NkFMZw==,type:str]
                    - ENC[AES256_GCM,data:WLGN7ViYg+oWDVcPtyPr0egx9pAvDQ==,iv:IoLd3JcblsngzFP5dPNSgMUHcBNRgKRubrYoFlBawbk=,tag://Z6BeMY8fFKiJ7EM/5+ug==,type:str]
                    - ENC[AES256_GCM,data:piBOrP5G/wGj08Sc2l+xZFfptFcalwkMylA=,iv:pDFp6/ZuueumDVkz/dPH5jSFweqmSIAw1YO9K5HsyZY=,tag:ZFLS6a9b8C+r+WvlxAug6A==,type:comment]
                    - ENC[AES256_GCM,data:A6zEtYtynjO9v/st7qXR5Eg+PHRH9vn4Peww,iv:kH+CNUlBaKOWSbXsPBO8CqFF4qampoiasCMtR2I9b3g=,tag:4XXvWcxjjH/kc4d9sMyd4w==,type:str]
                    - ENC[AES256_GCM,data:Nwo0o+cTHEHcwMaV1dCVKtqJH3XMogU=,iv:vM+VE87t6LD1A4SMyTcD9SUvwwRXbWtj2uP1n70VeuM=,tag:KqkPFWbB50CnfbXFYHhr6g==,type:str]
                    - ENC[AES256_GCM,data:vfeb6BetPnaeR3dr2YdD50vIY99s,iv:BVEDFCNDYLonwxpzM77o5j6oo6k1oNDEaLyj76bSE0A=,tag:GVsZ2YCdFbMIRM0UxPq0xQ==,type:str]
                    - ENC[AES256_GCM,data:WXDegFwdvVyV8338zD0KYa195g==,iv:DIXoIY45SKpTncKxkS9VqhmAaJ/pnMxL4dPHay1sa7A=,tag:bgpeKFzKeRoDGdjXI2PRVg==,type:str]
                    - ENC[AES256_GCM,data:PhCthVsPOVK9JDyT/Qmmbi4CqJiC,iv:zuvzi3nv/SorROUfwEtVibyU8hMsIq1Upv8VgPIShDo=,tag:D+cYWupseA3Isb8a3L2sJA==,type:str]
                    - ENC[AES256_GCM,data:RGOx8Pjmd4wPXDloLFr0i8yNy+s5,iv:NM021nyhycvq65YDXqOzlROX9WlPOKHjXZKr106Xatc=,tag:yR9Mue9PjfSCJEqCmJtIdw==,type:comment]
                    - ENC[AES256_GCM,data:0M+t/MRTXJaL4NDQKyS5,iv:DPzgbDS+8HayWk05kKOaAHn+fnFjYMXJkrhp4qMJ18g=,tag:W9wItO1Vq1oP+LP1IGwtaA==,type:str]
                    - ENC[AES256_GCM,data:5ifwx6Pj6F2BsB3RNw2DnreuJ+h43AQ=,iv:1HgPEykpsjihic5FI9qr1bHA5R7csdI9r0JOUxlCK/c=,tag:XmoRYszvURudq2FIzt1ubw==,type:str]
                    - ENC[AES256_GCM,data:23yVUPRoteJfeYr6z4IiFtSzNwL0Rw==,iv:zG/88jPKsZFef95E1kX/QxcaHV2h8AbA7l2IRom0dNg=,tag:KbXd+kQHUiYDTOv9CTfD0Q==,type:str]
                    - ENC[AES256_GCM,data:4frTM3NBZhoFtvxc1Lt5CtXXIcxC,iv:GXWkifdmoGIkUVu9TcSbeUCJSjNtDJcyYJsuUcDaOKc=,tag:zmsYJyIR2sIbTRiW6oE0vA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:00Z"
          enc: CiQA67O9AJ4YbWssnwbJJn4Z9Eqo7yGXpERJ1Kg4SvBWckPHhhcSSQDmhpq8SA+MyTAnttEfwuMdEbquYLE3X0anzqhV/kBxoZQI+MkT6WKDvDnggxaMxXws2YhXqLA+P5qzuheWQIc+D4pZ6Ii/SPc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-24T10:30:48Z"
    mac: ENC[AES256_GCM,data:TcD1iR9XbfINF7G3L4WvPufhud4YhlYNuMRDfD4jPaYlHyFbFlhX/THdWTHXLGAMvVmOt4dQiiwD4VdonbpQVOWtvFiCVAp21mNkxzjfyoJXAZRTbULhxa69smyyc6uy7M4FBP9yOCe3ueUmMHL0zuH7vpnbelokwaH8xI23rUs=,iv:c1gbR5ZWycNwWxCVivpbPXrUvC4CgTI1Mbjgi9hjpxc=,tag:G6fsQefgZwi8CRp2A/7FDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
