jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:3IxSAd6JboJ5TgoasW/Frb5czbZ/6SBOub/EQOS4j+Vcxd2hZ/FZekWUufVNW5ncYO9jWFJ2PzBCAIiOQSaYFRS9hjEfH2tV,iv:gDriKXdbN8d/cXLLc56EHSt47xz+YAtSND7I1pBThHM=,tag:qPZpXGBtWOImRiIgHpBpBg==,type:str]
                client_secret: ENC[AES256_GCM,data:BC/dgIfnfnV9Zufl9DSqyGy6uXjn8UML,iv:dBU3cxaQj2cCPAoG4ob4WCypY7VpzJMBTQug91d75DE=,tag:48ib4UqI3/K1zluD1vJfrQ==,type:str]
                callback_url: ENC[AES256_GCM,data:J47JGui05CeUXXVSXYTtSx7zUO5Q1ikCcPYo/7iTYXJQJtCiS7eWV2RTj4HYcnxm53xmsZaL2iUs4Q==,iv:K9SdW+2JW0NJBwmkdYIo9ur/tslk2wge0Y/RX8oyXKQ=,tag:5SRDAOclAwYhhL+nAA8Xjw==,type:str]
                login_service: ENC[AES256_GCM,data:CEbMI26P9sGC,iv:qPyKtaS3CxYdWCyijhwJnXVSHSJyeaamGZ21rAlpYew=,tag:8KPZ3kRAeEQhLKvqJe5n5w==,type:str]
            Authenticator:
                admin_users:
                    - ENC[AES256_GCM,data:coSdHRmy4EzkPYNER4o5,iv:1HXj7geRUeN3pSnojDnKTNNMIzzw2v+NJzXTNfNBmqI=,tag:POR7rG7dmunv4DBLRfEkUQ==,type:comment]
                    - ENC[AES256_GCM,data:UqOad+5+9b9LrcUVe0RrFKI=,iv:vbQdnqZrNhWx6Uru/k2otpl7mkHM1WZAR/7EmG/RJJQ=,tag:nxdulhpgrBOyDVGTExLyYA==,type:str]
                    - ENC[AES256_GCM,data:RR5uMsoEqaM3+nKnzygxQpvJln9exQ==,iv:GA4zxqxSAHEH5sUIwybSKnUEYMI+dfviPWSCy3dhYew=,tag:2CcK8RfzsEH5Kr0IMq2Qzw==,type:str]
                    - ENC[AES256_GCM,data:qW7mSWoALqoFYeDnfkyN2X0e1A==,iv:uvajUUXXQZXdXBm/6/2457jSyYsaTtgvPcaSzBIzh8w=,tag:4zm+iP/VjXHvysqOJZai+Q==,type:str]
                    - ENC[AES256_GCM,data:VSBsFTGW514ewJ9mYA1cOgvfJQ==,iv:+lrbLHB4zkZHBBAXY8ySQARnmCKpLaH+HndHp8Is/iQ=,tag:oA+zB5YU84bKCs93NkFMZw==,type:str]
                    - ENC[AES256_GCM,data:WLGN7ViYg+oWDVcPtyPr0egx9pAvDQ==,iv:IoLd3JcblsngzFP5dPNSgMUHcBNRgKRubrYoFlBawbk=,tag://Z6BeMY8fFKiJ7EM/5+ug==,type:str]
                    - ENC[AES256_GCM,data:piBOrP5G/wGj08Sc2l+xZFfptFcalwkMylA=,iv:pDFp6/ZuueumDVkz/dPH5jSFweqmSIAw1YO9K5HsyZY=,tag:ZFLS6a9b8C+r+WvlxAug6A==,type:comment]
                    - ENC[AES256_GCM,data:A6zEtYtynjO9v/st7qXR5Eg+PHRH9vn4Peww,iv:kH+CNUlBaKOWSbXsPBO8CqFF4qampoiasCMtR2I9b3g=,tag:4XXvWcxjjH/kc4d9sMyd4w==,type:str]
                    - ENC[AES256_GCM,data:Nwo0o+cTHEHcwMaV1dCVKtqJH3XMogU=,iv:vM+VE87t6LD1A4SMyTcD9SUvwwRXbWtj2uP1n70VeuM=,tag:KqkPFWbB50CnfbXFYHhr6g==,type:str]
                    - ENC[AES256_GCM,data:vfeb6BetPnaeR3dr2YdD50vIY99s,iv:BVEDFCNDYLonwxpzM77o5j6oo6k1oNDEaLyj76bSE0A=,tag:GVsZ2YCdFbMIRM0UxPq0xQ==,type:str]
                    - ENC[AES256_GCM,data:WXDegFwdvVyV8338zD0KYa195g==,iv:DIXoIY45SKpTncKxkS9VqhmAaJ/pnMxL4dPHay1sa7A=,tag:bgpeKFzKeRoDGdjXI2PRVg==,type:str]
                    - ENC[AES256_GCM,data:PhCthVsPOVK9JDyT/Qmmbi4CqJiC,iv:zuvzi3nv/SorROUfwEtVibyU8hMsIq1Upv8VgPIShDo=,tag:D+cYWupseA3Isb8a3L2sJA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:00Z"
          enc: CiQA67O9AJ4YbWssnwbJJn4Z9Eqo7yGXpERJ1Kg4SvBWckPHhhcSSQDmhpq8SA+MyTAnttEfwuMdEbquYLE3X0anzqhV/kBxoZQI+MkT6WKDvDnggxaMxXws2YhXqLA+P5qzuheWQIc+D4pZ6Ii/SPc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:02Z"
    mac: ENC[AES256_GCM,data:YIZV6UpO0IpqMRXKwqu5GesdsUAcMx1zlU91uZ5fXvv4zGOL9tCb3GvnUDF7CdUR8sqtsZKIr6vPRpu+7Bqmjpw5CiIi4m1GHwngvE2nf+eRqYviLbQXgXgU1dak01u61cSfwRfZ7ZG18I81kGypjWG1Ne79tpv/2itEwAiL/KM=,iv:27UyrQFpfO+5W9a8iJjYRnD2xNaQit5+uFVdaPG3ugs=,tag:kenR0yQ3CcivsmAM4e6p1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
