jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:eLIJqJUkAyUGtNkcVJ0R/4CGgItvB7Crh49HYdCzPXTCjb1ADTExq+2nkWsoJbSxTcOviNTcErkpyTu1nUGPnc/0ZEDGpyN4,iv:y+ItHf+V1WCXjkGSJhxi13NgE1yB731UDnKlUGE3yJo=,tag:gukt8AJ4TknHxJo01XX+PA==,type:str]
                client_secret: ENC[AES256_GCM,data:v8otv7tr8I+W9VPU0bEzbnOsw0PcQQnp,iv:BmENWLx/yi55BHeHUoEhl01EQWtRGYSx0Fyv3fh970A=,tag:jGxOgCWJF9rKBxWGPHB7ug==,type:str]
                callback_url: ENC[AES256_GCM,data:cNOS+62ygjcSXglXg2Z2h3VKdPRy8xNAVB0VKler+QAaO5c+BO7LFE5gk6+CJSFUUrPpxA7AjuzyEo3xVjjqTIsB,iv:4RKSqKep2Ex1ap3/HSGWcyZHNYKBdHHtHANsASYhw0s=,tag:O/O5/tEJsTDePy5ijemyRg==,type:str]
                login_service: ENC[AES256_GCM,data:0coTShwS51eb,iv:lisx3fmNfD3EYbtA21HJ9sOHJvQxTfPtTUt42fGAoY4=,tag:pOaOBKbPuiwtj1PRuOOThA==,type:str]
            Authenticator:
                admin_users:
                    - ENC[AES256_GCM,data:ULZ6uoDeNzj/wF7KARuA,iv:tqjoy49tZZ82J+2T5IUa8qSouASmpOTF2BIVhLUMb2g=,tag:EGKhT17ZLIdyXbucwJTAwA==,type:comment]
                    - ENC[AES256_GCM,data:4xs+dk9iQZ74CF6gY8gkrcs=,iv:TtllI+KAB2rR5g3eFUF1SR1N3XdvuWB5E7JH3USpmOQ=,tag:3YSdDbgxsGBu6suTa+nvhw==,type:str]
                    - ENC[AES256_GCM,data:8XF3WCg9/aNMFiFkpXN1vEHIl7jN0A==,iv:4B+hBlg0G5EkM1zCuMgSUmObH/gC8TfsE465d7AwhuY=,tag:rNUylWiRpr4NgIuiFwC96Q==,type:str]
                    - ENC[AES256_GCM,data:Z6usABHGqGZCmxRVmsuH8RKRmQ==,iv:N2pBIP57MzT+N9lnqEYGGDRcJVGzbgiF8xVzYvi0rEU=,tag:VKuIR9It7gjJZ0saH00fSg==,type:str]
                    - ENC[AES256_GCM,data:XG/Wjjftsa8mCgWUJ6WKkKCAuQ==,iv:8OsD2MT8R+IkA62tV6Ci8YqgxhbJkPRrP316uKfP4F4=,tag:Uj6CCMKPlBmOGtjgiYXOig==,type:str]
                    - ENC[AES256_GCM,data:lh6QHfSFH+0VM7ul/WN3yJ1hU0MEzg==,iv:ubNgKz0ttjbI24uGqkgtbY4LykBwe5soKPvbz+KizJM=,tag:wClPsaYLXXnBcwDDVLayBg==,type:str]
                    - ENC[AES256_GCM,data:NX4yozPxOH/f0Z+v0WVh1pRTEcL3vYdjLLo=,iv:WEoVXEXF/USGucSG89Qs40qiI6HV6TZbbL1cSZlReFI=,tag:2i4RqQam5832rmBDODY9ug==,type:comment]
                    - ENC[AES256_GCM,data:q03EEertwWEgGh1IywHDE0gg71PqQc0OmYwJ,iv:agCBOCBGBk5m3MbmSjUs1VoSnmoJY0pSiVsGo0n+e9o=,tag:kGnk4MD7vTt8NWiK2TT+Rw==,type:str]
                    - ENC[AES256_GCM,data:eqGJNDz4X1f+vI8XokPJpKfpqWmzFRo=,iv:u1YwAp17KLHhvdYEGx9Ob/9gxf6mtRdOJlwFpMMnznM=,tag:vrKUDYy+87j4gg/g986Sow==,type:str]
                    - ENC[AES256_GCM,data:xzcX35+FNqrB0tUT9qsRM2jjDDJX,iv:JfiDX0UWDlULxDlwpjn3DFJvwMnrWnNArsI2QZhY5xE=,tag:lgo8Ym4YKhTHAbJRNPkyVA==,type:str]
                    - ENC[AES256_GCM,data:eEEHh1iURUovtksGO0MUVclkIA==,iv:0pQbtUO8xl8XmlxRZgT9F7U0MdPkzhF+DnI/hmH3YTk=,tag:/3boeOFjP7WPT4iMbXfrqw==,type:str]
                    - ENC[AES256_GCM,data:BQqnxqIkGbiwajCLK9QOO8phKPCw,iv:CUyozlo/54WDzie7uBynIMddPPHSL0OaRKG97mso9dc=,tag:C0Mia8FYP8jSq6+ahJfRgQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:19Z"
          enc: CiQA67O9ABo4u+bI51xiPyVhFcCNxj2S/ZstG4IdO1QvXN+481cSSQDmhpq889QRJibKMZVbmxM2UOlipTPyBr8g23PM4oq8pw1AZd9EhKFouNwtsZqY+UMRhdbGTiqVmJrqug06gi8lRWfHSUIij+M=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:21Z"
    mac: ENC[AES256_GCM,data:1CVKGX6otZEeEKBmEaRBH3GtYR5FjG/VRdEAVT5p3JOu1q75pV/toSoqpV23FXebhTtzvkUgYJ9TpVKA+chocPaDqzIOiofy5JPLaNY3hWw4DVPbsFzZgL/XqXWqowlM2Tg+6whyLzxjOu5FNdMqvGwGZSPkCiVLneVqLrorTZ4=,iv:UKDxWx1XxmnJ5T2XQ0AQFRbDes5apKoz7czOrDo+Umc=,tag:RXkiMP7iWtDyU6o7Ufu39Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
