jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:x0L4eFlBvQxh6YfNUGBLtY/5fRDqRn6OTE1b1ehg7hEcsCJk419+XDFXkeCbmhMgjlqBfbq9OvuDluJe0ngRmEqH8s9oEAx0,iv:KQdrURGui1G/SLoJnyRKPswKCMBY6ZNCMuR24AaIes0=,tag:ZfKZp0I/wThui2Af6rxMHw==,type:str]
                client_secret: ENC[AES256_GCM,data:hDS5s2bz+fZtoMV9Xdwu1O1ux4Ap2rhk,iv:BP1Pp5wiwNv2FV8soSAJH/6tvgQeaG34TLFtdqIl7Wo=,tag:D2DC7GnOoyOlJL1VSTwFtQ==,type:str]
                callback_url: ENC[AES256_GCM,data:l62Tbab/5Ylc8f/bQSXROm1ZPzUaEga9CLt0togg0YKmm4Lc2sUWMAMPmrI6ybi2X69Ml+xPePm5sA+ynBzArtSb,iv:Na3eAnxKRU6ZGszj7p38ZliiXbgZgtOjkrQdCIJNE/8=,tag:Vtc0c8uVni7KISm0lGYiPw==,type:str]
            Authenticator:
                admin_users:
                    - ENC[AES256_GCM,data:MT3XMw90LYJyuEJ1ZYNt,iv:CbXHeULLRZPUsHa+vFnK2P1GC1r+CDZaoCx0lSGaqFU=,tag:+xKtmmNuX6JvqxfIbykdZQ==,type:comment]
                    - ENC[AES256_GCM,data:m1IBH5b9G4rvdYcCdeQId7E=,iv:hNX3gJS80h1UxGn0jz2UGjKjaAytDAg8NCnVx4El2S0=,tag:G98GMrPkh08n7yPHLJiBaw==,type:str]
                    - ENC[AES256_GCM,data:mf7QWvZSRVzdONEBFVicGOTOOHvSIA==,iv:6zu1K35IS1Xx71mVSTJP+qPawrmUqObzPhyeTx+8dX0=,tag:WbEiXL/seK1Bfe1q+hyPHw==,type:str]
                    - ENC[AES256_GCM,data:vlg+ROsHMdHjjMjr6zVGjpvMCA==,iv:Yz9n/2fsbaRSk6zB1+pQkoKDCDxKGu2lxV7KAS2aEzA=,tag:K4LZktamCbnp0gzbjIzJhA==,type:str]
                    - ENC[AES256_GCM,data:YcT/kiuvO2MuHBr1dcVH3Xsn1A==,iv:bmXSEeA7Xg/MTKfR84VD9CoiXYaqkKyw70OFdHwi77g=,tag:s51QfNFvEqgTnrmai3ZYHg==,type:str]
                    - ENC[AES256_GCM,data:k614HM5cA7xtOvhVUp8nyZ5NY++6wA==,iv:Eb8bj39QOhtNkx8hoTJFjE9VS06560qw7fMtuRDP0/w=,tag:1Q24n56khb8XsLNxPvPYFg==,type:str]
                    - ENC[AES256_GCM,data:SH4tF6rYZFUSYA+aP7ulFSihYuXqppODEKQ=,iv:lOxsnqYm595O1Y8rtb1LIS1ciiDbwcOJdHp9z9TWDXs=,tag:kBz6UTOC3/hqVQLnHmDwjw==,type:comment]
                    - ENC[AES256_GCM,data:83ntZJN/I3eZxrvE4D2srrHdLX3r40g2u8bf,iv:kdyOitOw2XIYry1qJjBPujnc1XtfmTYgEUv84NW90ZY=,tag:EVIoHz3Fh3hAOo9n5zJoPg==,type:str]
                    - ENC[AES256_GCM,data:+YnBUeF1DiELVX4IEyrkYiW5RnWyLZY=,iv:SqBaiv0zxJ856BuZmrn6vBEuEeIrUFY3VlrWoScykMI=,tag:UdVojxnmHjLz3sKFHq1Abw==,type:str]
                    - ENC[AES256_GCM,data:sigAiDJZVKPJ0IBMtpR2HoV/XASw,iv:S7lNlrjsAVkYpnQAcQ0xOrx8mo5NziEgjXrsPU61Peo=,tag:0MPiBnqQ1bRHkZ5bYXVXAQ==,type:str]
                    - ENC[AES256_GCM,data:NKSlav8E3CorJHKQcmPiiDr68g==,iv:Drq+Pa3ab8TSNrmZXwYaug6XMJ9YaGLPRBQVsrCBs7k=,tag:HXEbuWBCIE3Iri8Bkr08Mw==,type:str]
                    - ENC[AES256_GCM,data:9Uh7Gcv+rSD3fdjAwgrBVb3tFGJ9,iv:XO83RKofKMTc40Wala3/rJaUirbpgCCTGXFjwZcB+Yo=,tag:caBzslRoOK02J5PUuN33gA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:00Z"
          enc: CiQA67O9AOqJ7c4C/+H8Se8S8UcC/QIceSUR6gPYrpZZrpoa1RkSSQDmhpq8GkFAuLtwWA6iIlwLGbZ4QCCLycFacHZ+KeH6IarfaSc2fxD3qVMwVTziTk1oqaHT4MhGQsnymA0YbfdiL0G+Torc71E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-09T21:50:29Z"
    mac: ENC[AES256_GCM,data:rDGdXUplxI4qIiV9+tpGDSEYXEVxfH142AMovtypdN5rVKF+VaWRW/zniOB6oVDKXKaFpYO8mhCFAqW4CbsfZ70+85o6XIXkI/fRLhmvpGToR8gQynNkHdMv6oPA2iGYpqWCYrF+Uh3GCTh5mFRobZZNzl71U6Tdc/5uyStETyk=,iv:EP3VsE0FHXYq7lu/rghk7UKjyjZKp5NEEH9wAMMp+Fw=,tag:8SGChEI8lof0+6XMaQNIhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
