jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:2BYPdsNK01PHoFml3I6cRNCPCwXdTNTwuhchy72LRUWirf9BJxMAe6/bEcOUk1cs7uQOXuZFZF7GWatPw2+fUQ==,iv:QMFwQaBUmuDBsSB+VPgaRDN/j9i5OQzhyom5YaRtlWA=,tag:JuOVcbaJY5fku8puptEPWA==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:Fm9QwqJKVquXy4nObF3Sn/6tzqJmUU9pTL/rO22bQa6TkAM+M9dgpodY4z8ov0oizc4ilZwaKbyezPbnPhmtlg==,iv:lW7ekshc1OnTy2Cuz87lRSlGvX1CMF22intsLotoBik=,tag:4Yd2TuKTqkoIMwZF8k6/fQ==,type:str]
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:wKsCc/3Eb/Vd0rMh9lLmdVbyoNEEkY3Dui3AuTikvs+5cpANuEoSAzIl95t09z2rXgpGAYcFF/DiNL+/R1keYJNdEn1P6/+M,iv:PFtnRJk1GZeqWwpya5A4clQefT0dcRqw3QPI3R6row4=,tag:YLWwSy5A0SYDvZcnJlbWNw==,type:str]
                client_secret: ENC[AES256_GCM,data:hzfdvjMjEC0mFyVyjvp/YNTiFRINDpzo,iv:VZ1b0Yn9BF6dD719llueZMsSgjYCvIudgksrRkG7ryg=,tag:+cRQHgaYYZuG6/EzgGywXw==,type:str]
                callback_url: ENC[AES256_GCM,data:8uzaO5piqHf7DFsJHm1IOKu1At8OIWKCFlU87rwoOCJRtw++XO/kh8o4bUw78/SO7VLqW0wk921cFMNMwR+gpSdj,iv:dG4HB76NopZmctLv/TbiMXfAONmBBnFpvoSl+y7GRWU=,tag:iBSEOD5qU36T7lhFJDA5zQ==,type:str]
                login_service: ENC[AES256_GCM,data:+J5sdYIIbMWT,iv:VUyuI7gQXMP/0xsnijk4FwiM4BIdlW3YdmnyY0PWn+Y=,tag:7d7iToBdGgc+KmIXJgU8sA==,type:str]
            Authenticator:
                admin_users:
                    - ENC[AES256_GCM,data:WiDjPU9DMwIi9HRbCT1i,iv:uaPJB5HfKxjRvUXCvx2WpTVnvLbukaBKBCEC/W0Tsng=,tag:b+uMaQuWuqBsi6yUt+llag==,type:comment]
                    - ENC[AES256_GCM,data:tg4szRJU5bzAHEIocgbEWeU=,iv:T9JrUhhhemEz/xJTHCKo5uikkbJ1MVQDbefkhv3XpHQ=,tag:Ch3GyieeEFZjj2C7yKLMwA==,type:str]
                    - ENC[AES256_GCM,data:U3e7XHPjF2H2gB1rKspdVnTCcyN2uA==,iv:cntQ4+nxN7yR3Jr+6sIkAk0LVWQnhTXoDdRQgTJhbYs=,tag:RHsoCFTDzEjQ65qrdYCp2g==,type:str]
                    - ENC[AES256_GCM,data:Evp+M7t9/B7VB0ZiDF/zZ9/qeg==,iv:nhPSr8zFRT7WBGP3mHkkW2lMETJfqcYUFRYONiObv64=,tag:HUE95TEwKLmumlopUZbU6A==,type:str]
                    - ENC[AES256_GCM,data:UbXSv6g+t4WyWzm0MCUFug+eZA==,iv:5qDWXSyOIywe/IDZ2uys75mmcdQGaVz5SF0o96/uUDY=,tag:7OUp25iL0gjmEd8ue+XG6A==,type:str]
                    - ENC[AES256_GCM,data:geWdJ5mTVvht/xa7xuMzqGvqfR319w==,iv:EYDz3bS9pcqfJ2N/2pNdWG0Z0Q5+88R/ZMz6Ql0pAh4=,tag:WToKgYjl/SvU4F/XHfIADA==,type:str]
                    - ENC[AES256_GCM,data:KwjKnwlClFX2mf6DKg6vWV3rrYMbDP9cAh0=,iv:eKLvJ4uulMEJ2OBJDFALTkH/g2N3flMsCmDRiUyXOuM=,tag:dfLPWGeumERjo0OF5PQ9eQ==,type:comment]
                    - ENC[AES256_GCM,data:4f/s8ZU+VOwxWvgZH1r8nNHF2mdrG9vQNzUH,iv:zOAUCRNs/yvWgM+fWlWdwKS7tNCJYe9FndCJ5fBqKH0=,tag:LXxDKc/24ifit5e4YY64Iw==,type:str]
                    - ENC[AES256_GCM,data:t6Yb0cHzPMAsUiwR4lFN+AVNwOO78KA=,iv:rhqsBUug0YRlIcvTZd9wTzRFcXUTO/MfS6yapDNzhNI=,tag:oB4qemwbBeRhU6p/6QcLOg==,type:str]
                    - ENC[AES256_GCM,data:y7NzdAcfH1Vyhm+Dqwo/6fOdqxWj,iv:ZNXHl/Zmlo7EMYhAHV84P88d/MfBKgDgALl7XlvQ34A=,tag:tvRIhgM4H6ftl4fkm502cg==,type:str]
                    - ENC[AES256_GCM,data:E9ceVcVsZtzXpS6VB6eFYHFs7g==,iv:0LyRvzVBD/ra6G7MSq93MJFKRQ+PyBXEvMXczzZZWe4=,tag:PZG0+7UQi/oj7WHoMDl+ew==,type:str]
                    - ENC[AES256_GCM,data:5Z4o/QD6DTdGXXxuLp6BAqmuGQOT,iv:YDYUtAaIbSvOKYDNll5aKvBMyuBqk/zVOcfTdD1yas0=,tag:rioyr5D+756CPQgNu3ZgGA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:05Z"
          enc: CiQA67O9AGZf+aJToEIdfKi6KQafMVexzXv5+vyKK4OkTzl0XlASSQDmhpq8x5BdKw8mNy7d1rZp/18Xl1itOBo+sCsyKVh4phgKkuILQP9fO7eHkbAlFzAZU09irNWi1rvTsBJOTLvfLTaBbVchWjw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:06Z"
    mac: ENC[AES256_GCM,data:9dyn5M1I+pHrUiICX6ST0/wqgfTru+n8IgwuJZG4ZpndrbA0wDmLl2Kuu0rhaEpOw16lpQMZ3K6rHELmgfhUUPEQw7007fHwZwtKuSvcOxMzNAmxzo7javQcIAu6rYXSWzFQY6U1E45aMD3VtE44d+8F/1NSZbyIhVOCN8LKMQo=,iv:A41KHPUTv1gzrDhRF3FcJhslrBnXz3++9o5pzwt87rI=,tag:OmQQDkfTyaEz1OqRtmrVvQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
