nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/datahubhomes-2020-07-29/homes

etcGitConfig:
  enabled: true
  gitconfig: |
    [credential "https://github.com"]
      helper = !git-credential-github-app --app-key-file /etc/github/github-app-private-key.pem --app-id 94386
      useHttpPath = true

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
  hub:
    extraConfigMap:
      # this should be migrated to custom.profiles when that works
      profiles:
        # ESPM 157 https://github.com/berkeley-dsep-infra/datahub/issues/1849
        2020-fall-27267:
          mem_limit: 4096M
          mem_guarantee: 1024M
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    extraConfig:
      # 04, since in hub/values.yaml we explicitly set it to /home/jovyan as 03
      04-rstudio-home: |
        c.KubeSpawner.working_dir = '/home/rstudio'

  auth:
    type: custom # This enables canvas auth
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # PH250WF+PH250WG Instructors, issue 882
          - jadebc
          - jcolford
          # PH250WF+PH250WG student assistants, issue 882
          - anna-nguyen
          - lucascarlton
          - m.ruiz
          - nolanpokpongkiat
          - stephaniemholm
          - wmjilek
          # List of other admin users

  singleuser:
    extraAnnotations:
      # Enable prometheus scraping just for R hub
      # We scrape only every 5 minutes, to not overwhelm the prometheus server
      prometheus.io/scrape-slow: "true"
    nodeSelector:
      hub.jupyter.org/pool-name: gamma-pool
    storage:
      type: static
      homeMountPath: /home/rstudio
      static:
        pvcName: home-nfs
        subPath: "{username}"
      extraVolumes:
        - name: etc-gitconfig
          secret:
            secretName: user-etc-gitconfig
        - name: etc-jupyter
          configMap:
            name: user-etc-jupyter
      extraVolumeMounts:
        - name: etc-jupyter
          mountPath: /etc/jupyter
        - name: etc-gitconfig
          mountPath: /etc/gitconfig
          subPath: gitconfig
          readOnly: true
        - name: etc-gitconfig
          mountPath: /etc/github/github-app-private-key.pem
          subPath: github-app-private-key.pem
          readOnly: true
    defaultUrl: "/rstudio"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/r-user-image
    networkPolicy:
      enabled: true
      # NOTE: This is a partial repetition of what's in hub/values.yaml,
      # add an item to a list. We add external ssh access here, something I don't
      # want to allow in general as an anti-abuse measure.
      egress:
        - ports:
            - port: 80
              protocol: TCP
        - ports:
            - port: 443
              protocol: TCP
        - ports:
            # Allow FTP access https://github.com/berkeley-dsep-infra/datahub/issues/1789
            - port: 21
              protocol: TCP
        # enabling ssh for private git repos
        - ports:
            - port: 22
              protocol: TCP
