nfsMounter:
  # Re-use datahub's mount
  enabled: false

jupyterhub:
  hub:
    extraConfig:
      # 04, since in hub/values.yaml we explicitly set it to /home/jovyan as 03
      04-rstudio-home: |
        c.KubeSpawner.working_dir = '/home/rstudio'

  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users

  singleuser:
    defaultUrl: "/rstudio"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/r-user-image
    storage:
      type: hostPath
