nfsMounter:
  # Re-use datahub's mount
  enabled: false

jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users

  singleuser:
    defaultUrl: "/rstudio"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/r-user-image
    storage:
      type: hostPath
