jupyterhub-ssh:
  hubUrl: https://r-staging.datahub.berkeley.edu

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 34.68.107.18
    https:
      hosts:
        - r-staging.datahub.berkeley.edu
