jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:PYVO+6mIh4FpO+t9F3awtUgOGMXO8zkUYB80102oP8n3UFkTqVVotqzAB4C8faKjA/A7Qz/4IuWxVYC/Nt9h3w==,iv:OqvPrOPjKGeApT/+Ykr9bKJf6bDfy06AuQasUdBjD5g=,tag:bPy/C7fHG+WcgpPoI0j6dQ==,type:str]
        config:
            CanvasOAuthenticator:
                #ENC[AES256_GCM,data:wFjGEn0SIkcrWUwvmfH1EFCG3CC6r9EdjnZ5SzC7b/rGcYHMIPzBLl4vyVJKWJW/onnm2Vd9w8vGSwwi/g==,iv:wuOaOgMH+GLu6Mb60UU7ab2/e7caUAoAYM45JZGdmQw=,tag:o3NuPdZlz5UJGOIXGMWBFA==,type:comment]
                client_id: ENC[AES256_GCM,data:/PypY5KDye2NRKfQyEJAGjA=,iv:YSF1QKIczh7IN5LGaJ4//qKsQ1bGHLXG7MHQjAu0kQs=,tag:Kv6FDXy0dT6HFGeYSDX5NQ==,type:str]
                client_secret: ENC[AES256_GCM,data:AxZZZgAKuLIaOB8bXfb6qERgNgE4zwZOS8gPLorHJbuCPEcHa4J44I9ydlJcdSgn/xeLgWBJj0e6+Q2I1q3rlw==,iv:6klwetfMgJKv7YyQvH3RIoGJqMZmq6ALhhdscpPh7vo=,tag:2lfUHNLDGnNoisaXMw6A9Q==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:JJ7rYDVbhq2NaLnpBsmVXnJ3S0tU/YX/msIoXAQuQWK0fxovo8YiD8D7vW3pvP3Mf7jBG7uF2A==,iv:HKhXKoHwNHCCpDCLwUeUR8ohi+9KmtdRAWlaykvG7Qk=,tag:9QmXQXNQiCOMKs9BJnC+Vw==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:5N9flHpjTnoB911G22pnl+oYszvfWGAHMtdW6yfnzaBElxyYY1Un239ByRXrrOuTZxYV567iT/421y0W2wUjTA==,iv:GYJnTFRqLTjXUu0KzyAVpOqumhx/FMsD5iJBQJ4J8xs=,tag:bNWM7t22cG4CweO7f4x3jg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:06Z"
          enc: CiQA67O9AE2IhPCzlk3v38ukDXbSB3U9fM4CCGI00GSeFkODQsQSSQDmhpq819lIAn3GQ83h27fyyNWsPh/KOccCwVXCWFUslfP6byyG7VJtZ0ToeFtR9cgm6XC9bPyZ01C1p7MbcSnEJwftEzefJj4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:08Z"
    mac: ENC[AES256_GCM,data:lPZIRH6xGtIw0ObIOMJwDdhEf5Cd1LYt/QVkMY8Uv8SM7WU66qJIjy05AwZkufbY3f6E2UQcQo0oifWkeLkH3qhkyeUyo9diwGPjvSPZRneOFcTKvfsh78NFzg4yENvZhWVQyjSSBrCC2xquRzqf+D9gRX1AnZJ72ZQPwpIhAC4=,iv:lvX4AcBj5lPPn4lsT5/NBWDOsTcldg/7Ft0AVtduZck=,tag:MaVgr1/wMs1AZi6Bds+OMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
