jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:Y4+xsn3sShKfeSXenWENszDAAYF8K1UMQq/W+O+JQ5KA76Q0k17N7VMqmRkkcazOq+HoSBw47uGoU+LHemdYnQ==,iv:RQjN3dbLAVTfoc8BW0HxvZN4JURCsvin5Uc4SmpZzos=,tag:F/4ZfWFMG+kUc8PkbNOG1g==,type:str]
        config:
            CanvasOAuthenticator:
                #ENC[AES256_GCM,data:KgYnWSGYfVUZvWeH2+s9JfkI8+r34cNMZDks2FVlbRnT4jIEMkoP4uX7sVQEo2sV1EOtH/BBG+/tTCZMfQ==,iv:J6wv0UQs0O1bPyh7gvV/Z03NOtmITbQ5LcBZv0939Cg=,tag:Em8NT9rAunmDxH1ePHel1g==,type:comment]
                client_id: ENC[AES256_GCM,data:MRDcYXqGeX/FPGhBlI6dcZM=,iv:wqIOARKgvvI/+yuDSQZyFUULG+30w+Y6jK3jh2wJmrc=,tag:BDJb7oRLokdRL8+cq5g2YA==,type:str]
                client_secret: ENC[AES256_GCM,data:AuOdxHN6BSLeSqbRzDHHivklGBI2Uuro5PeOWxpRqyu0hzdF3C7a3F4/VQUdSi+N0M5kdQSoey6/v7SobIeE3Q==,iv:RZIAjThJUqQJUrvLdwIY40SLeHXiIh5yR117UgWOYZU=,tag:242hxOttZ5VtVdvyUgzhVA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:3QoP2ofURwdW8Sbe54ZpLt3isosp9v7P6ixyT1NV4f6SBLNWVd974HOjT/OFQe8gLXYFrYWlFA==,iv:f6yLbKEqvHHQTxa4XpF0daa03KoMv5xdF44zTeXTTPk=,tag:+zt6UnV6umnxLWJzZ923OA==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:ud9RWIDIjRBKbgEq+bxN0K+NKh2TFOZYMitw54y2boo5Fy61Px0DlaEs5UNyzkc2BCrbOOvZj71UiTuLC4rnWQ==,iv:J9sdFyK8SHZYxtA91kJs3HgdD1NsvYmcqFGBeZtuHI0=,tag:nOpWKFwuSphJ10oPqP7dZQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:21Z"
          enc: CiQA67O9AGQIhUzzX1e5ko0v85vza/bjc55roq/Mb+p/t7hwlskSSQDmhpq837p9seA21iAWadGlYC4WBGUVA+9V+y8jg7Xhja8Rc8PAUWDdwvaPrKpLlndVGmLPaQi8Tp5Elq5iXKdUMZiGqbRCGHI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:23Z"
    mac: ENC[AES256_GCM,data:Xe/rkcGRVQozzaWHyWjmsVg8HsU+mt64hgW4PVLsPw8C4DQ/e8OSANPf+wwm4DYrxwAs1PKAdRg3P5pjn+SQKHrjmuWCnsfdpweO1UHAmYU1PQo4XDVsSHzIln0UoLr+xztCA87rVFaMtIjJ43elqPLbawH8SJ1BJaDaCnsnoK8=,iv:vrlEoJM7Q+CPVJjXz3ZeOQ5OgbS/31EUNqUjqJLnF8c=,tag:yd8GJoo7JkNPZDXx1nP/mg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
