jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                #ENC[AES256_GCM,data:2TWCv5kSXA94s56A/jigMeeKPqUSlOdR8YrdyeTJ6pfvR7K5/BCI2rfT0Sk4OqWezOCi9sjW4ruqM8qAMw==,iv:lxkNrKvrCQOq75E7hfH9BlyS3inMm7uPv5ccRrTQeuc=,tag:b74KjIQ2bJWS/0zlT27mDA==,type:comment]
                client_id: ENC[AES256_GCM,data:csZjYaSh53KK5pu7edeeZu4=,iv:jDHRKHihME/YmHBa85+M/JBy7yj9YeOom+3dqsBhsCE=,tag:ImtLni2Bnpwd/zmlLZtxmA==,type:str]
                client_secret: ENC[AES256_GCM,data:YzRICJWCoyIxu1YBE4wUgLtTjGTEgx8lRXuJnBwMYFB50b/vvkOs1rUgqReVDAPwiQYlO70j1Zx1009F1leJwQ==,iv:wSYf16IHEE6xZRqgQR22FajFQ1HeuNkda2G4Sy+c734=,tag:dxRmQ3wDsh0iaPLVMZJPAQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:yaSb4tmrydlhB01LjCdT0ePYifKzO4ymxC/r5sYkTiRBebJoU8bBSmN2mS6cMf/aBeJTY2rV2g==,iv:OF1s/NxlUkMxpJ9/Tfk+r4BgqMdfg65d4QHBfdkz9Io=,tag:l3jRpwTSFYWil7l8yxZW/Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:01Z"
          enc: CiQA67O9APjuEc/VehOAROxeDf4mJUcdNeaQQwrxVhc4zviocUQSSQDmhpq8Vap79CubutQf5oO7cNGFFiOycIYX8ACiVxriXxt14fIHSOro8WzpZdenP7100cLNIkQaei+kaGHIvTBwBJrlAFjrqp0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:04Z"
    mac: ENC[AES256_GCM,data:2x1sOj1lm/j1Nf2563bAcUc1rbsTLtpEsMocbMgYkvDwRYgiNdfgjvNbY4vJamO+yIuqpoWJGD2ExxBp9lHuF3g+z3n51njyLnxcu+ZPnL2YaWWUSzv+e04V/s0Q0N3XpE/tHVRGekowV2r0/qEk61Y9c9eMzm2BL+t8COhs1qs=,iv:fJ8ZGJK3UNltGRJ3AffCBXxJC/TSFlmUFqNVrU1jXMo=,tag:/CuWW0xrTx3PoTQb0V0s6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
