jupyterhub-ssh:
  hostKey:  >
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDX4uStAu0MUVRTDD0tghbQtcft2ud7aS2QslzkvsTQdgAAAJAWzp/YFs6f
    2AAAAAtzc2gtZWQyNTUxOQAAACDX4uStAu0MUVRTDD0tghbQtcft2ud7aS2QslzkvsTQdg
    AAAEBt5FqEZxTuOnzfZ+qOskyRv1+fLhV8eZmg+yABMGkZqtfi5K0C7QxRVFMMPS2CFtC1
    x+3a53tpLZCyXOS+xNB2AAAACXJ5bG9AeHQ5OQECAwQ=
    -----END OPENSSH PRIVATE KEY-----

jupyterhub:
  hub:
    cookieSecret: 9ba86d79ef9f1ec9db9625916ce4f450318a1f599dcb6ee6640940a3448b6c41
  proxy:
    secretToken: aa77048071dd3b0f61033cb040d27c7c0b38f0f8f3972d852d054bd89cb89c34

  auth:
    state:
      enabled: True
      cryptoKey: 45325d1aa809d9d2ad0526d4f9b333250d48af1b2f7301f00d1a1dff46ace4e3
    google:
      # Fill in as needed
      clientId: 639319454093-m1525c33cgpsg8mdmp3odrl5hkhepunc.apps.googleusercontent.com
      clientSecret: kZ5O54_LJS1Pak7WYftIafUQ
      callbackUrl: "https://stat159.datahub.berkeley.edu/hub/oauth_callback"
      loginService: "Calnet ID"
