jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:ibzkp1aEpA9CHZDk46FUhXg=,iv:pQcvnICNRTaQ/AVYTDDosIhawxjgRQ6mXJmIVYZZzdM=,tag:xUuQtLI5wI3X17fTjzFYtg==,type:str]
                client_secret: ENC[AES256_GCM,data:Kih28dJUdK2/SEujmddu26hmsT6WDM9Z5eeFm6Rx2Kl7HWEG93ts3qP0EIklgoKbZ/baYTPaHd2oJ5/3iNtgZw==,iv:H6AuJIgkagUs4CfCHSww3VoMhlWNCdzwzLKOgeKF0Yc=,tag:TKgmwJ3zBFRrzcJJFCpr0Q==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:a/L83EfXpEcUu3JXojH9Lm/PxLGDt8ntveH6G3Cb7WIalZEO78LPpyHAyCFbjqpoDKCHgRKSSGQjA6C+84Ik,iv:AfJJwyDmwxcgMo8YhcyvAQ7PQDekVbUY2XU8AOsHm1M=,tag:6HNHubLqNqHJ4D6Pop4fUg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:01Z"
          enc: CiQA67O9AFo08YZMZBLJtudBWKufr6N25KZLIkqNg6lPMFnIbLoSSQDmhpq88aJ0ZuivNWHzmg0sGY6TZtsivrPLPGLte8c5sHwSqwST/c4UzsRaAetzLpyWOUEqnmJRC+Mq6Kk4KTIvkr/QJl76P/U=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:04Z"
    mac: ENC[AES256_GCM,data:43Z4diKXNmQD4F/rhDbNDhwAtWCboY7CjiUtSxo5mvg11hD7cJhHWAiXA13bZT/9/vYZF95f8aU/nbCIdqGkQGUW2WjzISUTIxTiOO1HK38+yPbi2ZCDtq9WvlQO9AX8owxDpqILbP/g7xN2wzvSPBTfaywWKH7+HOcE2+M3ED0=,iv:YlLXktydATn3i4cy11R9YqYuMbiLDhU1YZJ+NPoybfA=,tag:sbBIAqD2cCLjNv/YFPo6GA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
