jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:YYHYZUCLhiCYM5cqocZmiRdNUSqUxM9qy5yfo/UIR290+tWXbG5NaZM8ZLydsHSbZK1mJhfa/K5kQQ0ENwCxXg==,iv:a6w4OpQAgmsw1NuDrJIfUffNdIeCh5Qdam1f6rlQgss=,tag:Gxc0h0bZ4gfzffJS57HPbg==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:Oygoyp2ncMFVP+ZqIkphWDI=,iv:EfnHv6+VdS77fwIqkKCiPYe8c/SP4AMx9pCPQStjHwg=,tag:J+ucHW9n+fMfRE28Wzu5QQ==,type:str]
                client_secret: ENC[AES256_GCM,data:2SEVHZ0LhpxKMok9wuFIx1wg+VhFlGPa2fLakOvClRB9P4Vwh8tA8HHEFHQGSfN2qa6wlkY3JHjFzTz2bFJa3A==,iv:lMbwMaF10NfLDUtNyPDxCNN2mPtdWNfl+KyknYDzfF0=,tag:3KMJ3BCpOf+f74Aln/E9pw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:7EsOqUkCq985RZRM+17ils1jRQeuIumAmmAIxQyvpT/2xwq77qB5P1jgcsvvMW6DpVbJp50/C1RWFK1IYCNp,iv:WaGwp9bdZcfjSIzc3umGgs+wZ+vv/EP/CvLffN8nevo=,tag:2QVshivkezLmmvoLFpE/1A==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:he0pr/dWJYCNE5Eapcc1L/DhSthVD/80go+9RWjrxA3t1xQ6kdCC/wn04cpe+tRuiWXD/gkyAc1nkj6ueVB4NQ==,iv:Sypf6EIA7El18x37Afs3HGDUH59FKqnFXik8ZTvn/tc=,tag:w20RXVavRGEGvIOikWPUug==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:06Z"
          enc: CiQA67O9ALUZmm2Z/BRvdBoMQZModlajw8VSiT/xt0iY3vMS9uYSSQDmhpq8Is+llgIT9i0EEYp/SNmo1EcN1sGCmVjqc1ptk9jtR5WTSgB757yOJuML25KAF4XtzPrsCGwoVSsdXb03rKbXUcwqUFE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:07Z"
    mac: ENC[AES256_GCM,data:YOu+/P1aI2Lz4mdLcFvbbczxCO39CaYvOHXuLndJgKWinxlEOJ+QnFh2orKZaEL0+2URfHpsyVa5hDvDNyEEWmUuQrpxchHacWzq2/ijoDhfcbxafmcM0ei2A4ZsDg7vfq3b+i9LLLi76EUmJRkE7UVw53jnAr9K9/Qnyv1jGHk=,iv:9tJYhtYYIwRjzvWcTlwCeMo2jbddq3aWyIBv+CxHw4o=,tag:3nvuCCwRCzKaS0n31WJdQg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
