jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:A06du2GwlFu3BDsMC9EJHEI=,iv:zg2S9ua4CwVi8GEOQY1CpDgpQRi89vESgjHLP09tjEE=,tag:n7fzHdLRfj9xPgmKj9beGQ==,type:str]
                client_secret: ENC[AES256_GCM,data:tYu97ZFtB35o0/wg0mv5AnJDdJBCbAF5L64ZSLj4DRq4HFpIUSFzXyjemQNmuV434uuy5JlTgwjOzWl9QkRqUQ==,iv:n487qF1xFy+P5UqkcqlCFjwO+jyFyuMmU2w8EiLhSJk=,tag:1HkQS0pm2KHTH2EX5ugObA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:hJ/kZc5RCkjxUqmcX4rgh6sgr+SA0Q8H8cmxg4/hb1rJVX2FCx1NiF3PKgkcMEp1BOA5ZGsshM4bJIgwFCrg,iv:nZg9Czqh4ewdHp5eGSWzRGkkHJkvO6wx3sU7tS4qugI=,tag:a+b2bE6S5rPnbBrpAw+6xw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:21Z"
          enc: CiQA67O9AH7nMZOo6hdhkzEfBfPS+U4S7vSG1El1vOVz/suOTcISSQDmhpq8f6SFZ507axtP6vrzSFCsvf4ufw0xUatKa9majeR5OBh/0SiMfCF+nXSN9m/82t/f1i7PEbPBXdXnfAO3KA2Qzv81POM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:24Z"
    mac: ENC[AES256_GCM,data:ZgrJxcLA8tSCACO8W5xiGflUbcJFLlCImIvlQ9GO7WRc9tRPFsPWRRRdaHj0DUmMa3ydNsyLb/wNOzjT8ZbhH21fgbUMWxvWjkJGPWFg71h4QqevfriyrPOgQ3+LiuajDrSEJETgrQ+5YdBO8EQHz5MSbbSbeJfgdyvD+5MHKqM=,iv:pK26V9wVoLRLWxU8thFEC6mm5alEDF/ehwUrWjYK6+0=,tag:GWedvHxvh+fMezxOKKxMpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
