jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:8PV3Mx23RQifz75QJ5HTAmU=,iv:4ECbRSeCKdLHQTwjBJV9vL/AlFeer1kuWJKTWqRgvkQ=,tag:m0V430suVFfHduBYlwqeiQ==,type:str]
                client_secret: ENC[AES256_GCM,data:NIOrOD+jJ5wTUg3pJt6s0kgq9vEONDZhVIvvLgutW/+6nwyPGp7J/TLHbWHBxgQZQYfoVldGxu5xeP4pm+t4gw==,iv:hA0aRUsCL9aGJFzsNng5Y9nCdYI4Ib2bgqIsSepFAi0=,tag:7ejBecYSx5yNlnI+JMJzbA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:a/L83EfXpEcUu3JXojH9Lm/PxLGDt8ntveH6G3Cb7WIalZEO78LPpyHAyCFbjqpoDKCHgRKSSGQjA6C+84Ik,iv:AfJJwyDmwxcgMo8YhcyvAQ7PQDekVbUY2XU8AOsHm1M=,tag:6HNHubLqNqHJ4D6Pop4fUg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:01Z"
          enc: CiQA67O9AFo08YZMZBLJtudBWKufr6N25KZLIkqNg6lPMFnIbLoSSQDmhpq88aJ0ZuivNWHzmg0sGY6TZtsivrPLPGLte8c5sHwSqwST/c4UzsRaAetzLpyWOUEqnmJRC+Mq6Kk4KTIvkr/QJl76P/U=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T22:55:01Z"
    mac: ENC[AES256_GCM,data:S/wfgatQI4yWXlNd7vBXInuUrX/mJFSy7ZCvSPUybaOc+R2BtXjwiOGf3O0pbSLguxfAd99al03ej0l5YhWcfW8CMIkkNVSP1HxsXtFKu30A2BFtG23iUjq8crgARVddNT9joISi3/hAsMwy4UeoDHS/86qKsNbaxe1ev+JvvfQ=,iv:66hX751KIJTd5fdWe5M7q+xyiURg91ZcOMIlscO0o5s=,tag:pDqoCcS2F6fJbOncNqo4Wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
