jupyterhub:
  hub:
    cookieSecret: aaa60bbfd8427c23c2547ff5aff67decdf0f6eb64b72060d06f386929d42b95d
  proxy:
    secretToken: 8138380237f8caabda48be6b140d1ba1d42d02193522327259993097168d7bbc

  auth:
    state:
      enabled: True
      cryptoKey: 7e78c18596c527bccd6f4579b9790dfa4d3fff493f0f172a461e706cb8f7708a
    google:
      # Fill in as needed
      clientId: 639319454093-3dsbfa1qe5a5p12j2a5vjn8miuqcomco.apps.googleusercontent.com
      clientSecret: 5gYamLWb3WcDjoSsHGaSlwrS
      callbackUrl: "https://stat159-staging.datahub.berkeley.edu/hub/oauth_callback"
      loginService: "Calnet ID"
