channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - pip==20.2.*
  - matplotlib==3.4.2
  - pandas==1.3.2
  - scipy==1.7.3
  - numpy==1.22.3


  # Visual Studio Code!
  - jupyter-vscode-proxy

  - pip:
    - nbforms==0.5.1
    - datascience==0.17.0
# For grading
    - git+https://github.com/ucbds-infra/Gofer-Grader.git@dbf3500
    - gofer-submit==0.4
    - -r infra-requirements.txt
