nfsMounter:
  enabled: false

nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver1
    shareName: export/pool0/homes

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/node-purpose=core
  hub:
    nodeSelector:
      hub.jupyter.org/node-purpose=core
  proxy:
    nodeSelector:
      hub.jupyter.org/node-purpose=core
  auth:
    type: lti
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          # List of other admin users

  singleuser:
    nodeSelector:
      cloud.google.com/gke-nodepool: user-pool
    initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: home
          mountPath: /home/jovyan
          subPath: "_bcourses/{username}"
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "_bcourses/{username}"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/bcourses-user-image
