jupyterhub:
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      # make the IP static in google cloud console so we won't lose it
      # then specify it here so if we redeploy we get the same stuff
      loadBalancerIP: 35.225.96.130
    https:
      hosts:
        - bcourses-staging.datahub.berkeley.edu