jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:BFN1nblbWZzrhdagUWvjfuKQpWwJ2wPnGy0064alJkyzeA03dKR0ftKKP8zYMbLH0iNAo42R7W4RlasnB0ZfNw==,iv:1gKc0hsUhK+/YFSw19tv+ip2EoD1zr1tDDHJk6QQCUU=,tag:bwm5h1qPuUA9PfHjYUhkqA==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:92lfgIB9Aw9wt3o9vLXvWlRPrtpZxGWbSLmVRqyZpVFnVs/1+RgOulLtYqPfjls0HNa/HZy8hYi8Grx8SJXjyA==,iv:SvOQpIBQuOxIBCx3Sp8DhAqlg5dqGOiWui884oSeuYo=,tag:ntFhwp/4TORFCUTbj4qCNQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9AKrFHE73yXBNTYBsGFdavSZtHi25vOM2zJ6w10aF8xcSSQDmhpq8BtfIDNAQ5cxPEQU9WRgdRZZiloOSdJbhdh6Dm7BleCrHANVf+CjpfcJp/Cuz5VI6YGLqjX+3AGqfuSWLxk4MJD6NE0g=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:50:07Z"
    mac: ENC[AES256_GCM,data:8YEoVgZyvaQBB35+jOHcqcKgNLxpfkoTUXkL7j6jIu7sUq4Se346tVnx6/vwnA0riD+fZhXz37o6xEu+rXOxnHvWp1k11QElvQ92b70wM6C52s8U+Fa0FrmGQBN9qt+PxC5K5MsBWJ2zJ6QC2b2PlO2yykah8993W+ihhnyNNH8=,iv:9p8K8bo5E64zXctxPGgCiiqP1jAJrBOjbaM7h0bmpNM=,tag:UOcBco0pXrpnDvHDcbasHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
