jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:qIQE8jUyd0Yfco4+rbF+7L8eSm+T75x1a8AAivvO48gfoJUERp0EhLaipnY4PUjRZ7OC72odOm5Mwen7TgUT2g==,iv:YZb+FoKd7qT7lVut/z1VMQIL38uJFBpSK8h8e6Jr++w=,tag:lz0iMTILDMRWWD362sXFpA==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:FvP/h/XvhZW8LQYF+i1z56A/W1dzn4qw4qQn0XlZ4ya8MywtVRkAE0svopoTm3gnzAM4OM1zhzsDXAH9Juh8iQ==,iv:r54KuYGQhwlPB+iFL6iQLJPb3WA830wGgJGkawcKIgQ=,tag:ngNw8U7RCXexBlbjh7+e/Q==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:r4mUtI6v/FJDD+URaeeAQQo=,iv:lJuWbRJ5FK65OFCNEiOkTgUgyd4IxuHDKpjMP5K8OqM=,tag:gvMBYTzC2sEEm/9ecoWjXQ==,type:str]
                client_secret: ENC[AES256_GCM,data:GHaJgf8F7bZhZYzg7iFppLGzoCvzcomCBBMF7BzyfzWkETloMjnUwkOUcoGAQr1S8fHuQEw9vFWMUhrRKf3KVA==,iv:Sy8He8fPPGS5kE4mvEMIbjKlhNQkJ41DMf6VZuGPFjE=,tag:uuAEOBJuP7J/6truj7NlYg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:aBPO9eLEJMtd1pDJKrugYXyy6wVeEkFFBvVwE6kPpVKUznuAOW1egD39MFQnIF1a20BDrQ==,iv:C65/RQ1CW7FtiNMj9Othq+P0L2MxIdzzlOXvl6YP2bU=,tag:xzR+W8nQKOR/22lik2Of8g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:01Z"
          enc: CiQA67O9AD9d8Mj3ipn5pyN5ynQME4wKeMYK2qiN8iWZHzRid1gSSQDmhpq8oVPlrWq6O0n647fb+tud2yQlqmVXa9i63DnuFshEp8idbeYZ/4TWHeTA4D2j0SZeHVINc4BtZXVNXeFYH6t2gL9qc3I=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:03Z"
    mac: ENC[AES256_GCM,data:vkOfMzUFeM+nZ994VGR//A4Vt1qj6hGBYla0d2OtTKcCEYiQDFfHyJwkn7Vdf86BtXuOj0RTQZiAexQ4B+qy1abl/ZiO2EF40NaFUloDzbfb8x7m8YAKf8WjU8wOaedwAmGippmsxU0suo/VpxpoJzwyW1998bMYvcKMfovGJVE=,iv:4lFGzdQGd9RWdVP/CZULmaBvJAfuOvzXGq1SnEb4vKU=,tag:HMQu8iflab6W5pO36nT6vQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
