jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:UN1UvoXXDDbLji19ZGrGEgAfGT0zBOm14FW6/JxGbTl/j5Bppd1izlg2PWNIIOFS6bErAq7+yPkrKiqYIJmWOQ==,iv:OWWchiRPJlhNJnmNItnZo97/Vx5Fzi1hvJ8s8CQr2v8=,tag:d3TAl73fhs7Qlchuk4ufHQ==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:ibDEFTZqEevTqIt4Ju0ChSD277wnYTpV5pBBw6htXMc6HaovG4iNg/zJ7Ue5uZD1UQxYl4n2SwLncJnkYmWIVg==,iv:5vSNPOIgoKNW4I/OHYqZ6v/uUYpOULe216I4N/eqeZc=,tag:7Ntu06dQwKPZ9pf4uOkHUw==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:ynG0PaOTv1Bi2yUjp0Xp0CY=,iv:XZ3of0a1C9TPpfgtpwFxWp5L8V0efxDBvrkl5BMAkuQ=,tag:D8Yt5U+2HxZPLAU8MwaoFw==,type:str]
                client_secret: ENC[AES256_GCM,data:pPv3lRvTTv+LYNKgcZ4ZA0h2T0iih/tBHh23pl3/VBpz2fWY3AJSsQjOIq23fhWdCsM0V7Ldl4gJ5scR2SRqpQ==,iv:i80JAB2uwzh51IWbO/paHaWxu+zSiBrE6NboEZjgNLQ=,tag:hO8dCSr6W4T3YoXj7IDq8A==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:wtm9ur9uIKduw0x+QtQ6aB6uCQkuaxETZ9J4pdrit5rQ/kpRhko1cKrORKcaqQU2KLe+fQ==,iv:MPNIaAHvI0i4oboy7HxgKkr8IpwQ+jDERPLDe9WThVM=,tag:HXmQkeyLE0/5LYRj9xKNXw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:15Z"
          enc: CiQA67O9AJH91+PUk3LhLYF9xG8sBETajWNW4x9LSUTbh4nHKR0SSQDmhpq86CJ6QBmOxn7uOZkyKyAptvG9cOJX7UNqkJdVnOwrDWGXhbvhi2O4G6MgdHVRbtB69lrkgB2A6V9n9FNNpfhg3wyVf2E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:17Z"
    mac: ENC[AES256_GCM,data:I3DjqOsis1j/2lzkyiidyTQSA7x70i+47aO1amMaZKz6yQkYRwSFFV1q2LYek6ADzEKTXmGQ4mDvF9+NkiHmjBXsAK/sqV3TPBcyqYGrOl2ZATpEjD9McF/MckvaHxzy7cHPZR/wB44InQNnIuct2yQ1khmThTRODFhVQa8esRU=,iv:cFBKCcQHmS2w2ije44e7qUZ7spOUNfr5WTKpubaYCjg=,tag:e45l7rwxoh0WZ4M35r2siA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
