jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:7R+E5B6aVP1C5afgHL5pHnc=,iv:xgPS+6gB7yhBcdHl5TfS6ohstmgDc9YUnWzf6wYKceQ=,tag:qIIZvbBdkEySXuvsBM61Pg==,type:str]
                client_secret: ENC[AES256_GCM,data:Vmz+pWKZ5M54yTd2fYe4ivD8n3YrtcPy2sdE3amqzPWYsv6vkD1CKUhJ/RciNKrU4teXx2whh2B0FB8eAccoFg==,iv:enAJwMR4el4fbT4adOcgPK6sIXPN3Cb76SXJKoxDluU=,tag:J2m7UP7XLWho1fmEGIZYPw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:l1DnFaOJ51ffH7M/Un9aFFOW6bFwxd0f8ilF/AcHv9Xb5S+XXl5snZg76tDCxC3RszbL/P4nqw9nWSZH,iv:4tA+9F75YGuch0ah2xups0JWzy7UzFzSoqpni7FQLKU=,tag:/iJCEt7vRxvlpj80uUdJ7g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9APoLwIJnJjVDMGdp5eJXWK62vVkZL4wnZ34cjQ1VmzQSSQDmhpq8WE/zFmStIuU+bEtkG3pMwvD3bDrydLBkffIVL2SZcVcBCIPG//I7IIQmliLP4rwckIJ9/OIw87gcyjCdEX+vaJ3YFn0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T22:55:57Z"
    mac: ENC[AES256_GCM,data:yUm3gvStq59orsq+xnmLLZdFWfORMoz/eaur1ZzZ5F4bFqxhXksVwCjLDAfaCW0aXmp/Vu9MsKsDAAYzibM8AaV18o0wQQvxpeC0In+WJQBbIGNJstvwBmX6dYlUQujlK8BCtyXy9JgUU6yjZBkGIohi71EJ+zY0QguSX0HPq5Y=,iv:vXIX0tFSU6tvGpH75mO69Ip2OyjOzoyc8Bi/BJT7cGY=,tag:O1+UKJ2KlmSX5fyGqweLhw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
