jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:yS11RI/vRpQsQF8YTjRmCzA=,iv:G/gpnpRCXKZT6JhCbZDk7jDqCly6XHnAL+n8kgcpzfY=,tag:CUMC8m17twG4hCASFQhbZg==,type:str]
                client_secret: ENC[AES256_GCM,data:uBGBz66LnoABIppQRpteUsxsGBHy1+ZUGdexbV+t3332VoRi9XyAHbyil0aFP/pQlglbdzgDGhDknes/mUnGyA==,iv:aKgDrCtBX8BS2PlaBTxrAHBY/tPhcU/jaWn6mCxpwqc=,tag:REpylfzxZWyE6pswxpO67g==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:l1DnFaOJ51ffH7M/Un9aFFOW6bFwxd0f8ilF/AcHv9Xb5S+XXl5snZg76tDCxC3RszbL/P4nqw9nWSZH,iv:4tA+9F75YGuch0ah2xups0JWzy7UzFzSoqpni7FQLKU=,tag:/iJCEt7vRxvlpj80uUdJ7g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9APoLwIJnJjVDMGdp5eJXWK62vVkZL4wnZ34cjQ1VmzQSSQDmhpq8WE/zFmStIuU+bEtkG3pMwvD3bDrydLBkffIVL2SZcVcBCIPG//I7IIQmliLP4rwckIJ9/OIw87gcyjCdEX+vaJ3YFn0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:57:58Z"
    mac: ENC[AES256_GCM,data:1Rvp09/qdJ8YGt2zlQLzA/BFKYLV+rsjssL4s5/rZ6S02kCEyRSZljmNtTmGP/VsvPXRS0DdFCvZx2huFK6oQKEvCc3xQsDx52cmwKVHxuv7gFZpkk0Ps96wS2e02ppCfWvavylLKEZSpUusSTg0JDG9tiR3pm8XMAuDhc6lwMg=,iv:Wrpnx4LtECha99TseeOQYy0PjnPQx1vnflaBo+T5nsw=,tag:SOFF62gjfUmlFEghD4BxUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
