jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:L7EnJc643PnVx70ALpmuabE=,iv:eNp+6hl/b1MjlkXWy3dUhfEBUvRp5oVVnv3dHoDErf4=,tag:01cqpBBpKcqobvHGqkyyww==,type:str]
                client_secret: ENC[AES256_GCM,data:/acL+jJT4/8A0MTA7Q6LkRbI8Ap26fSnnPGuZCoNHlh6pPY9IsutneT1X9L7xH6Y3vAj5tMuULJI9CoThXexKQ==,iv:ILgoexZuEnRF/Fp28U3DlWA3Q5MDKST68UmYIwVEU18=,tag:kSz24HufCGJGhKt7rjumhg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:LQsZTU74pFypBLTKpvh3MiBMyJ0PcHXmousKBY/IfxJeSycHmVzsb/S+Zf9DgFo5VEG2PzDmhW67ahHc,iv:zjHUoobVIIncQKx2VoJ+rQJBQ2DAVkUb0yAhFHp/phE=,tag:NXxpVkjuG6w6GFdMMfXbTA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:15Z"
          enc: CiQA67O9AC14DuOiHmeI9tofNUwrXsjBha2HHaD5uz4cvWcSDHASSADmhpq8FX75TJW1CAcZpfC/5pxrD7a8dAtmK1RaInian9H/I8N3jM43Z/FIVzrDMAk4pFV904Z7dzWirW493s7fPxaNqi8S6g==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:17Z"
    mac: ENC[AES256_GCM,data:+4YVT7xtv/BXth6EMKDFK/sO+8UPZ07TJS0vKiAFrvryjQO5pshKA3y/2+aBrMriA47MEom14XxI1qGz1bzg4Oz/aREcoLaaC2LxlvMfy3Mw89oPOUvcBWXHTQMLwW+giXNm1YcPoV8Emedz7Ss7HvQleMp2vJHqE0sgZAMEm4E=,iv:C1QBZ1c4jCsVVabPKPBQjyD7yDKmWi7J0KBCNAzKFho=,tag:rjHkXSg95ULiJUcUQ/g2cQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
