jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:o+0d0lDMvjBtvCaSQPwUIgHy3XSeZYfLbRSRzm0n6Mr0IK0QTwXT9BM2PJjhULJ9M1keCfQRWxybxOQxYkMYLQ==,iv:YBtclCCFSzi7WDNWEoMUnoYYecPMnKt1TAlOUWDa5gg=,tag:aUOxgzv4EL5FHsfOR1Ro1g==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:kE3hWwCNLHHL+wqkC/az4e/KhDRJJAuWBH8zFiqtuulobNR7iPWmeRXyaBisiltjwTef0pma1+bXxkS/wggkMw==,iv:CgHfwRGu+TDCbPgETTf2LwQI+PVuuKNo0ekk7YkFF70=,tag:Tyq4Wjv7RBRSUdhLmoj/PA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9APoLwIJnJjVDMGdp5eJXWK62vVkZL4wnZ34cjQ1VmzQSSQDmhpq8WE/zFmStIuU+bEtkG3pMwvD3bDrydLBkffIVL2SZcVcBCIPG//I7IIQmliLP4rwckIJ9/OIw87gcyjCdEX+vaJ3YFn0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:49:44Z"
    mac: ENC[AES256_GCM,data:0NKCv6Z+DyCvpNL5arkPV9QV9Y57mQQfwdj/NyJ8eWxUfxTHghSjw5TEYJsOKNADGDdoGdIIV4Y2D0OSyapEIlL+Qy5L4juXfXX4ixvKXWK6XK/+kxsi/B91MY+aCqwKXRb6yoLnDe+3igJdhyZeSXHl8vje2hEI7hIdr4oGAJo=,iv:2D6gj2dAFgT4zVVqvqsYdFkqM7W3j8ROAZBAapANNHM=,tag:kBrU90/BR7Kgig+Rw7gveg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
