jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:/l1hl8SmoXZlcpX/yHraSupCRFG2FTuYKYLWf9U+HQsO6j9IsdSNXvJlORLrgSWo+7qs+aTEaYDGSCVOmM/u6g==,iv:ZXGiKAojbu7XAajuHbV0RQcbmbMLfBDu/3Cu/bOmnbc=,tag:ZeulsfSnwJ7wMazltDVJOw==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:tgMT3a3Wd8WFqLlmhFNTpCCX3Sw8FdeisIw3xBbkQr5gK1kQig3iczF95+xUGjbTbp2pau3EmJL4AY30S9Vl8A==,iv:KRd1umi+WSsYp7evoj3JrRYNS83IW5Rh5gZiSt5MOOo=,tag:Rz1/GW785/zywm/tYRu28g==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:UNxDu6Wovh03xpakOboyo2A=,iv:8iHklgEVG83pxSiIrRLzXPxc4u4sXiIrsLPldwRTWgA=,tag:ZdCC+V7/Lt26/CW5TVw8fg==,type:str]
                client_secret: ENC[AES256_GCM,data:++FDrfkWApqH2/0btxJgOBc+9xGFixo6huwL0nRgxzHEgJ23UeokYrRib1fqNhJMl2KGyJBanVArwI/GqE+6YA==,iv:ULR1Ww0RRYiNlPV+lj09hBBcd9cZOpfrxEQFIDiwfJo=,tag:CIia+MJfap+WzPbwCNlN/w==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:nUnTnlnrznOaqkJUSmKLRSjubiRPZdNrVwXyeF5nDWEeYVUOVYhTuULkEhCtvytZ+LiKTgzXlN9RIW7K,iv:wsYYTd6mZaq3SeflFDIRz8hQHeihuPoU1PAK0OmLCEQ=,tag:xt+zsm/SNLrO2fJDX8YvwA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:01Z"
          enc: CiQA67O9AGHDYEEgGl9tSVHwdMCJARCCsNYrfdf5epJma80DlU0SSQDmhpq8q51zgZvyJTNAzsk0GdziPYqprPla9NS9xLw/W5xDmCMkxPYxhI2BDVzBnBaJp9X9LXP4/m+ujRpG5uy4IDplebGeIwg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:04Z"
    mac: ENC[AES256_GCM,data:ttaCaT8YoUwYTtGZqB/ZklfFrMTOAzIIjmdio40+KYA7HQkVzCHOxdja8KP8n94oYEShGoInD4xOpWt2viQ81joTYkKXveiUJ2sXXfDMAwXsz/mgA91tUctPCH8rgYSFK6DHh7yn5L0r4wCFwQe0KCwcNuhtdAli4pu+yYA3jXk=,iv:KCsVrbGOLFMvSEdZZsfCuR057wirjE+fXQyI0tUiFAg=,tag:fKsZhGPFuh3K9GoVsKc76A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
