nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    config:
      JupyterHub:
        authenticator_class: generic-oauth
      GenericOAuthenticator:
        login_service: bCourses
        basic_auth: false
        username_key: name
      Authenticator:
        admin_users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users
          - dhughes  # https://github.com/berkeley-dsep-infra/datahub/issues/2462

  singleuser:
    defaultUrl: /rstudio/auth-sign-in?appUrl=%2F
    extraEnv:
      RSESSION_PROXY_RSTUDIO_1_4: "1"
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
