jupyterhub:
  proxy:
    service:
      loadBalancerIP: 34.67.132.203
    https:
      hosts:
        - canvas-test.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi