jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:NPgJlqlVomROmW4PLRE0WEAhDmiLJwzpqtFmpgjQz9ZjUTDw406SdsBgvGgwsiwb+ECJU1jaTf4Cdn0IvrHkHA==,iv:MJ4e5+lA31eeTGv43L9ZzdCL0hVHjrfzihrhesLYGKw=,tag:A9nCj2glEteqY/ebtQ+MLA==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:OwHrvy9uC4c6dHuZMO1vdZOTEYJHOmzQ7o9o2Zms5MibGtWf14Dx5GVMZQdOVe8tAfTQ8mDVpdfAdylPu2Nmzw==,iv:O+Yc2oRTrqoxWe1vTnbeEMLNvrQ+sfW0dcP4exd5R0o=,tag:Yyfp6y6fjelCLcjHFE2LYQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:01Z"
          enc: CiQA67O9ADLXZYKuccVHLgrso5dL3wrNikJBnDWoGHRnFKr0eTUSSQDmhpq8EwTsMIJwdzvjsvqiZGPUUnH+JtDg8NrJhdcq4YCyN2TBrN+wF+Fudy6o6DCvaBBlQL0wlCoF46PlamxKtNclAzvxfPc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:50:53Z"
    mac: ENC[AES256_GCM,data:2BsW9XeNAEff5BtU0tyvrcKcwifUeQJYnSIGlcngseROIwDXcAOX62z/IP9DggCFv6zvxK3Od5xKoCLenMZrVkVODCv9PmlWHnD3nHmQu2qxsh3O4wABj7TIhSrSVi9CXol3pVayG5VbffBWLGYheHk3uCg4OAh+dXI1zqIG6DY=,iv:o/PjztkBOiI3IkCkwOIi3QwIUQO3+kwXXKF6s9QRY04=,tag:K2yrdOYtk6K3FYLfCC+QAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
