jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:/UJpQl51D31XGrZLyKcmWKtZAm0mD4ZtERXRi00YOhFUgwE6ViaejKqDD3kFiGPjE8YBNhdf9aH0RYI9l6Hnsw==,iv:EXgd/xuL9BYwGM7Qyn+w0q6FgDi4ZdPSMxuPBDVFS4k=,tag:TM3u1ODxyfdG2DJwVn1hQg==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:VtyhXmS/7zfvfuevrRAvD/E=,iv:V6xfhc7Lf27duLu+XaM76or/Pw+GMADR3NLcI1/xMsg=,tag:QYxMP5b9fJ2FAhZJxa63tQ==,type:str]
                client_secret: ENC[AES256_GCM,data:REf/tCNFXluVnJcxcmJMUlB+PoBJmMFs3qZnb2dY6PT9qRnWHqpS5FCaZhd5p9UGHv9MFUuB2A2eM3yYImFjhA==,iv:Z9fcBg4RP+C1ijEECXFMxq76IFmMYk1p8od70hP328k=,tag:7+aBE+IEL3DtSt6wHDQfTQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:juC61dxUFI6xjFSWvpipFDGVB7kZ9NQ2/JsOre1awZlvAELDN/f7ZYSBZUHYwth370b7rKM=,iv:hGAo94WjlUeI0Q129c4Cd0xSW/WtPhzTTT9ng7wa3fY=,tag:Jd6tdRlsdh2k8KB5F3pEHg==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:Q+FgVvicjRGvNW2PczJLdNR4N6M8a8gOaFG279BMoK5w9EYN6FJkg4OrsHOl5JMhwNH1fuT+RxMcadQKTlCZkg==,iv:+meMHRQAsUukmtR3EyglH81eSPyxA4GBx5aK3e9tr1w=,tag:wIoI2gddG3hpqrti0MUSvA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:21Z"
          enc: CiQA67O9AF6cx3jPQApHNfuQWIs3brfCkt2ZxBZbZy7ifHhH/vESSQDmhpq8WL/W9V4HE5Ss8OQLdzFAgXeevHjvC6mLk3f/9xoxyyDfj0H6iKB9BFZXiemyp5fE6F4s4K/g3zqoXLo7wKHG3nMZ3U4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:24Z"
    mac: ENC[AES256_GCM,data:yfktbKKC2RMf47QeGJMyxXkmFf8mzPSCSlj7QUbaXcqUsAYAunSukvn6qfbdyBljW6I/TQo2rmAZDHyhZvT/jT+IwyDCSwYEhkyUEo8ZEFbUdNfeLtIv1hOKdqAy0DeqahsWnYeyJkVwczDP8axGtrzzBdlPudXVrYHeFvByaaM=,iv:8LJVQjEri8KJa517fAGjy45ar4Dj+8ceYMn7inBfuSk=,tag:aergHnSLEijfnaEDNenazg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
