jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:kIAPpFQWHNQh6ukxNUlP+AI=,iv:VDV8XQRatDl7K3bA8O/Diqjimag2u31+DyQfebqyF8Y=,tag:ww7u2zMTLt+3d5mbQ349jw==,type:str]
                client_secret: ENC[AES256_GCM,data:U5LMJh94EONnLFoLLsoqIf2U40uhq93BJ2zOQ3aDPJAKJJrGbFDKgqJWzSztNABq8PXmnMiRlhDTvsjTfmbRew==,iv:3CME05Ed7b/YdQQzSaMmZdyxIoIwoN8+Wh+IMxvlQdI=,tag:B79p7z9WO2OP5I2k6TldVw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:dZLF7cbAC0YMowWVo1nsshOJUy688wk2V2ic1nDwlEIWFq/Dg8okYIDQ7iSXy8+sG+sGMbs=,iv:+gwfcoopoe0xZrYJN3dP9sYS513DMroNvZCGw6HjOlk=,tag:7fyCNaxuA7SY64W9NcoaGw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:01Z"
          enc: CiQA67O9ADLXZYKuccVHLgrso5dL3wrNikJBnDWoGHRnFKr0eTUSSQDmhpq8EwTsMIJwdzvjsvqiZGPUUnH+JtDg8NrJhdcq4YCyN2TBrN+wF+Fudy6o6DCvaBBlQL0wlCoF46PlamxKtNclAzvxfPc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:04Z"
    mac: ENC[AES256_GCM,data:veeTjesAwmdEnE3eL0jJDZXnn+pcuCFopoKRkbCIwFJ4DeqIhOr4nzsonQSq1WADn+p8yyNEdIMWh0B8YTE0qSyWmVdlkF2vONXALRy9ty9xPrDCybva7ONGiGgb61Nx4wflz7w4iePS15zRapqx7rK7TgymSMcCiI8xDDh+xyc=,iv:gMaqX3Ul0JuI6ZfxfgqRKpJCZKBW7cHi5o5WirWyjYE=,tag:E6Qqdv2VOwrFgoMhMYs/mQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
