jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:XgOULJzJ9C0R3CAUe2quZN1EKUyLojSuhjlbrx0482zdK2UhlhvEqzShpJ+/sDL3kUTLNXcz1+SiwhKw9BepXg==,iv:R6K4zMODwhtw3GCJLRyfEhG7NNmUjSz30pPedbiFoYQ=,tag:reHdhH1awmEiLhYxjhYi+g==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:crBMxyjt/yh0pJ9Nvnfc2/A=,iv:pKpUcDKKIwYz2YcfbZQHILcprRXT7ngiwGO6LIbCiz0=,tag:tzRupaJuPFQfD2+KOkUpag==,type:str]
                client_secret: ENC[AES256_GCM,data:FwX6NJtxVnZMv/iW59jLq461ynmYGt8wWwWN2ET/ZIkKeYBTcKDHBMbwm9LzQPxqlrLdCN1g1drIl3LB1fipKQ==,iv:CN2dXW/21htSqaydZDI+iamuJCkrbNUfu3THElW9EX4=,tag:u9FBXpzcEeD91PZkuunJ1A==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:s54yS3YIZG7bOngT8TyYra0W2ThK7yU+4qa3uldGeYLXgoh9wNA2nMRnZjgp0Ep5jXEOpUY=,iv:3nBxY3UAadGyA8JCd9OO+tP1mFG1fi/3vJEl4fLfu5Y=,tag:YmMyqgYnRanj/a8Rfhn8Ww==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:tcp8HFW5pZs/z/SjJLxajrAvlc/L42SBouK7t+R2QWW4rdvTdHkoVpGoDo5Nw/f3JfqnxRpZC8qXBKq76nA1+g==,iv:n+b3XIEEEm1hAAFSfGUTmVuAh053IWc/YLg4/tiAiqY=,tag:rmvXy4QjRXuarH3D/NaeQw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:06Z"
          enc: CiQA67O9AHa9b53QdCksPPj3F+g04jhe8iDmfVs1CnpAN6NrKaASSQDmhpq88p9pSHCEXOU/29iABfMqVt4xuFL64WE+qoRVrxDafuL1sI2ac0Zq3cbDtkg91xS4fBha7SStCCF6n/qI33LiQRQQExU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:07Z"
    mac: ENC[AES256_GCM,data:fsNr/9fZl76DqguHMz3VBYBLYZs9IBFT5EAgf+Z3rMnq+WxEStzdg88FHhVI5um9ouUa3XcOqFNyu6/MAIQ0CqF57DRrd1gJ0K4XV+4A75mCCI02G0nTAUMQC2i4PqB4OUT5dQF1Sp/7wjfpxVofAe7rlzALDI5aTpCs+mDiltw=,iv:AWOByvh6bQ0QDTWDNZAXtjvsAd316AHIjlX0FYkTa8A=,tag:7+srlc2NtGDlHDoWyQhjuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
