jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:2fK8y7zG/q7fWH7OStycXoJ393zm5Axlw75tuJ3kATlcmU0Hvyz6crP2Rz9VxV3CugrDNFT74GI/u5DpBbNFUg==,iv:siIb85Pxc/Fuon6bGSGovJaX8p8Pb4A5nOUsQ2UEDao=,tag:NGXiTHRRlbGOGiYS9I6lhA==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:G/c69TRFD9mCY1eHs2Wn40pQfVOJRo8BnNN7fWBd+ltaR2xm4tsGQrhknM7Y3nQIVXDyKp/DMxxihp2+l2IqvA==,iv:WfkZVIBVuTTgngriwbm4y6BH8EAVG4GNMhjGJSUNmuY=,tag:0b6fUk/6wNJIiknz27Ae4g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:01Z"
          enc: CiQA67O9ANm71jTsRvvkqiySLAjjjn4roVDZEuTM6vC4180Cdl8SSQDmhpq8KUx0ALQUY90z7xNI47SOGZE7Z/sxQkMBFVvjkpsToDaJTQrQk2GdETFbrWRXvEUZLYv+y57bzoTjbwLU3brRIDkTfoo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:50:30Z"
    mac: ENC[AES256_GCM,data:DSyFzvVPiYUCUqEta3Hn2PSJYveSd31hcEoIwmz4Ls3eD6TLUPoYFWirYCE2XkNjH4cI8ybiHrVTjbl/kiY0gYGX+nmSJnAqCBQGcwo+oBotE4W/SDRBN/C7KMZL5L0Iu7yeJI70gAOLo1lpyGO772PVcZTWlaeOAIB1cRBkTDk=,iv:7y3eUJ58vufDr05ezCCDPoc1/gZHcTOGEieXY7oAgXA=,tag:48os6F8Wveoaam1x/lPOaw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
