jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:RaMUFt0ry7IrNdzroBrO1h4=,iv:tQPDEc1zWaCQ9hqyluDP0jRiKZJOblb8IZi3iFlt8+E=,tag:Cae5CA6yPYc4rHg2I88AJQ==,type:str]
                client_secret: ENC[AES256_GCM,data:A5o7s8ArU1giLFZTWMV8cQ0doMchv3jkDUap5sG6ILhPnY/Jc+0mHiKMChj43UlOpsoRQtAAgG+lJsRmCBRmZQ==,iv:oSjwM0C2vUB9Jg8RVopYMythzj/nN6KFWsGgG8hIy2c=,tag:380csxBf99/SQihzKBTZtw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:WNmnAEOZUMdAsMHVM9GQsuVdKYqh3GOATCMsi0rPqfrYco9v2OPNZtF2oTsmbLQ5OrhPt/g/w5YD1QZ9vQ==,iv:EEIQkqvDjxauft/fEluZ+M4jvyr5YMJAEPPk4EQAKUU=,tag:7Fchaxa0A76BBeBY99AWfQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:20Z"
          enc: CiQA67O9AMpJOJ9CoVspiKaI/1jubS6XMTS6qiWaxmr62BTnPZESSQDmhpq8RiT0G8Ei5G2qI9CIcn/CwcC5e5bS0+S2z26206eGSB2Ih9gsQi9FRdMxqk/0ee0fnFfGS6xR2iWlqRqb9F7NTypBTj0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:22Z"
    mac: ENC[AES256_GCM,data:5WReqJvvsy9UqRGHrIeES15h3s4UbukhtxnDFtmYEXvz0v6FOlwnuey1rxFri9gS/smo7iK6JUyATEGEp8DbrEghHtp/OO6o7DBcki0vS1n+7DgPt9LH961vFoiGVg9snWkRxUbIGWsbmZimUc6cuuowhhZAExXOtH4KrGnl+S0=,iv:n/Zt8TMUg6UtbuLyNrKS/Rm177OwBt6g/cetJUmcJp0=,tag:UR/KhahW9ivhyrCQ7ucbMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
