jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:Mcxvjf6TLLJPIa7xSISxd8mzm3+COlf+6RtKRjY53vnrmP2jVaDkkauZBxX5SVVG2Flkq8mTJH5DWjV4DcYiBg==,iv:/usOtJlVNmFKWIuSIH9jjapfx6tQE5Hol4kndNRoSJQ=,tag:AXXO88VdxudoQX3v+LXkFw==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:m7qdPz3ThCIECA7RfaiFmTQ=,iv:rEYHLKtISK33yffnrHwQSfHC6eszkMbQuXCu4ggwIhk=,tag:obXwC3W+HvQC2PwhnW9PXA==,type:str]
                client_secret: ENC[AES256_GCM,data:vjnEoB3WYaAmchzoOKiA2Ym9ZZ0EScCQFgsKrJumwKv+HIGo62FfsYs6O0q5HNlXMm7tqBYnSWq9c6BNt/ZlWw==,iv:5WQYqK8RpqqOOZrTcWv1P5RgZlhr20aqN8pnKzenhXM=,tag:r8DrT/87lX5LB11GLGvR4g==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:uVf8Vr/Mp52HCVfpWZ7l07xUhfS3jQs611iMabprBU9BC1II7SdjD8tjCe25674E8L5LER1Q9XVTmFcmMg==,iv:VKLnyyDYklJs07SP7hUhMu/L9mgzWVh5MTJIQOS7tro=,tag:z/fZvgMBH8zRD1zHVO8BGw==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:psPc26CcZ2HRuhnvwHFG3eFFxJ3M1btWkS+BH2GRFFMd8nrkMHpKC1yFGYAvxyEFnu0HJVgGqeX05I+1e5CClw==,iv:UDuRu7L92SESqIDvXXl7JJ2lxe+tJHO+YDOAWjAkBk4=,tag:OjJKAk0aYvwbNti7zJkODA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:06Z"
          enc: CiQA67O9APApkdFWvo9CbTHxJA7OAOMViclPBjI4C+55PN5pnikSSQDmhpq8SGMZG7ytJthavFO9GZ2ynyd+Ozw1eS8aVHcigGI83PgGCOZVehkL4V/qAz9eq/3eejgkcXOOYll7SXBLZrz9HPBL7/w=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:07Z"
    mac: ENC[AES256_GCM,data:IuDU55W5wZfLD7lcmdQX16X7pIummPorr3QXnGlFTuPcba6b/EEDv3ihn4Zm4NmTA14tzb75EtXKBr6GKn3nHZHuC/P/9uyJUBCPL5394VuQbjr8R+MBJ5g/bv0zd7aMkV1qut6iNs4VaaWAqLUmkdLOc474EUh++LBGhNGrkEQ=,iv:QGJvjbeYyvZanFGUdLMyhRSVpNSAbB2493/wNCC1E8g=,tag:I9+LJ529rh6GFQyh05KkKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
