jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                #ENC[AES256_GCM,data:sBMKBBsYY6+w7jrBmLYJ8CQQ,iv:aySglNCXFXuRWjOm/hiAqoGTYjatZ/wtLI4li/KT1m0=,tag:IH2VLC+ENxej7CioyOzOIA==,type:comment]
                client_id: ENC[AES256_GCM,data:K9WjzjIYOc7N1mDSDLBuHnxNFSAspLgdVc9CRDKmX+aycM75yGQ1o1yUwR1iwlOiA5jtQLKUj6CU5S3KnhNqJF3VYvo6cBUJ,iv:kdYpEGIt4Yx2DQcZV1Qz+c8JpOAf+jIoAdYeelo8/Tw=,tag:O6tfLmK+qr2tKwRSUYRwmA==,type:str]
                client_secret: ENC[AES256_GCM,data:gUEFAKC8X+RylZ8JmcE7hNKBWN0/BpsD,iv:x+tcwiCnZ8d9XmBXh1rLJX/dzEZlayP6Y0NqNVj2Itw=,tag:BBAqUIFUrxS/bGKqtQrILg==,type:str]
                callback_url: ENC[AES256_GCM,data:PvREPgjBsbqkcJ1nf95INVxQaUbLuPJTGtQeb6mAaKlHK05yqSZtfQx1dOjSiGUB0bAdcE8sjg==,iv:FXJwrBa8UbfFVLlb+URdiDi953nyiEmLlW82lchGmRE=,tag:DrZebdxzw/8vYJkGFOADfw==,type:str]
                login_dervice: ENC[AES256_GCM,data:wQfyWLhkJl45,iv:WPPHP6ESOSgCul6c6mTX/B14/ikTmMS/a0VeocxyD3s=,tag:1fwGN4KUHnCnxUYGrR8UKg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:02Z"
          enc: CiQA67O9AIhxkOUY0NkVFdEyp/NPwioBhbFATOFY2flJpcJLWcMSSQDmhpq8RkIBR3VD+pHYmQMVgK/982Sgnu3a3nO44IoBNAHqIzzaE7qLqOFIPk1XtmMwXafGYNyh3FVzlUrsRysZ3ah2r1QVEwo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:05Z"
    mac: ENC[AES256_GCM,data:LYnIjnWeuIH5NFEmPH7hN0oOQPSzcSrVq7RGgZV6Rum3eTkACS5/vT1EZvMNKMjMpYKED4xmXXrkX2SA0kxLxQsNkYVJlXqQXNGAGC7RRaUJcyWYc2rsUnOLpaSwH0capxfHCrR8QYFD/o2tBbYTQx/tclYIVIVjlYgsgATh0YI=,iv:txkEt7B3UOE4R2V3wCsu4bOLCSBhXdbzkEmBVKnkR50=,tag:9oJ3DU2OHS+WN9U9apOK0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
