jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:cLlXByQz2M7tkfqNB4Ox3g/nB97mRHONJE9pM8rogkehTMVWceoaxFYET0rcJQ3sRPAP0qCg3jLvlcbKThW1tQ==,iv:pzjYjWvKRvuLOpfCRez4XaZaFLWtN3cCzmo93ZXSm8k=,tag:tR0PF06y2WHCRKquOhi0rg==,type:str]
        config:
            GoogleOAuthenticator:
                #ENC[AES256_GCM,data:bjRAiA1ovr9+fizRzqkgc65U,iv:sPVd7KSyB3w4vEwx8IfCnaxXIOzTvh9l3+z94PmMjbU=,tag:VMT9NVnG184YLpMDzAaqnw==,type:comment]
                client_id: ENC[AES256_GCM,data:qy/C/F4jCQkPUvwfQ1Pxc/4xQLldW8nmJwPkOvLxHPPWCnpT1Kwvjbhnxi2ASS4TH6HFMzlqVYhpdR87xz4/oxJ2+MdU8SAo,iv:uZJB9QnWcyStbaJo0e8C8xvFUeq5XDrG/gDDb4jLMoU=,tag:UYIQ3T1lT6/KN+MStWXhBw==,type:str]
                client_secret: ENC[AES256_GCM,data:o8aF2yeqxoNVSECtn3LeCaG8l71yj2Ge,iv:dfyeWeVHkZzc9kkBQe5+6tsoIS0Mx9Diis4t7qrzbVc=,tag:3T8XHfg0N79JDsFOlQW2ug==,type:str]
                callback_url: ENC[AES256_GCM,data:2gHdhcRvKAdetw0tXfhdqBUPPVEhe7qpfCtZjlsdTHu9/IkMOC+Zcv5tzgX671KHHrGZRQlZaw==,iv:Jtk+qcZ0yawKv/33erNh2mQ5Yb+7olNR9RkS4d2Uk8g=,tag:Va2fdnSWlCeWgWt913/Exg==,type:str]
                login_dervice: ENC[AES256_GCM,data:yPBi44AE+D3A,iv:Ypa8JU6eYKf2dg53Y+6twcb66NZiAB2aCwtxoyyn3Cg=,tag:/cI0k1z0SQf+9c7WwX5cWQ==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:BmZ56bDf1T5Z/2vzQiplmnK97UVrXo3+hVwS8pjk+acsr9twjEFHeaEZgzE0guiVb16slVoCQ8xBvun4hAfzsA==,iv:beQHscilvp0vr/yrGv2V3If3R0J2vW5ycnYu1Tft3GY=,tag:XhcGBgnhdpYS+++sctHilQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:07Z"
          enc: CiQA67O9AJtOQq3hR4NloMhMWd3PLclvFbYma7B/83ncdIMLaioSSQDmhpq8vWKYVvICUDnV8siSVxDKc33QfnkjbiZI+TC6KplcltT3pJ7W6B8GQoNouM2h/uhYNoCpq9kKLUTFZHWeRibh99UwhIo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:08Z"
    mac: ENC[AES256_GCM,data:DCwFzjdsAlFlbHPlXIVcVyo7Asbjc2B4XwtiQsg5oeoU40LUqmumtOFo5hZQPGIuj+CPpxlSOy3N6tEBJeAH9xczKF4Y4lHBxajQgiRxUDSUOIxGwy8HDjGJ1FCyNaheWxjBfZ79KJgqgEl8xMlAoexCXu41QEScBegPacn7WBI=,iv:xh247MxevRdGWjfhlSbRk3eVD+KtZyMX4L6gv6yF96E=,tag:S32aFMZfabZWW0+JD9SvrA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
