jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:WamCTFap5MW8icnR/XBAWtZe3yiOsKTVX0lJaJMXIEte9qjkVa78OSUnwEARiCO/yiFuPttGN/dcIHt9zD1MDQ==,iv:zyQuDdOR1e8vhCOi9MAAgHKp00CtlPpmQdskRDZOrNs=,tag:NxUrSxsJhAXWr6Yq150xLg==,type:str]
        config:
            GoogleOAuthenticator:
                #ENC[AES256_GCM,data:DWg5uoYNxXFrzxVbAv2TN73A,iv:YOEpIZe/s5CzuvQdY118VfTVXQcR/JOTKCd+HA4ta3Q=,tag:RTWW1YJXCjBbVuGO3j5PdA==,type:comment]
                client_id: ENC[AES256_GCM,data:sFezj+Z8C0X2l5B1v97Fn5vke5+D4cdI4Uc2GVaWFkZid26pkeT4UCj0vs/VDy849T1fTMsVgXlvb9XIPkB862NOaZWurqqr,iv:EooO4YD3r/PqHZjUt2uyKOI7L/riLH1RrdmXVT5HdCE=,tag:xA4zZTTylUBdvpjKmYAeGg==,type:str]
                client_secret: ENC[AES256_GCM,data:3GHz2k/raoSiewBbn497JycIJcpFRsOE,iv:dzzWwC/L/CvMJMhdW7so9U0OqnNxGH8zyslizHPa5Io=,tag:N4bloYSoP936rmAohz/mbw==,type:str]
                callback_url: ENC[AES256_GCM,data:wbRQeCLfgbqtCo2gV3Ect++tRJl/4RLqSyBbMI+pR6TPSjSCBkZRkFYjYUZdS/jrbrzbxOHiZg==,iv:xC1W6p9sOJplPN5pMt308IIsLWzJUFzYWPAe9MiEMc0=,tag:4drlV0XVdx/xPfgQiKUTJQ==,type:str]
                login_dervice: ENC[AES256_GCM,data:K57LSCwfLZct,iv:jigWs9UanUlfci3cUEMX7PoB8UGGYP4ONbf0v1kdlnQ=,tag:Tfb76UrtC6GpB9bOq7N26w==,type:str]
    proxy:
        secretToken: ENC[AES256_GCM,data:JuTn/iAwc9zUBmHrSw/z098JlxVS5IIVxveneJabLX719UQx5+SE8pUNzwI5ylEFggmrvCbAvaubV7XYmhROkg==,iv:5mwMHK4/8ANfa+leU0tivyCY+DzsByUnK/l+tFms0N4=,tag:ix+d0rxvJFQAgwb4yQp1oQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:22Z"
          enc: CiQA67O9AIc5SGnwxEtiviEnmkQSDhSinQqS2avBAtM2tero2joSSQDmhpq8g1BALD5n8vH+qioMdFybDXbqt1kN41kzBC9tQRA261uPR1FfXcvyOXTYOacUEtkx9uy9m3Blb+LFCiCpKg84YmTZSgs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:24Z"
    mac: ENC[AES256_GCM,data:6HF9wqIo2CDoPPZnLu3ztY/65VcIosvqLNsVN4pSTNtOjEcv8vBwXWeZ4vUz+DXiQXf4fm63p3wvB0fg6TCHCqQvfiYemlVv2hqX2WAN2sIJ6HoxCizZEafcGOsqUqmeRKgOHwj+TqUYsjXGHe6TyI4fzFj4VkRiJFzGfpajyJE=,iv:xMNPJ0XKxQh+jqtpGtU5+ldJwG8M+KdUHnhXkjeZTPs=,tag:XoxedPDoqwXXq0pWrRgBtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
