jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:heC66fPDtNI/B0gfJxnw1Yeh6CLqJQcNfLZuqBroaPE1DtGdIETbRjbzZhsymBXnJlTc94BMTDMTLRxdDhQLKQ==,iv:DmspLRVyoEtXsf64JZgAKXPb8ve5qnOyX0iTJIWEgy8=,tag:ilIZ0RMZj3jV6P1n4G9hDQ==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:sgG4bzxl4TfOLg+3qUbvEAP/e0kwihrZ/8sgTeuMKRNcir80RPwTXl6Ba51xN8ai0TiKuhTVhb6dxBQ7K9TZqA==,iv:q8P0k+vAGjVs6LLcRLpAfKFc5Txis0AITDZrMH3v+2c=,tag:osd+EVOuiOiam/5aXkVYJg==,type:str]
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:HTMHGrG6Giyakh+bgK7DfbyyQ+/N6i6C0edkVIpRdV3z2597hzqLsroRJ8+gqKvN7ckl/3o7wYpgNNgoeaL/4KsphS659pqy,iv:GyPh0npVESmCXLrj75fc3qzPOKKWY/aRMUN+1eW5NKs=,tag:7G8xnirhjc12cU6jDzI1aQ==,type:str]
                client_secret: ENC[AES256_GCM,data:TM/O16KfrrcuGx5lsrYg8y27RNg8E00R,iv:qIkq9Ti+CIjUN7/JfIT6ECUdgNbzHZ2JzcS+exE/hlM=,tag:ZU8e9i3+/tVZ7VTTeVVukw==,type:str]
                callback_url: ENC[AES256_GCM,data:nn/dbshLGeFdPi3/zSPUNCp32jLHShzaPbgAVDE+2ImhLU0+jlFaE7ZOVIbHmm1v7vCMOdho5Ky+AfDwgdyG,iv:PrgAR8pYNMnVMUwBBUmBd/8LBnSA4T6C+dXdvOvsB3w=,tag:pYOvJjAMyXONEm3Vd5heJg==,type:str]
                login_service: ENC[AES256_GCM,data:5kZlwPB4gQX0,iv:0kZFdBEggYSl5zLx8WUpwrv5rmlsUp3C+YSevSrTWME=,tag:/MjuDd3qpXsvuPv1SsJ6Gg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:07Z"
          enc: CiQA67O9AC/+gWmN92p+TPrlSkfobd6Yub93XxX2duLUTbFK5TwSSQDmhpq8a3GRuccBk7vd5m+jxw+CH1isjGjyhKepsbBRiCUXZ6iRdwNblzcr60HDb3ZpiRLx9in2QkLe5ODeraHuE8XcyxmnnLo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:08Z"
    mac: ENC[AES256_GCM,data:dSLYrwrd8I5RWD3yYces/rv0Lu//JMz7KszO4M09b14NdKL792+GXW9twtKKU0PUV0WnMUv7BIUcZoJ54SBEX+fYshiRhFLJHzWrLIkosJx0TXpwzxHh7GGvDwF/haaX42LV5aeX2xulRgisGigmIBLXV5Ha9nWjdOcLW6FQqKA=,iv:NjhHGNG+9XquuZ/yGiPkQ6SuGsO68Eui85nSUjer4Xs=,tag:UC9XKuYo2DIkcXbqVIXMVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
