jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:Y00qI1rTr7+trskh9jOTfj44ZDllnDZFFhjzX4kNGWRUv827ArNpoaqL6Ras0pdM+N9whg9OGVyhZ3o8WMIm+EXd1APivRI1,iv:IUsFQMtObt1oKvX3lJHlJR/S27zOV83oqiftol2aXPM=,tag:qNmZesUvRkFWSDxclBKTRA==,type:str]
                client_secret: ENC[AES256_GCM,data:wiK5Wrt8n6HmrMLy+MJkxAWyVSi+iBf2,iv:Ad6R1661UCGLqa5++yxVWLYlTaN3GThReIIoOrwm48o=,tag:uInk0lBuHQ+SdrfqeOVG/w==,type:str]
                callback_url: ENC[AES256_GCM,data:M5Oh5P4OCp9/qU7wriMIc9yFkd8NtppvFerU5nuSq2rPM6EKAJlkVEBjoqJzhACwjy7W0zh/RGTR2vepwCaf,iv:3hwkB3DaXxMClDzYKCHDu5omFibFbsyJq+isH9yJRpM=,tag:1sSAj2u1Rbe+7bsHI+8xXA==,type:str]
                login_service: ENC[AES256_GCM,data:WqZIJExc2K75,iv:wwAtPHD4InfPQQeCLUXC0Hi3hlxkMwBwR4OPNtz77ig=,tag:ZYCWrENit46whZuZWFPTVw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:22Z"
          enc: CiQA67O9AMaXOBsTzrX7Sr8iPcRUl5z/6eJAdC21ZYPfoCI+58gSSQDmhpq8TfYxko4g1D54C5QbntgTgnvE6olStgyFeJ9dbTtoqC5SK4YsWf6G5FMXKvC4PX/axLe1kXUjaRcDAPlP0+hgxAzm1Oc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:25Z"
    mac: ENC[AES256_GCM,data:R92nOMWfSIwfrkZPziOQeE4LvUQD6h4rCIjd/ST+A22W82/MVuScyiCQK/hJLy+7dC4fp5SHrs8XK90djg4akVgbIIybKMk37MR+PW92hbe8UnF/9x3KHaxmzQM04yGFZpxtocrNeTjHe2tdkYLKb1ckeNz8JjFc2jmonInq+sA=,iv:8nX0/sgNzAcwXfYpLZ3ll3qsmwXw6P70qPJtNFwzWCY=,tag:9x5HCHMT+b7pq10+0UKjtQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
