jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:UNbRoZp8qwq6niINYwTkyoH8219y4VFj8DS+CMxtC31hwvlJB4bqTw5dkADv1o5Mb8YWTeIoTZE5lFlSxvlydJKwxILMqHAn,iv:F4c90jzScXvuyr3Si5IMNKrUL9BbdGClw5MPNNv8wbM=,tag:QISOEgqDBO2eWgQT0kOz2g==,type:str]
                client_secret: ENC[AES256_GCM,data:YqucstsUYDpowKks4N8nf+A11v3C0O++,iv:lkXx3ktraRFGbBlR0ns4a+j/upCBrqxjZ5yPevkpc5g=,tag:KrHUhhWsm5tg3yS2+tllzA==,type:str]
                callback_url: ENC[AES256_GCM,data:4RCCcc7QG4bDIQC0gtsxXxmNlP8v1GeBuANeV/KTd9H0YUSMoz1o/7z7Y+Inz2ILdFvqy38idw0ppdx7mjc9,iv:Q/YBjhz8lVEqh6xP6SIIKa0znQ1kI9QKXTPQvsoNHfo=,tag:AlaMvofFrdO2u4m5ws+p3g==,type:str]
                login_service: ENC[AES256_GCM,data:4x7VIiPv+Avk,iv:F9C+ZTL2kOUcu/TbZO6G9UG1ZFCfWOg1aynwJ69q5Uw=,tag:HGVs2LMPmCPrjEoa3LzZ0A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:02Z"
          enc: CiQA67O9AF5na0nc0qf1mVBTlJauigVdBhkS5DscxaL8CUMEL58SSQDmhpq8h9MgOgVOeZzLvg+eL28YpEYGMggF2Zbc/TiE46Qg/kgbx+hb5AHq6m1FydaACeUAxsPw6k3LZp8I9EfzwfBfY0u9o4I=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:04Z"
    mac: ENC[AES256_GCM,data:90674Ol2DKKaqVNGg3pXNqTAZIcJI+8NHNjdSPenp4/LRJHHHjfur41VujjRtYPTOeH4JeWUqjljXGVf6vqU+OYuLtUnwhycI83zMwB94O1M6rtPMKVgb73yimkRLeQ147NvO0ff9XAKJsWNQDsFIkPxdxjnp6DyQgX8zec6/o8=,iv:F5rhpQjomGVeEN3HEJi6ssfqq9IiJoDBjyejyOjYlS4=,tag:YZE19ATnV57aL3uUqo+P3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
