jupyterhub:
  hub:
    extraConfig:
      90-sparklyspawner: |
        import z2jh
        c.JupyterHub.spawner_class = 'sparklyspawner.SparklySpawner'

        sparkly_config = z2jh.get_config('custom.sparkly', {})
        c.SparklySpawner.gcp_service_key = sparkly_config.get('gcp_service_key', None)
        c.SparklySpawner.storage_bucket_template = 'ucb-datahub-2018-w261-{username}'
        c.SparklySpawner.service_account_template = 'w261-user-{username}'
        c.SparklySpawner.gcp_project = 'ucb-datahub-2018'
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda

  singleuser:
    # HACK: Temporarily give user pods lots of k8s access in their
    # own namespace. We will lock this down later before productionizing.
    serviceAccountName: default
    memory:
      guarantee: 512M
      limit: 2G
    image:
      name: gcr.io/ucb-datahub-2018/w261-user-image
    storage:
      type: hostPath
    defaultUrl: "/lab"

