jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda

  singleuser:
    # HACK: Temporarily give user pods lots of k8s access in their
    # own namespace. We will lock this down later before productionizing.
    serviceAccountName: default
    memory:
      guarantee: 512M
      limit: 2G
    image:
      name: gcr.io/ucb-datahub-2018/w261-user-image
    storage:
      type: hostPath
    defaultUrl: "/lab"

