jupyterhub:
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
  proxy:
    service:
      loadBalancerIP: 35.202.51.47
    https:
      hosts:
        - w261.datahub.berkeley.edu