jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:S21PvqhGZyCjQ7yqfOTSAT4=,iv:fag7yFO3+REGZi6dqy55Y1x1zWsPDVR4vfz7SmNsK38=,tag:PxWu0lHSkAtFL2DAhUFjWA==,type:str]
                client_secret: ENC[AES256_GCM,data:G+AlbBgpTln1Hezjrb8OJMbJmGBcDIHlpvuorpRjcS4Hc7bon30uRGdJERSgCPhBcc7/vy/DfbaO0231rRJHDg==,iv:4HbtrlFi4dOfKxf3Nw7UE6Fyosebg469Teqwp/nX0Qc=,tag:ceZRlcoaOkeLuzlNZ1dOew==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:VuTYOGE+zRG4MZ4gD8VNTpPjy/6/aPkGhg0YhGF5TMuSFeA6wdRWkagHlBO4p/BM37znulQ41w==,iv:YaGR/g5CIY6CCwDM8Hqgzuu4+cHfRZKwgc5Gzpp8+FE=,tag:kSnsQbxS5zVtJ6VrWTCDWA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9AGf3YJfZEN7uX0fLn1yh6fiOBhfXAFPidMBGLC/g8woSSQDmhpq8HXNr8+jBRVUhZ+k1t1JRNLxdA/kINAfN3kD1hRwz1DB1LFAeAC11jCo7LPHUeZFzhjI847QXsU7jEflPa1Cjdvp0Cuk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-28T05:42:51Z"
    mac: ENC[AES256_GCM,data:PFqC/Jf+b20VLtLMnbCm2LNQi89BnRDkfxoGMIpC9t1IPMXvWu9PC2TNZBPUERAMkk69IrUJd7fLCLzRIU3VIZzvld8RvLNcU2PLKWlhV9usLREhF6IcKS518SU0hsflpP/GGAIOfpY8Bl6eVnD4S810CytZC1569KZi4rwh7wM=,iv:kR1yp0aSUgOZVDJ4NbyrY4byV2ZctStBfdiMY+fEAjw=,tag:9I4XZxrprYeBWqZvMbFKVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
