jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:juWUCXsKLsFulKbgzT7tCtO0iJRwGql/YuD2AB9OrPWtNwUWo/e0z5PMIt9oHA9ZVxJfo+2ZkXxTX7XI5Vbw6Q==,iv:YGhrVjvyhaaHrvxhmQOyd8cUPYUOxhcgI2Sx8MxSHEo=,tag:rjk63NYdVlCbXOrzSOGSNg==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:A629Y8eRuAQ5uILemww3TG8lMXiR4wQzIpV9B7oYp53R3lgdLDb41ZWeaxHQrQ3dEXlTR7O4P5k6GpfJLL+PBQ==,iv:2DQCffYUL199QzZHpoMvtaiSkRTWA+iRt33h5Uq3utc=,tag:z1ulSJbhs0rHAGc50MhkJw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9AGf3YJfZEN7uX0fLn1yh6fiOBhfXAFPidMBGLC/g8woSSQDmhpq8HXNr8+jBRVUhZ+k1t1JRNLxdA/kINAfN3kD1hRwz1DB1LFAeAC11jCo7LPHUeZFzhjI847QXsU7jEflPa1Cjdvp0Cuk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:46:26Z"
    mac: ENC[AES256_GCM,data:0Jwmbpmw+kBQqEO/QQ924kF255phs79pCVyCKejOFAtsh07ZSya488P3gM1O9wKMTPQQICa8XNMchIHOogUImImA9QgyaFGbVxhoA+ckiu00ZUJvP6oA5fdvwTQkQkiEFEBdmXysNsJh4tc7mA9rj41D7++TfhyKW/7DaWGm4z4=,iv:VKqAMHxKrRYKKjAtAkgZHZ+n7GtnSOIeZFbrWB3i+cU=,tag:6GJyE2K3scPHi8c1tCS7DA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
