jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:+CF6vUp0DzuM679fRhCu/iE=,iv:3x4R4Df+jjU/ypFaoqp6PQV5D2bGkAW6p4TuMCZMhmY=,tag:FILE5uR7iJaXbq/Q1pcu5g==,type:str]
                client_secret: ENC[AES256_GCM,data:pzt6642uHXo6e41EvtPdrf2aE5cqD1a7WZISfGunavqYB7LOZgOeA2dMuB93DOipUpXvd3einjKsAB6lAwRq+w==,iv:r6ADgxqPgRBxHqApaCghQp3BUcXDskZuQWR7n9z+h3g=,tag:65R8P+6S/eA9DyYazPv1Vw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:k4piWlBVvsknpO1NYnvVLVs/fBmfYhNoim/dX14eotAehZ0iCvfdFbZq5A5q+d9MWIWZwBMYrvbaj4/Ncop9,iv:aVD13yL6W0aSsUFszQ65gz3bQXbrzXUdmoxaApBgWgQ=,tag:O7Z3cGFnxBJnk8uVU8Dcqg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9ACz7rZqTd/BwMEMVe0Kz/HAANXHEvPPLzdESq5msmPISSQDmhpq8jhnCtx69Yysbh5dTHc/oUSpHF3NXtpij9nAQPlGkvCCDcbwWEDe5zzJzXj3gAopcmHw/gd7pwM7SvRtkslIfhduLA7E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-28T05:43:57Z"
    mac: ENC[AES256_GCM,data:TIaClrMm2bUnRFFPqukmUCSv6sSFigp/3dkvS4lCJvNUtk4Q/bnyxkOHSC66PgVU6O4UWqPu/uSl8FAwgy0OIzlEzswgxLbYgjx/5Bq0lyTRCFqQAhR9e1KvQd6w71aS6Gn1TtYy7rjutz5TP6uuVkFo2SNJNW52dgkdtpSfnm0=,iv:Rb194XQbBmhDkFMciJb3Ij8e5qGPKS/GAmxy8qPrc1I=,tag:OJ5+Xmu7dYWo55ZDTRpEmg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
