jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:O9ImBqf4fhPhTt7M3ql6rYVj/uYOykxU297p3BVE2ni6ppGsYjlvKbOBN4ITsOuM+56XJNWvPS9TPrTv9hepbQ==,iv:eYWR5o9JNsAZEHMJI+rjxh16bX2EfXfPCOWuCboAdqQ=,tag:8Orxt5w3pDOf15epwuBrOA==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:154lgz7fGIWi3ESAnNNHD3Cyo280NsfbyL7ECg9MZKAW4rzYwekCA7Wp0n54Rqqj1ODPYNBksZzwNmSYbLYxNg==,iv:v/4NSre2pcSlIWErscbBsduuvnQAec8dwvjzJE0lotM=,tag:6M9cECfUO4B59lx9ggHs1g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9ACz7rZqTd/BwMEMVe0Kz/HAANXHEvPPLzdESq5msmPISSQDmhpq8jhnCtx69Yysbh5dTHc/oUSpHF3NXtpij9nAQPlGkvCCDcbwWEDe5zzJzXj3gAopcmHw/gd7pwM7SvRtkslIfhduLA7E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:45:23Z"
    mac: ENC[AES256_GCM,data:uxRhx8RZz1tX4Ngwif6AC6OKvelXfcMsG4K5ovU1H8UIn129SQzKWksvJs0stAuXXVI4Rt7EBgATqTmrlHAYluinDMeY0KPZ/9/H27tr7pXU8Qm5a7fR7dtLxLlBBemx/kQuf/BvVITzHgpF8Lt2ECKq+pnHGIFK2F7poOY+UrE=,iv:b9NR4+CINywh+fbFoE8eA4K0AKTUa/JwIAraxaXeMyY=,tag:23hI43gtRHvnbFsvtl98+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
