jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:+8Yt4JizT6DmZhbCzLuk//iGCxcW0r/F8y5IOqH6p0y4VMQ8sLe703gKU8iqv5ueX1uU+rKVLfoMrC3Og6ffCA==,iv:LpG7nRogTdX0rb1LNIi5hEYj2Y6jSI/MKtOnnyifIhU=,tag:XVCoAfTq1CxWGiTl1d7cwQ==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:DPqU8Yty+WX6QU4uyzulozTQMG6NG+6mF8Cusa8WFIyjSpgAb9EtStgNxh3Tyy2IZXW6Pynd1ldrPV+cTCvTNw==,iv:Qcs5d4EIQ3lr/HqW+aL/Z7LWcrit7KJ1RNkgE+ddb8A=,tag:RKOHMrNCB8v40jSsnc93sA==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:rg7+GT/fm8Kp7ve/xGhAyiY=,iv:/d6JJ0QoloT9Nfxgmst4xG07BAWZGnLoUcbzGoozVX8=,tag:ud5adxQkW+zn2EZQBA1Wzg==,type:str]
                client_secret: ENC[AES256_GCM,data:uVBeRzL+AMXOpmHG2VZrsLzFCIP/QQNLDJxUj8EZhF6phmtta0nZJ9EHGdk1LigYWIE0kDfI9+PYDn+mZLMU6Q==,iv:Oyp0r0gIKoTMZdM2SObwPcYVLzNl/nCxg0yF0JwkCnk=,tag:TlscCJcILNm8m6ZhYALdEQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:baL2ifv8L7Hv+vQJXh9r9XX7CltOul9Yall5/6eonjnHh4FwJaPiB3e0YpqXKXFUuYlhrg==,iv:MzX71XcDoADwuF4R2LDkaT8vrMqF+7z2OVb4GKSiwow=,tag:NM+Lp5JrQScOX2I1/KU4eA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:01Z"
          enc: CiQA67O9AO/cIzaln/5LdF7z9JewjIafENfdRBPUhFG/8TG+3OgSSQDmhpq8t1CD8NjYoKSGFYAlztxK9qYm0Ql5yhamUvKefz+M+tTJVkAZJENN1xAsTyLyZirRatsFaUf+IWipHxgtTyJ92oDMNjY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:03Z"
    mac: ENC[AES256_GCM,data:Sy7dx5RhdDWoGrYmnlbU88LmPHEK+cXnYI28On6+V3kXqpT2fSy75PYgs+//xW9v8mxJOls3gKNOFmE5pPtWqHdqeT/owN+gjkwrOjx1UpECh1eyH9VY9Ma0aTuu9t3CNVVGRPbFnssbRRTx2Dy+jxHYBQ/Ej5wX7n6IDPXAh5M=,iv:K5e55D8YJAqEFkZUnaxo+iNw2H337Daiys4MgOgIONk=,tag:rZxC+46HKl3z0Dtw+SMmJg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
