jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:7VneYOmfVJEKrsmQU4cCDwM=,iv:tKZ2bpdt4FQwEfg1EMmVjetXcyhDV6NFLWXHTEwcUsM=,tag:GeALAU/eedbi0SjY3J8IdA==,type:str]
                client_secret: ENC[AES256_GCM,data:qCzM+biZ5Pl1LyYbwMNVlU1tHyoC8BledVrfLBB8EInrqRRJ+Am+qj3HLdQ6F8ydiDMhZ+T1NMClCzl0/kkkNQ==,iv:L74Bag7xpNJ7pbfHxGTnJ9TDvbKlX+TZpMvmMLDCFQQ=,tag:N6VfQlKQKvkrHW9Q3KqYiQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:K0+96ghqpVcha9aNbNvWW2gwgOgj95FpyQx7PaW/CvaoHTFfywvtLmFFaqjKBLhD09Be+Q==,iv:AkNRHylsQizQqCshmyigwn6OAZPylnd2+snyZotWg5E=,tag:MyngFkIY4nKW5gZum3ZArA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9AG7In+P38vy/yG/mZHkQSwJ2jAwImE9ytWWm/nWyuqsSSQDmhpq8b9w0I32iZqhIAMhwv8kvNAqshAH4Pmf6lPgGM2k3TzePi6qER5or1U29fiPH4wQzDk0JysSb2Ge4j4QCcyP47LQbyDM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:57:59Z"
    mac: ENC[AES256_GCM,data:YXSiQGaclsWsUumH/e9kBsOvvYqx+Ffs9RycxbKhK1KiP9Y7lzV5UUwmyzkKdiFKFg6L75T3K0jL37ht5+Z7mTv/oXlCe0iBM5KPl/nERlxHITbaZMv2oF2xpg1kUX2AxEJZJ1ROe+7sR/aYVnhpzBDMUWtwbShMwWzB6SxzLVY=,iv:pPYhKk945g6aW7KO2zyozlTblub/c3vwznzRkVB32K4=,tag:CUnGy2jlRgTFHV9xWh1E+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
