jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_secret: ENC[AES256_GCM,data:31kGp70wPJoFVWFJEzC7DLCHK25CYLfyQiDXnORKZ9Ls36m9htju8DmdmoY3cBgq3Y2R/CJVO7ThL/RgGNZetA==,iv:rpVW2Mp6bn3mWEUDZX6P8BE/y06SXLHB1kaPdsor1pY=,tag:WLJ1Gr9aNt0/pMPPbG9axg==,type:str]
                extra_params:
                    client_secret: ENC[AES256_GCM,data:dlyp/PkAXjlY0XjUT64QMb5F5wWDqn0iA9EDnPXSyLOgigz3qOpxCerPjj45g5xVuFMtdh0n+uZ406/boZ0jpw==,iv:9l8PXW1it1eyBpsJ65l6lSQWyxOgWyE/ZFH8U40EJ7I=,tag:FIE7+w/3zFWmu4nZU4/sYg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9AG7In+P38vy/yG/mZHkQSwJ2jAwImE9ytWWm/nWyuqsSSQDmhpq8b9w0I32iZqhIAMhwv8kvNAqshAH4Pmf6lPgGM2k3TzePi6qER5or1U29fiPH4wQzDk0JysSb2Ge4j4QCcyP47LQbyDM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T22:48:58Z"
    mac: ENC[AES256_GCM,data:khjCL5wSxDfDgnjXyzV4B9Z2HLSjV89ksvvbDdLOkZm2GTpN5ZxMCp8p9tXGeLOEeHegW8f0rMcis0mThXhLYbjB6D3GWoZY9Qb7PhEk/im/+QYgEmm4C8v9Bgvlty7lt73kQ1cb8BLm8DnlWMxBE0bxxFk/Z7c9zg+y2/Vdsww=,iv:XrB4dWveu/6I1DIWpZLddi7tiEuIafqsUsJoISibaCs=,tag:t6si9+Ay34h9jxcu9GqCcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
