jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:CujH+R0sfA65oUBwF/8S/C93ten6WVQe+6XsOTklV8U3xBJbjxUZTsf+hZT3pN9duMzeepxdQD0W3oGzJD1hBg==,iv:h26wreWG//bifdknoEwioMDZa5vesQUVkgpsSsXKJV0=,tag:RPoypYPgJHxutaeZa8Dd6g==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:df69LmZozrIEfUOWUdlFEAeOYGdEIRt0ZEHhCiQdr64lw2ilcAT1PJsrpfyM2SHyAp6Pde4+IJMe6BIgBnWg9w==,iv:Un+9PF/V05h5PpPLDbvltMfapcXDUcdZrF6vesercwM=,tag:xYABpeiOdu2YzvZeMyPIZA==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:XAY9XivIznlFLTLAiQz5374=,iv:sHZAH9sLqFVPC0wbGaIngz3rf9r8H2ovoMRXb61vMOs=,tag:6Atymugj/zxlv2Vs/3Betw==,type:str]
                client_secret: ENC[AES256_GCM,data:J85AdeEr9eDXpjTNAfB+BJVTaSssVGY0MTwAMR12JSwI8M14i4N3lLnIJDD2Cy+5q/LkGHlaLowHnwo8LhrLuw==,iv:NHfVEDTIecog5acM8qdAmLD7HE93qbpvFHTe3Kv5m9w=,tag:e13KnCFAwW/JAOQSsibbpg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:uNnTLN7BhFxa/v2O5rHL2X+Xy0JxyVMccrJ/iLHDT32yoMly4Yc+Kbv7qOUUEINmRUd2MA==,iv:wwNPDtaajow9Gg2SSyiZi9hUAoI/LYv9Y3wA/ObLEwE=,tag:Z58n98mbVeuoowOIwxBpZQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:15Z"
          enc: CiQA67O9ANn3a7IS3Ub7CHerJdngmLWPFiWo26XEFZE52xBGr0ISSQDmhpq87/N5PO645Mwe8F3/aBiB8zDNWrcBRoShdnKxP2TOVxtQ9/6TuO5p2jRWR+jgvsKj2qMcgn9Yf1kTTu4E8/3P8GX/vrs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:17Z"
    mac: ENC[AES256_GCM,data:Pq8akiFbCh1AjDqxvYbo7T8gd9/83T1RkV1BvBp2Vltxavn9mnA9eqlwKuRLO7HQqtw8Axb/BPYvVlSuwf9vohnczdKm/Ht2IXofM5TjGdq/AFpHq9k+/vyw4yM45N9R3ErwCrImSOWwwa5ntnCAJ/8r/abRIVvtkduXD6GaBLg=,iv:EcCFIewZNco1DFuFpV0eHWYFds5FzQayo1GAEzeH2SM=,tag:d709K38T8VPgWIdRMS8EMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
