jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:OAXAthpB6dWZs5Inv5jpAx0=,iv:rPTPv29NaDXz2VR/btIR7bFKQibDzzsCQp+ZDDlHpfg=,tag:4WIHtkuAnnGcesimo2hi8g==,type:str]
                client_secret: ENC[AES256_GCM,data:Wwq81yQAS/naR8rCkMu0fMzDQcxGXa2hPuZ8xDw+SBpgBwH1CEf3Wwc9zeWpSY+9Kb0kmxzt15ojxlMPDRwosw==,iv:sKhg1ehW/a0TBteUE8dj7INdqdN3aUhWkkEzS4pSEqw=,tag:7Vz6h5BIjfmNqliZG5RQDg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:nZCyOKyi7Ley0GQqzBK+EY0quzAmL4IXqKevJh0jHuWNYef6MDXZyyeK27m3MQUl1hUgkx5LxS4KqOxw,iv:3k8/TanaVS6qk3cnG73wucnjNE6L8h+o9B3/t0hFy5U=,tag:ZpTeuQ1uJV2AhLg85hn/wg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:15Z"
          enc: CiQA67O9APReEnBtl5Vw21JH92MhhGwCypzS2yAuJdMRnbFEFMcSSADmhpq80EKAxI+L3m4zWTSHsPWF4FCVrtdT4oaud5EhNLYO3DAYdfn7nZh1cE+o9qpPmk/SueAS8YDlZtOZnYeQIIsUCdleWg==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:17Z"
    mac: ENC[AES256_GCM,data:iO+/ZsFFzM1kCE2HvvM6wCFSKPjil0BpjNPyKsOiiIovcYbC4AoVYiCp9bNgx1c5tiZ6OhohNv5v0vunlL7B7mXQ+nCFWKeqpmzjD4R9QLh9s0Tso0Mw1vsNlpVHDBatSegD4tzCkbA/p/5yeB7PozhsUl5u9O/0q4JCTwEaOZA=,iv:oV7M0/Pu52xZhQPetabdI3wdaYVZQZgNGN1eiJYymVQ=,tag:2QDicETpb8GF8wqIoP3XYQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
