jupyterhub:
    proxy:
        secretToken: ENC[AES256_GCM,data:CiswiXcpjmboroYN8hMsgW0UtSoSTvyxBbW9b+lKE2Wqz33MfbHp2Bvh0iPDaDpNxhOl3NcydV6EwBk/g2Bs/A==,iv:oJvhjsSeQ0C1PpEfrKMmTdHXUALhuF6XeIqs3HE2atA=,tag:FHBUmUxFg39FyaEoDRx3BA==,type:str]
    hub:
        cookieSecret: ENC[AES256_GCM,data:yINeSiJqdTzIeNpF3lHxpj26l1nud7WT1YWa70zLSsmYfbJLbeRxKbZPnfIzAXLeB3d78NGGev2vlyOPFo5G+Q==,iv:H7ftz6zf2UNg0gwI80MtYt399V1DaeHmWxAxcGhl8no=,tag:Eri9xNdnFQliCNIjqSheUw==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:dWQvi1M3UbJtjNxwufbKHXU=,iv:hkv3zp9Twp8/NTs2c5gWT9DtfJJA1+zGQAuJ0DHKDYk=,tag:u3pMXqziqLQPc4WKS+7jXg==,type:str]
                client_secret: ENC[AES256_GCM,data:LeomxfnASW7RVpyxGFc24sm3NbjmhRaif/gG6lErMon5p/KiacQMbMdquVZY9fdiU3iG7XTYKm+Pc7PSOXVY4A==,iv:aVp+lGS4oaoo4YDS9FWLvBpc8ThsRn49bZ5jMiq/QOY=,tag:Ct0Xyxx80XpBdQfCEbkFMw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:/432gMXICGvo98JzyF1kyGHyor6CrLMmTzHtuViVoIl0BIoiAXNwksbn5wsTyYNqHWx6mku7mTNP7XgT,iv:pnfxRjtZXUjAwNODcsUSCFKtHOsaCDC8c9eHUMOhPug=,tag:Sq1ITZXBSIsUI9hxmFJZWg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:01Z"
          enc: CiQA67O9AGgqjm/RuE0RRn/ew9JGyp5wzd7HgD7WtyzcuUwpMjMSSQDmhpq89EG7/fHYGa7kes9xH1TTNw+YK9kgaEToFnfEVZJafI/ihxTe+Alz5ohMIBrmHgrbrVw180/d72iCdPyh+lIKTSETCgA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:04Z"
    mac: ENC[AES256_GCM,data:At3W9cxe1zOJSl4my7IbNSD7SqJqQMB7mcCJV3rKUdRCIpk/IY0qKjOCf2tb8NCdk6UIIuPMOcWJ5ULw67bt7dWBMcLMYvoi6H3uRJ7WgXnImoCyOvxHp9kMr/nzm0lN+6CWLsyOYvgXaeP77KlGGZDI6xLMPOuvrO4nwuFEQ9g=,iv:BMxXTCzHkNt1IcZJQkaMCPFviuZnYVJwhb5bCPP8o0M=,tag:CYIbP3yKp6z6pKvQeRLL1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
