jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:aJAk+cpB2zqBa3xQ52TCnQA=,iv:EkyWCXI8qkQ71FutiyV85BHMvoY77SZkxH7IcDtUX5Q=,tag:H2GyVA5IVwPV6auxjfMzbw==,type:str]
                client_secret: ENC[AES256_GCM,data:e4DDxrXJHPpXzD/1qSS21odJOGaA/CKl/W2vaqYA8I9Yn92o9VwNE9bIwaIQS5iMWGzyh2YPdHFhk7Jy5kSPFQ==,iv:whLlp7YwDfryMwYcnJwhF1ZJW/SF5GyvjLRtEZbNl8w=,tag:Q038nQjJMDLM6vCnC1mp9Q==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:QowN2Xcdj0rtCRgkf5/ISoO0LBNUTKqog7F9+jZERMHxB3uR91V6MLpp+hzWIV4qvzuY6Pve+YdRrJFG,iv:YZI3H55/7zMUaycQ+d/Ke7JJAnpZ/1c6JYpYvtJPVnE=,tag:gZu9xZ9LGgDj9VriBzsGNA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:56Z"
          enc: CiQA67O9AEXG+boyO5lIpmeoa6NGz5mIE7FpLJA/g5gnwQq7C+4SSQDmhpq8vXq9wEQ66RrHqAtEwA5IijNymvaWQ2T1gmC/Jz6l4gkURScnVgpw9687BlcvXognkC3mL94rkTGrSDIa+BUdTSxU5Bo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T22:56:27Z"
    mac: ENC[AES256_GCM,data:JlxXOrxnucay6rs4mjAf+Aox9odwbw7DxKryUzZIkHMqvJkPsPxSD0zPGhN2R/L/uJn/zYACFEuJ0TPU7dSYY8Sp7raHxiMvkfTmxFwSZ6GG61hs/vPfr1JnzCKmzPVCVljJrkbMTJodGPrNyySUPLLmo9Fz5Ptbawf9okfoAdE=,iv:d85N9iO40ZjHDqUV3Dvuz66a9JbjE/HE4hPx1GalF7o=,tag:OQny4DBv3yquaBVp12pT+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
