nfsMounter:
  mounts:
    # FIXME: You need to create this manually on the NFS server
    - nfsserver1:/export/pool0/homes/_genomics-su2019=/data/homes/genomics-su2019-prod

jupyterhub:
  proxy:
    # service:
      # FIXME: make the IP static in google cloud console so we won't lose it
      # then specify it here so if we redeploy we get the same stuff
      # loadBalancerIP: <IP of genomics-su2019.datahub.berkeley.edu
    # https:
      # hosts:
        # FIXME: Make a DNS entry for the service IP first before uncommenting it
        # - genomics-su2019.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/genomics-su2019-prod/{username}
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
