nfsMounter:
  mounts:
    - nfsserver1:/export/pool0/homes/_genomics-su2019=/data/homes/genomics-su2019-staging

jupyterhub:
  proxy:
    # service:
      # make the IP static in google cloud console so we won't lose it
      # then specify it here so if we redeploy we get the same stuff
      # loadBalancerIP: <IP of genomics-su2019.datahub.berkeley.edu
    # uncomment once DNS entry has been made
    # https:
      # hosts:
        # - genomics-su2019-staging.datahub.berkeley.edu
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/genomics-su2019-staging/{username}
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
