jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_id: ENC[AES256_GCM,data:6bXjwGClrBBcsvqDkdgu+Gb6PRY2w6JLbkFf5VBFvRtQ6tWukYBQnAzbQ4g9Ie2rLGzyTSdHwv1YXAj4+KbM7w==,iv:wt4+YQspr0QXAtWvyqwn0gxphYrqGDQjS7HdyDZznmQ=,tag:1eIDFIxL+fVS0yhkJ5ftxQ==,type:str]
                client_secret: ENC[AES256_GCM,data:wlbesP7GbPTmw++UVKs2mY8kaJL8BQNZCekP9U/+zF8flz4IQFASUT9ZjKiymG2n3DcD1x3WvsQttk2VF+RHIg==,iv:WHDN6miOS/YFZj38S1sLPlSzHFip+Uy5GLiPKiUTMCk=,tag:bOpKcweRVmk7sE8zsI4BEw==,type:str]
                extra_params:
                    client_id: ENC[AES256_GCM,data:umrlO/k4pYe2I/qPUu/peqbJGzUtCmqPRD5Wfb1fJs4cbGFpccLuyUvYxQBPkEDdNJ3kRnqYnyVDbV4rUmnlNQ==,iv:69nXVVX9dEGzYevubUragAJ4fJMazO9hlsrouQERDaI=,tag:HK1hUxdxy0/VOdhUXyCjTg==,type:str]
                    client_secret: ENC[AES256_GCM,data:cWuTXOAjl0joZ6Tk+XF689cNCYaQpfZ3fihkKh0WLky8r2v/o66UdXj65d7GqvJfU+bnP/+SvU0b1oH8PWkm6w==,iv:O7v8xoOFYYqcppgMsXgoM+gQ+mgbYuXAozQBWZAFhFA=,tag:movx2X9SM195+rA5gDM3zg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-01T16:46:08Z"
    mac: ENC[AES256_GCM,data:TP8T5728rpvTzgBtP5jMhQk4FPq3JH25ve2EkchXCrY9GCM/+DO4OJi83ijXtQQwDoqPgfDzrN+LI9pY2UVytVlx3eZCbd1jkuC4XrBqFQYldDfd3M6vi0gdzEsEzotX6vtuqs6d5keuLwtG4hFhfMSZxe2bVdguLL/wPvkJklY=,iv:D4oOMAguzZirl8twG9UOviXCbM+WbS7O2XPLo1ujvyM=,tag:rr73F6BKs8NQCZifkPBdCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
