jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_id: ENC[AES256_GCM,data:cJGqU5hcATqva88yDoxAyeVQT5PX3l2LDh8ZN5ccjg4A9efC5YLADeARKpp4r+mqJVf9l07I7Z/tFtFOhXNCGA==,iv:QCeajHrAqke7ShJXNOiBg++KpJFdIE4GgaxZarkh9G0=,tag:BXrIqhKMBuu0DngoYSt2Kg==,type:str]
                client_secret: ENC[AES256_GCM,data:yeb44Lr5a22E82QT2AXpMJLjb5g1bLu2bxubNw1VuB1Ensqta97gS76Klco6L4iHarNim85oyirrk+E5bHDcWA==,iv:Oc8geBmF+OfSOo7/pMnb5cwayoHlZQyrn1kOS+Gvhwg=,tag:NOp0uPJXGhvhfWFI6QBd7A==,type:str]
                extra_params:
                    client_id: ENC[AES256_GCM,data:q/WY5wdJmf9xlu1WzKlRL4XufgNuQtrKUnmerPhMLHkLyZJA6UghcGMUUZRvBBRFXt922E2p/4linmQLnatieA==,iv:IGeqm2Y2Zdosus7XCd1PsktWVYq5LGzJk1/OD5cHGGc=,tag:DrSJLMD5FeN53GkuFfJ8Jw==,type:str]
                    client_secret: ENC[AES256_GCM,data:pWc4TTNIVc54aNGK7rG33tBnCkmShaKJ/bVn94M7lYrH/oQkVe8yKXPEIlzb3zeQIU2SfzUWh3ixxxVgrqLd7A==,iv:VedRSDncffEGiA7XgIi4aXC5v9CgAoqEapRl3Hn8rSA=,tag:Dh8bm7DhSodlwjCkIJjcYw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-02T19:02:24Z"
    mac: ENC[AES256_GCM,data:CjHF5n2oXKE+3ApeLIq0UeqisF6+qf4QK7Im1cgwiigF7cQK412YXGTxa31Uyg6DPYr4GQkbaRtYmzGTOWw61qc/qstwCORnQbPwrpxa+4FoiymtZ9yLRovXu+EHIaUcIkK5uNeMRpBFr9ekVbvKZtl3Cy2RORfXomXPuZ2akRI=,iv:O/sWJIZLG9I3iMjH3iAUb4DTSGoKDWlG1LMfgwUZlxk=,tag:HDg70uUcAntfJG0NdRh3TQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
