jupyterhub:
    hub:
        config:
            GenericOAuthenticator:
                client_id: ENC[AES256_GCM,data:zKdb8oThgN5nnkttsKMPr1SY1GW/NK+zj3wT1YVUkIY0HNaF0z0pnXE2+Jwg2N+JoMpr0vcEjpXy/RDnCI4wbg==,iv:RmHxVzmTHDACQwAMTGOAj+DABtuAqIy9++drDnpFy/0=,tag:A4yCWKWmzlgoA/PbOz2HMw==,type:str]
                client_secret: ENC[AES256_GCM,data:xWleP5szYaliOKkcQEl21mqI+yfl1zxo3uu+4Svh7UXUch4oJ2Hv/zacBy/nU+j+jkhEAXCUIrQmzokvmVQSKw==,iv:6j/ad9jMdytb6YydGnFL4rsncle65EYlhQwjL+esh3I=,tag:66RDPYhG2mE8eHovVSjjuw==,type:str]
                extra_params:
                    client_id: ENC[AES256_GCM,data:kN0xEyAJ0ZCx/+4Nun8+FSH/DoHRknuRNL9ZT1Fe/BgfdDK4v3TTWQ0947uDJZpwu7hvHjKnUgDAg8HtzaVJ1w==,iv:U1+iZbBfy8hVBnCq1rBpahhu/dykeDEXO5nomQBobRQ=,tag:OBZ00QEVTTrNjPf+j/YpOg==,type:str]
                    client_secret: ENC[AES256_GCM,data:Pi7kVq7NyETlAARjncZ+RUsN19XP1Uv2jK75rbAdoxcBIKBtWCT85TXGNL/nq7oqjTaU1HO8KQUbOZyE1gTfCw==,iv:UiadHiEWNNgWAz5S/0DIG8EEUY2YSVU1+efYosWQ0QI=,tag:BRvzWw3L8/m+zjNQFCecAA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-02T19:17:00Z"
    mac: ENC[AES256_GCM,data:ZN2CCJlqlGkMPaB5iHvyLLEFJJQvnZKkLcpEP52MnAdLl99n6EON4iloi9zjLx+uaOER+YmShD2Jm0xBPWou8L5x3VT4IOsubINZxRo5CtTRxdQC0u+ogZGWu++lGvDMhLa+B3vSD8n5BGmXc1PBFxtBYmWbW97j+qqOTlOZxt8=,iv:/+WnWsO2840s4XaD7aXXBgIpvj2Je8IvVniTxkn7k6s=,tag:fETz3xwYLi3d7LexWxWULg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
