nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    config:
      JupyterHub:
        authenticator_class: generic-oauth
      GenericOAuthenticator:
        login_service: bCourses
        basicc_auth: false
        username_key: name
      Authenticator:
        admin_users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # Summmer 2021 Admins, from Yanay
          - katherinetsai
          - oscarb
          - kylek
          - jeshoung
          - takaokakegawa
          - wendykimm
          - ritawang
          - o.chang
          - jacquelinekyu
          - anna_zhao
          - meiji193
          - gprasann
          - seanwei2001
          - xinyueyou
          - noah.s.tran
          - lingjunguo
          - jaqian
          - kinsey.long
          - ryanchien04
          - stephaniex
          - devin.sze
          - efliu
          - sarah.zha
          - ellenkwok882
          - ralui
          - nataliegomas
          - kanchoo
          - stella1001wang
          - vkarukonda
          - pverde1
          - lillianweng
          - vpadma
          - markcheunggg
          - eunicechoi
          - gracealtree
          - rgoel777
          - joannayoo
          - graceyi89
          - vivrd
          - haru.yamamoto
          - itisashwin
          - cayanan.joshua
          - ciara.acosta
          - sarafang
          # List of other admin users

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
