jupyterhub:
    config:
        CanvasOAuthenticator:
            client_secret: ENC[AES256_GCM,data:QKxTGhCGbY9TcPx+JK4I930vXZDstf1UIGfw/2MoqifY8/2FXH3u75dCVVXCSSSReAP5dkQ1Yp7x5QDHusmwiQ==,iv:lB+XnsYywzLXxw/9KdlWGSujZvjychGyoZrQLSYgwUw=,tag:Uw9xUKrlBOyZ5UyBSvSh5A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9AK2027WGYGTzywa01Cz+Ez7sOTk/d9payovyK5pg8g4SSADmhpq89bbIWFjlGg79o/iupJ4anLU5Ab9VL+qNzhu6e83JtJ7wSv6sK+cDiEfVSaKQ1YIcadDXFt4WUKRt7MFvAa1sLqp2LA==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-01T08:04:54Z"
    mac: ENC[AES256_GCM,data:Jj6BvrjdhcB0OgvvNJ+0fX+TF8F0B6mZe9Aab/DTW8OYsWV3KMT7sH0yo3GhaCcZZjIx5fsVnTck25yTi/gNe+R8439z7TShURcUDUfhW1xiCJFxeoU+PcgF0W2qBxL5zfT1eIY5s9/o0kEKBsfYU5vbbu0wcnR8/z78+nDo/u4=,iv:HQ12IcCq88NwkoBe65ckQ7ykBod4IJYVquv4cnBklkY=,tag:NVmxuVhYVIHEQmaoMhMb3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
