jupyterhub:
    auth:
        state:
            enabled: ENC[AES256_GCM,data:gXQ5Bw==,iv:LU8eLCcznqaVw8KJfWJ64iADWhgBOYQA2fe+cQUmmNM=,tag:j9XiV4djZDiPsVgOF46law==,type:bool]
            #ENC[AES256_GCM,data:0hQsoJJ+fmPYvlOx+6PIxih9RwEv4tX4XVPSK5AbwSHlktODp80=,iv:q2HWE96ghKRvqwhEC3j6li/J5Ax2dFF4NBZeTKkihDw=,tag:3Srxg/QINYBaZiLRlnOlQQ==,type:comment]
            cryptoKey: null
        google:
            #ENC[AES256_GCM,data:q7dnberw01C2jIBAaZZhwOTL,iv:jE5Ydob0j0Jg2ZynXgguYcoKoIGBYp4cSMgJf7sTJ+w=,tag:klfm3URW5HW8uf6jxUT2Qg==,type:comment]
            clientId: null
            clientSecret: null
            callbackUrl: ENC[AES256_GCM,data:JDKnU60yOw9UyXc4TLg5pkj4eAvzGBacr2hpA1AAwYS+Ksy7+HMVo3kwSM4Gx6o/MmEw4n1gA650RdBNet9zKuh78Bcp8JVSjQ==,iv:3g2Vdx42UE6EvSOfcuIucgXcX+3qL8OI+NbQ7AK7HjE=,tag:fADgLF7kF4Qe1HZCF+i7Ng==,type:str]
            loginService: ENC[AES256_GCM,data:vZS2r/rGgHsW,iv:W67yXdekJGQ/5/cWp7W6erHm3f37nobIgBiGeX9GLqY=,tag:EyqB7NlllgMnFZ5CbgRjCw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9AK2027WGYGTzywa01Cz+Ez7sOTk/d9payovyK5pg8g4SSADmhpq89bbIWFjlGg79o/iupJ4anLU5Ab9VL+qNzhu6e83JtJ7wSv6sK+cDiEfVSaKQ1YIcadDXFt4WUKRt7MFvAa1sLqp2LA==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:58:00Z"
    mac: ENC[AES256_GCM,data:VTuGER/7jfVBYWEfsevxMccWEvDoPeYmGnjSV3xsmMKmdKTriv8wc7ro5W00GGOVfTj23UBt9SebalgXIrAVAA9m/I8XCVFctXOjIZ0OiluiTd3OJBJ6laqpCZsFTE+b+e1eFAXUWA/ZvULT23yT3vIL2Ky76mpWVZH69ePESHk=,iv:omwCp8aBKZ17rxXzsVr8YPmoQyFCCP7Ru5zPhoDNPug=,tag:800MOwoRAppwUtXWwYF4TA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
