jupyterhub:
    hub:
        #ENC[AES256_GCM,data:DsKHV6Xm6AupK7GNiWkKtydWLodadEgeiM6rZzlyXIQ326d1Hm4=,iv:3F+NM8egi4spAVox0MI9Vlk26HVE8vxevrQIQpBISjQ=,tag:3mIzSQUhdZe01836scM2lw==,type:comment]
        cookieSecret: null
    proxy:
        #ENC[AES256_GCM,data:h8+BdVg8bkx3iQVJDepCxHTJs6zPm3eU4amGOPzwZkOOa+udvK0=,iv:/OLWT1fkGgxWOlAsnj7F4KB1JLxdotQStSCKQhslmPU=,tag:iw0r66opTV9PhavUFNkLDg==,type:comment]
        secretToken: null
    auth:
        state:
            enabled: ENC[AES256_GCM,data:NtIvLA==,iv:vtSzLCmuiFcG09ph76nD8WwwgYNFEUwan4U9LOVv6ys=,tag:zh1/nm6INDd1jqSuzRPHjA==,type:bool]
            #ENC[AES256_GCM,data:n5HgoUeR6W2zmm/LYh27TGjBHKhk0M9m9aUOczqWP7QaHU+avsM=,iv:qW6UuGgqvpbBHNhnF5ekcLGsBd2JFTYJmBkf1eCtz+E=,tag:GYCGrWo0os77syn2W32GMA==,type:comment]
            cryptoKey: null
        google:
            #ENC[AES256_GCM,data:PzChTJfW4ta4RPL34n8A5qbD,iv:Zb1wpjfsVJNYY1b9ucEHJc/7eAea4ApwpGCyJjSrmrM=,tag:ZfiEuJrfhmwgHhBrACC5mQ==,type:comment]
            clientId: null
            clientSecret: null
            callbackUrl: ENC[AES256_GCM,data:hycuIEYPChA7br0A7VJFAW4sd8HBkcybMaogznCmWou2eXaSIFhJ5rC6RW967s/+bWdTxb8z5Xg4Kq8cLtfJvNE1cpUACIE+lg==,iv:u/jNBzuCfjYGQFGwi0+8vfYR1IGJZNF3z1+BuTYwt0Y=,tag:oyvs9ZCDXhWC2IKw75UNew==,type:str]
            loginService: ENC[AES256_GCM,data:RCrVZ2XH/GV2,iv:Orr5mtwgudihC/VaMmaLpL6y85DJVyVvXAi1W5NqeUc=,tag:KI5P57qr+vIH98HHLQgb+g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T07:25:17Z"
          enc: CiQA67O9AAEkB5WZ8gqMFQWw3FFFj5A3wHIBLti/9tTgcub29XMSSQDmhpq80y7Imzfy1CtWW+RGjBCZt9tM917RnTJRcpSwVO+Uk0Mhw9DqwrNyMaA2vCpqFG2Nc09YAiFKcHN5BeDeSxY+wMyiZ3M=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T07:25:18Z"
    mac: ENC[AES256_GCM,data:YKidZaHp/6xxvOIVGFbEUznptK4UWnz+5fn8R1myPC+TE8qNM7iC4efCd4laf2qmlqbI+n3g+ZyYlzXwxScVI7Iq/zof+PiFPpS4SAzi3s+6tWYV25t2l6XRTbP/0rcEHjKFcTuNfob27rVnEYRUHUdaJSG3zW5L+05Mm7vYFHQ=,iv:+PEBvGgMBdSuNqMXCUEe/HMQU4lbSK8eIZvyM1AACIs=,tag:aCqvYJOzV4u/dEA2ySBoJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
