jupyterhub:
    hub:
        #ENC[AES256_GCM,data:WPkM6peQq2wY+NssU6QYUdOHk++zEnjK3zImomU+qhgDG3H4Fhc=,iv:l3z4CbqRb9B/NQJHCZGsi3MU+e6VAZheoUiJnn9hdL0=,tag:G5q48ryDfRxblA9JbU2q2Q==,type:comment]
        cookieSecret: null
    proxy:
        #ENC[AES256_GCM,data:4YZvG+2rHvr4bKwHYP0vIpHT3kqCbLkv5r4hSeU5SNfaD7jZrNw=,iv:bPKxGcJuNXbRt+kkBoTUXxb5N8qBwIFcXjl6f2SM28U=,tag:+vhfzI0K3GOLiRNnNn9MdQ==,type:comment]
        secretToken: null
    auth:
        state:
            enabled: ENC[AES256_GCM,data:yMO5mg==,iv:jV04o0Rb91qv/HZxP3Oivmw4X3gEU348mShsXvndJJs=,tag:xQRa/p+4Mt/alrAF2cPHHQ==,type:bool]
            #ENC[AES256_GCM,data:ZjHQ3i2Zi8s+eQM+gjtrQUOnEG+F2D01Nw/UvuBXAIBFvG7ZWv8=,iv:jqUr3uVhq7Spy+GJ7xIikss7sv9w3mxe1E3Qv8itDmM=,tag:4uxqTOZzwT8kJHgb6nJCjw==,type:comment]
            cryptoKey: null
        google:
            #ENC[AES256_GCM,data:kGskPf0Cj/JM/qVOXzNYtEp9,iv:yvUaWy6bFf9HkFtmyDLkww9RksWOS5VKZasD1fCpW/o=,tag:O9tKEgXXAiwKbpGLqP8cYg==,type:comment]
            clientId: null
            clientSecret: null
            callbackUrl: ENC[AES256_GCM,data:1ehnIwGNAq7NE4VJWWfxh/dRqQETRlSMog1uf0av1Vdw98Acv4UiLbtcgi2z15K8/9FVVuJfbNBFHhdtA0JpHSOyUfoYs4Ck4g==,iv:P4hj3zZK2N8KeRel7bPEPFFnAwPjLXigP4tivlL8LQE=,tag:GFImfVNkMm7pAFIfpSkxAQ==,type:str]
            loginService: ENC[AES256_GCM,data:RpTi3VxB3sAp,iv:UjKZoZ0u8Rejcm8+K1JMkyjBxT+rXdzNaytns00DHiQ=,tag:FYzUZLCvtA2sFyCg/gWFJg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:03Z"
          enc: CiQA67O9AM2fJWWfT+g0YKcZ7TS7506AoJGTjVTOPHXJ0w/WVCcSSQDmhpq8+VQWJ9/zBZf7qwG09tjhENLBr9TyS75d2VZR0WIpHwVnYSN6gP4f5Djqa2KaArngABa5E+EA88wGd5BtuVS0YJcOz9M=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:04Z"
    mac: ENC[AES256_GCM,data:kw6xebYxrZAdQ40qMxwsSaxLxIvUX6KoZ25idpvlaY2CLWBOj+CYe3BRDqxuovKZg5UpGMgjPuF2ColmOCidNvwLV7U2MyGEDCi9JikP6b/ZVDCwQGU+jQWnzSQoqs2kBx/5hb8XwiY40f/1oe18k/XTQTlhJTg1DrZgPcW4Uys=,iv:nB/gy0fQ2jB+fAWtsIfhpOloj6H77zMgkBPKSKAX9pc=,tag:BZkjbqhOl4JBAMv7xE8UfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
