jupyterhub:
    auth:
        state:
            enabled: ENC[AES256_GCM,data:/b61iA==,iv:CvqXL+4cVov9QKus2k/CELWD9GUGujiKvy9WpjepyHM=,tag:BBikJAtMcL0TQZwmsH9B4Q==,type:bool]
            #ENC[AES256_GCM,data:y54yvqb3YMQPxlHI8gNdqsjvkJvoZKnGwB6kPGofgsj8rLsRCFA=,iv:xf/BzMJvKJg0dcpHNUcn+26GrZTR12GurMvaA42au0M=,tag:+bjP26OAZT4R4k2gzD52sQ==,type:comment]
            cryptoKey: null
        google:
            #ENC[AES256_GCM,data:BaFAWnRKqNXZqk4sNpKIU5Ui,iv:EeO3F+ixbKkDBGCpwMTUFebivxUf31Rghz58Ma5HFRQ=,tag:+gZ50K+3bWScb4wgQZJfQA==,type:comment]
            clientId: null
            clientSecret: null
            callbackUrl: ENC[AES256_GCM,data:svQNfL2zVBI64lHsHUW9KTgemLLCStVSgxrhKdC4PyXa869/tc5T7nbpqtVacFmqboSrkHt8vqnw779nQ+wm8j4aGJNDbyCixAw4gGEt7mQX,iv:0B/hjChQuqlZiIhO1XIMymMl2xlmWuhP8I2LqvPJOXE=,tag:SbL1X7bpzdf0ElmjPGm/VA==,type:str]
            loginService: ENC[AES256_GCM,data:2e2wc0DB62qu,iv:ltpIID2kjoBbdHSXTh9fjBP3Ntb8zJIldRMJZmed9V8=,tag:aIc9uS3JYa+pKfcthDK4MA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T10:57:59Z"
    mac: ENC[AES256_GCM,data:NMinRn3fVuq7C+t2pZ9IVNIbT2WfdwScIryd0n3ycanPKzk6QTDg+HqAxi4PUb/yq0JyOb0H1bVoe5uFNra23nF2le9jqiA1rM9EYRWV2EXJ+R5cyn6OAxTdD9J3pIifnMvWgx497Dmtgz51obTt+Y2mRNccKuq8dRbgpXdBCNk=,iv:qHNuDvCDokjfgZFWw4qV4c8l9UowWcY1AnIgY8HVc18=,tag:LrqbwVCinx7//itqInWkNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
