jupyterhub:
    config:
        CanvasOAuthenticator:
            client_secret: ENC[AES256_GCM,data:p2W7DHaLIDcNCV8KPInZb/E7z9pFFvQxMhXeQ6hmILeCMK1ctZe7YI6OMrGxJRAEWapp5hyDzzTCjGV6hE9qqQ==,iv:Zb40gsw1kRbFLdhEP3tZQWTkyeiWxwHKf/KRv+wZiVY=,tag:o9TjCdHC5QLMQzNxWoYeLw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-01T08:03:59Z"
    mac: ENC[AES256_GCM,data:+fTp7Jkza0S1jycsU/L2nxJq4ybq9TVf/tvhyrflTctZZyMxCPP6ob6H0HWxfMObiwKP7GOH5ghbTfdTtMUk6i3lBEUGufhe8/tBwYXbvON10fjfDlfvFZ9JIPY/Cfp1PPaCdCAL/UAEeQNCZrxfyKLkXKkMv8d4QyNYps02sx8=,iv:7GIDZhTzeXucAx8qCP10xz5Rl1nioAXLQi930UpM0ls=,tag:A8cBqJjCkSuIEAD4pnpjEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
