jupyterhub:
    hub:
        #ENC[AES256_GCM,data:N4B3A1j2ESi/guQncLUd0c8FLuiENZEfHNDUPyYe88eSsHXXEW0=,iv:EHrI2zj/BaqlF5NAnEGs3aV0ePhmP6TmP1orXRX5Xbk=,tag:SzwCzbx1nS4CaLcF+6nTyQ==,type:comment]
        cookieSecret: null
    proxy:
        #ENC[AES256_GCM,data:kAmZu97XaV7RD3ayah59NINtCkjmEeBChS+4OrZQgt5SOILWb08=,iv:Wf0mk5CdRHZ39S0u371aprilCe42OyRrTwLxBIX0Ejo=,tag:cZONmXHkn7BmToniH2HVBA==,type:comment]
        secretToken: null
    auth:
        state:
            enabled: ENC[AES256_GCM,data:ybSWuA==,iv:qanUdg/o6xUHK0xPpifXRd52tfHpZ96oSLTLSk4RqMw=,tag:LKowny7NDe+qFLIqcfSKGA==,type:bool]
            #ENC[AES256_GCM,data:aqwit/ebOrfLT/B6Tch5nK76/aZWfulwC45pqCQEDzZNpXnsIAg=,iv:J1/9jdfeEluk5hSdz3vk/PZcrMkel5goAnhwsH0Erow=,tag:SwrLlM2R9Jn9MO1dpJYW6Q==,type:comment]
            cryptoKey: null
        google:
            #ENC[AES256_GCM,data:oTC8z0azjzq1XKzWjoFsnC6e,iv:gL8Aov4JWfmfW2w79WKAd0RelaZRIS3zTcINEf0ZSmA=,tag:Zoa8OcYvyF18y8qfhyZ1zQ==,type:comment]
            clientId: null
            clientSecret: null
            callbackUrl: ENC[AES256_GCM,data:CyFXEDD9obROwgHuZQHZdWFYUZ5wqOClYtfpEuwbxOCiYjNnHP3q4c+6icm0qXBdTbGrYe9T/jAF0HmdPcCnetabLRc+RzkOZYH5ETpN20bj,iv:TVL5HCVhyv4E1Ebsh5SBZ9ROqUVKwUX9sNWlmv36b+k=,tag:QMbFxUV9UM6PbhgY/LlxFA==,type:str]
            loginService: ENC[AES256_GCM,data:JjvEc+zLTyD4,iv:nCrtoKjXa80PU8WrgOCMlPMpS2y2OHpvulvtgbGBFG4=,tag:msuSgzZ49Lm0Z3/XFkTOZw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T06:45:03Z"
          enc: CiQA67O9AAmfViiYSKo6YdqG/q+J5E6eZbVqNUZAU2fakpgqcjISSQDmhpq8zL0/Oi+EqqkU2aaX6SrYTozy0Co1oMi3uDwQ3Bz5lAMh9ZsIeNoplkAO1I5gWHbIkPjEnUOhFYPJrMVczqU/yPToADM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T06:45:04Z"
    mac: ENC[AES256_GCM,data:KHJfo3lbsaEdvXNCoLQLOrNEb2KPZriJVp/GZ7F/MbHeSBLqk1Q9kDgWf2SArdo0tJC2uDoN0WMk0NEJs/5Y6DNMkk+jO1/zChn7MDU4T3sD3n2AFvXKFMs1MkxgRbMLZeI4qhGHphZH1y2YLc7p/biESlG5zfjWJtUodoSeJ4E=,iv:WSrjsX316hGyTisdO+tI300Hzkmf6zt/xXchVlJDZ2U=,tag:djRXFN2Q1v2IWa30WXyqrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
