jupyterhub-ssh:
  hubUrl: https://eecs.datahub.berkeley.edu

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - eecs.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - eecs.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 60
