dependencies:
 - name: jupyterhub
   # REMEMBER TO CHANGE BASE IMAGE OF images/hub/ WHEN CHANGING THIS
   version: 0.10.0-beta.1.n019.h39e0cd53
   repository: https://jupyterhub.github.io/helm-chart/
 - name: jupyterhub-ssh
   version: 0.0.1-n062.h2759fb4
   repository: https://yuvipanda.github.io/jupyterhub-ssh/
