nfsMounter:
  enabled: true

nfsPVC:
  enabled: false
jupyterhub:
  scheduling:
    userScheduler:
      enabled: true
  proxy:
    https:
      letsencrypt:
        contactEmail: yuvipanda@berkeley.edu
  singleuser:
    defaultUrl: "/tree"
  hub:
    extraConfig:
      01-custom-attr-spawner: |
        from kubespawner import KubeSpawner
        from tornado import gen
        import z2jh

        class CustomAttrSpawner(KubeSpawner):

          @gen.coroutine
          def start(self):
            custom_memory = z2jh.get_config('custom.memory', {})
            for attr, users in custom_memory.items():
              if self.user.name in users:
                self.mem_limit = attr
                self.mem_guarantee = attr
                break

            admin_customizations = z2jh.get_config('custom.admin', {})
            if admin_customizations and self.user.admin:
              self.init_containers += admin_customizations.get('initContainers', [])
              self.volume_mounts += admin_customizations.get('extraVolumeMounts', [])

            return (yield super().start())

        c.JupyterHub.spawner_class = CustomAttrSpawner

        c.JupyterHub.extra_log_file = '/srv/jupyterhub/jupyterhub.log'

      02-lab-availability: |
        c.Spawner.cmd = ['jupyter-labhub']

      03-working-dir: |
        # Make sure working directory is ${HOME}
        # hubploy has a bug where it unconditionally puts workingdir to be /srv/repo
        c.KubeSpawner.working_dir = '/home/jovyan'
