jupyterhub-ssh:
  hubUrl: https://julia-staging.datahub.berkeley.edu

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 35.226.84.4
    https:
      hosts:
        - julia-staging.datahub.berkeley.edu
