nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/homedirs-other-2020-07-29/dlab

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool

    config:
      Authenticator:
        admin_users:
            # infrastructure
            - rylo
            - yuvipanda
            - felder
            - balajialwar
            # List of other admin users
            - rbarreto
            - pratik.sachdeva
            - aculich
            - cheng.ren
            - emily_grabowski
            - klganter
            - cvacano
  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: beta-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 4G
      limit: 8G
    image: {}
