jupyterhub-ssh:
  hubUrl: https://dlab-staging.datahub.berkeley.edu

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 35.232.137.1
    https:
      hosts:
        - dlab-staging.datahub.berkeley.edu
