jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          # instructors
          - adhikari
          - culler
          - daw
          - denero
          - vinitra
          - ramesh_s
          # dsep staff
          - bacon
          - ericvd
          - ryanedw
          # s19 data8 gsis
          - acheema
          - aidandeangelis
          - akritisingh
          - alinxie
          - ananya.krishnan
          - anna-nguyen
          - averyyip
          - castro.ian
          - clairezhang
          - colbylewis2020
          - dchotai
          - echang7
          - emmajaeger
          - fmcquarrie3
          - howardki888
          - hsubbaraj
          - huangjiayi0922
          - jadeyen
          - j.hu
          - juliannnguyen
          - jwarnagieris
          - katherine.yen
          - keh7
          - lillianlouie
          - liusabrina
          - loischang
          - makenaschwinn
          - namushegian
          - narain.rohan
          - niraj.a.rao
          - nwang97
          - olivialewke
          - oscar.syu
          - ravi.singhal
          - rishab.s
          - rwoolf
          - sathviknair
          - scott.lee.3898
          - sjamil
          - s.mani
          - tvilayth
          - vienannguyen
          - youmnarabie
          # connector instructors
          - miladm
          - cmason
          - feehan
          - yasminal
          - samyag1
          - michael.eickenberg
          - shobhana

  singleuser:
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/primary-user-image
    storage:
      type: hostPath
