nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver1
    shareName: export/pool0/homes

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
  hub:
    nodeSelector:
      cloud.google.com/gke-nodepool: default-pool
    extraConfigMap:
      profiles:
        # compsci c8
        2019-fall-28063: {}
        # pbhlth w250f
        2019-fall-29639: {}
        # pbhlth w250g
        2019-fall-29640: {}
  proxy:
    nodeSelector:
      cloud.google.com/gke-nodepool: default-pool
  auth:
    type: custom # This enables canvas auth
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          # instructors
          - adhikari
          - culler
          - daw
          - denero
          - vinitra
          - ramesh_s
          # dsep staff
          - bacon
          - ericvd
          - ryanedw
          # s19 data8 gsis
          - acheema
          - aidandeangelis
          - akritisingh
          - alinxie
          - ananya.krishnan
          - anna-nguyen
          - averyyip
          - castro.ian
          - clairezhang
          - colbylewis2020
          - dchotai
          - echang7
          - emmajaeger
          - fmcquarrie3
          - howardki888
          - hsubbaraj
          - huangjiayi0922
          - jadeyen
          - j.hu
          - juliannnguyen
          - jwarnagieris
          - katherine.yen
          - keh7
          - lillianlouie
          - liusabrina
          - loischang
          - makenaschwinn
          - namushegian
          - narain.rohan
          - niraj.a.rao
          - nwang97
          - olivialewke
          - oscar.syu
          - ravi.singhal
          - rishab.s
          - rwoolf
          - sathviknair
          - scott.lee.3898
          - sjamil
          - s.mani
          - tvilayth
          - vienannguyen
          - youmnarabie
          # connector instructors
          - miladm
          - cmason
          - feehan
          - yasminal
          - samyag1
          - michael.eickenberg
          - shobhana

  singleuser:
    nodeSelector:
      cloud.google.com/gke-nodepool: user-pool
    initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: home
          mountPath: /home/jovyan
          subPath: "{username}"
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/primary-user-image
