jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          # instructors
          - adhikari
          - culler
          - daw
          - denero
          - vinitra
          - ramesh_s
          # dsep staff
          - bacon
          - ericvd
          - ryanedw
          # f18 data8 gsis
          - acheema
          - adnan.h
          - austenzhu
          - emmajaeger
          - howardki888
          - huangjiayi0922
          - niraj.a.rao
          - nskh
          - vienannguyen
          - akritisingh
          - amrosenthal
          - alinxie
          - anna-nguyen
          - averyyip
          - clairezhang
          - colbylewis2020
          - dchotai
          - echang7
          - fmcquarrie3
          - jwarnagieris
          - jamiegerman
          - j.hu
          - keh7
          - loischang
          - makenaschwinn
          - mayarao
          - mayashen
          - nwang97
          - namushegian
          - ravi.singhal
          - rwoolf
          - rishab.s
          - roberts97
          - narain.rohan
          - rroggenkemper
          - liusabrina
          - sidney.h.le
          - s.mani
          # 2018 data8x gsis
          - rroggenkemper
          # connector instructors
          - miladm
          - cmason
          - feehan
          - yasminal
          - samyag1
          - michael.eickenberg
          - shobhana
          # sp18 Physics 77/88
          - ryansmith63
          - ygkolomensky
          # sp18 LING 243 Spring 2018
          - terry.regier
          # sp18 COGSCI 131 Spring 2018
          - ddbourgin
          # sp18 ECON 101B Spring 2018
          - jbdelong

  singleuser:
    memory:
      guarantee: 1G
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/primary-user-image
    storage:
      type: hostPath
