nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/datahubhomes-2020-07-29/homes

etcGitConfig:
  enabled: true
  gitconfig: |
    [credential "https://github.com"]
      helper = !git-credential-github-app --app-key-file /etc/github/github-app-private-key.pem --app-id 94384
      useHttpPath = true

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    initContainers:
      # There's another sidecar, specified in `secrets/staging.yaml` and `secrets/prod.yaml`
      # that keeps this up to date. https://github.com/jupyterhub/kubespawner/issues/468
      # should help us move that back here.
      - name: templates-clone
        image: alpine/git
        args:
          - clone
          - --depth=1
          - --single-branch
          - --
          - https://github.com/berkeley-dsep-infra/datahub-homepage
          - /srv/repo
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: custom-templates
            mountPath: /srv/repo
    extraVolumes:
      - name: custom-templates
        emptyDir: {}
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "templates"
      - mountPath: /usr/local/share/jupyterhub/static/extra-assets
        name: custom-templates
        subPath: "extra-assets"
    extraConfig:
      04-custom-theme: |
        c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
    extraConfigMap:
      # this should be migrated to custom.profiles when that works
      profiles:
        # ENVECON153 (EEP153) Spring 2021 Issue 2013
        2021-spring-27844:
          mem_limit: 4096M
          mem_guarantee: 1024M
        # astr 128
        2020-spring-25880:
          mem_limit: 4096M
          mem_guarantee: 1024M
        # astr 256
        2020-spring-25995:
          mem_limit: 4096M
          mem_guarantee: 1024M
        modules-leads:
          users:
            - yuvipanda
            - ktakimoto
            - ericvd
            - jasonjiang
            - alec.kan
            - eesaravia
            - almapineda
            - m.wilkinson
            - schaganty
            - timlan.wong
          extraVolumes:
            - name: shared
              hostPath:
                path: /data/homes/prod/_shared/module-leads
          extraVolumeMounts:
            - name: shared
              mountPath: /home/jovyan/shared/module-leads
  proxy:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
  auth:
    type: custom # This enables canvas auth
    admin:
      users:
          # infrastructure
          - felder
          - rylo
          - yuvipanda
          # regular instructors
          - adhikari
          - culler
          - daw
          - denero
          - ramesh_s
          - suraj.rampure
          - swupnil
          - terry.regier
          # dsep staff
          - ericvd
          - ktakimoto
          - ryanedw
          # fa20 data8 gsis
          - aanika.shah
          - aidandeangelis
          - alanliang
          - amrosenthal
          - alvinyu27
          - andyjvan
          - ananya.krishnan
          - guanangela
          - zhoa210
          - brettirvin
          - carolinejchen
          - celinechen_99
          - chendiw
          - connorcclark
          - dshahroz
          - devennb
          - nellepersson
          - emilykzou
          - erika.n.mack
          - eshaansoman
          - fachacoso
          - fqzbdkh
          - gregoryd2017
          - gregking22
          - castro.ian
          - jifu.li
          - kwalia1999
          - katherinetsai
          - kevin.hsu
          - lritter
          - marmis
          - meghanwang
          - melissarwong
          - nancywang
          - nicholesun
          - olivialewke
          - parouz
          - pratibha99
          - ritawang
          - netzke
          - roshansrin01
          - rdoshi99
          - samwu101
          - sarthakarora
          - saurav
          - sophiatan
          - sdjajadi
          - sunnyshen
          - tvilayth
          - vaibhav.pabreja
          - vikramchandran
          - winifredchung
          - yanayrosen
          - yashswarup
          # fa20 data8 tutors
          - aarushi.k
          - aditi.mahajan
          - yanlinma
          - anna_zhao
          - anujalohia
          - ashika-raghavan
          - aviksethia99
          - carlosortiz
          - claudea
          - terrylincr
          - devarshdhanuka
          - deveshagarwal
          - drewsuranjan
          - eshadgoo972
          - gracealtree
          - ichiachen1
          - jacquelinekyu
          - jeshoung
          - jinhao.huo
          - joyceezheng
          - kevinmiao
          - laeticiayang
          - lindseyhanlon
          - michellelou
          - nataliegomas
          - nickha
          - nicolepark
          - nhanafi
          - o.chang
          - pulkitb124
          - rachelchen0522
          - raymondwang
          - rikiiyer
          - rohanchilukuri
          - ryanchien04
          - sarahding815
          - sarina.xin
          - kingh0730
          - shayan.ghosh
          - stephaniex
          - sydniezanone
          - takaokakegawa
          - tongshen
          - jvarun
          - ellenkwok882
          - karywang
          - terry.regier # fa20 ling 290L instructor, with temp title "Additional Seminar on Special Topics to Be Announced"
  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: alpha-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
      extraVolumes:
        - name: etc-jupyter
          configMap:
            name: user-etc-jupyter
        - name: etc-gitconfig
          secret:
            secretName: user-etc-gitconfig
      extraVolumeMounts:
        - name: etc-jupyter
          mountPath: /etc/jupyter
        - name: etc-gitconfig
          mountPath: /etc/gitconfig
          subPath: gitconfig
          readOnly: true
        - name: etc-gitconfig
          mountPath: /etc/github/github-app-private-key.pem
          subPath: github-app-private-key.pem
          readOnly: true
        # RStudio can't write session files to anywhere except ~/.rstudio -
        # only way to change that is by setting $HOME. So instead, we just
        # bind mount a fresh directory on top of ~/.rstudio!
        - name: home
          mountPath: /home/jovyan/.rstudio
          subPath: '{username}/.datahub-rstudio'
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/primary-user-image

custom:
  wtf: "why isn't this passed to config/values.yaml"

# read by z2jh.get_config() in hub/values.yaml
# (theoretically!)
# custom:
#   profiles:
#     # compsci c8
#     2019-fall-28063: {}
#     # pbhlth w250f
#     2019-fall-29639: {}
#     # pbhlth w250g
#     2019-fall-29640: {}
