nfsMounter:
  enabled: true

nfsPVC:
  enabled: false
  nfs:
    serverIP: nfsserver1
    shareName: export/pool0/homes

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/node-purpose: core
  hub:
    nodeSelector:
      hub.jupyter.org/node-purpose: core
    extraConfigMap:
      # this should be migrated to custom.profiles when that works
      profiles:
        # compsci c8
        2019-fall-28063: {}
        # pbhlth w250f
        2019-fall-29639: {}
        # pbhlth w250g
        2019-fall-29640: {}
        # linguis 243
        2019-fall-31002: {}
        # data 88
        2019-fall-33469: {}
        # physics 188
        2019-fall-32821:
          mem_limit: 2048M
          mem_guarantee: 1024M
        modules-leads:
          users:
            - yuvipanda
            - ktakimoto
            - ericvd
            - jasonjiang
            - alec.kan
            - eesaravia
            - almapineda
            - m.wilkinson
            - schaganty
            - timlan.wong
          extraVolumes:
            - name: shared
              hostPath:
                path: /data/homes/prod/_shared/module-leads
          extraVolumeMounts:
            - name: shared
              mountPath: /home/jovyan/shared/module-leads
  proxy:
    nodeSelector:
      hub.jupyter.org/node-purpose: core
  auth:
    type: custom # This enables canvas auth
    admin:
      users:
          # infrastructure
          - felder
          - rylo
          - yuvipanda
          # regular instructors
          - adhikari
          - culler
          - daw
          - denero
          - ramesh_s
          # dsep staff
          - ericvd
          - ktakimoto
          - ryanedw
          # f19 data8 gsis
          - adele.bloch
          - aidandeangelis
          - alanliang
          - ananya.krishnan
          - andrewdchen
          - anna.burns
          - anna-nguyen
          - ashleyquiterio
          - averyyip
          - carolinejchen
          - castro.ian
          - colbylewis2020
          - emilykzou
          - gregking22
          - gregoryd2017
          - guanangela
          - hsubbaraj
          - hubertluo
          - irenerwang
          - jadeyen
          - jifu.li
          - juliannnguyen
          - katherinetsai
          - keh7
          - lillianlouie
          - lritter
          - manikui
          - mayarao
          - mayashen
          - olivialewke
          - oscar.syu
          - parouz
          - ravi.singhal
          - roshansrin01
          - rwoolf
          - samwu101
          - sathviknair
          - saurav
          - scott.lee.3898
          - sdjajadi
          - tvilayth
          - vienannguyen
          - yanayrosen
          - yashswarup
          # f19 data8 tutors
          - aanika.shah
          - alvinyu27
          - brettirvin
          - celinechen_99
          - chloelo
          - connorcclark
          - devennb
          - deveshagarwal
          - dshahroz
          - ericli3088
          - erika.n.mack
          - eshaansoman
          - fachacoso
          - fqzbdkh
          - gnacouzi
          - harimlee
          - ikaur
          - ishaan.srivastava
          - jacobmartinez
          - jenniferjia00
          - karywang
          - kevin.hsu
          - kwalia1999
          - lindseyhanlon
          - lucyportnoff
          - marmis
          - meghanwang
          - melissarwong
          - nancywang
          - nellepersson
          - netzke
          - nhanafi
          - nicholesun
          - pratibha99
          - rdoshi99
          - rinasa525
          - sophiatan
          - ssingorahardjo
          - sunnyshen
          - vaibhav.pabreja
          - vikramchandran
          - winifredchung
          - wwalsh
          - youmnarabie
          - zhoa210
  singleuser:
    nodeSelector:
      hub.jupyter.org/node-purpose: user
    storage:
      type: none
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/primary-user-image

custom:
  wtf: "why isn't this passed to config/values.yaml"

# read by z2jh.get_config() in hub/values.yaml
# (theoretically!)
# custom:
#   profiles:
#     # compsci c8
#     2019-fall-28063: {}
#     # pbhlth w250f
#     2019-fall-29639: {}
#     # pbhlth w250g
#     2019-fall-29640: {}
