nfsMounter:
  mounts:
    - nfsserver1:/export/pool0/homes=/data/homes/prod

jupyterhub:
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/prod/{username}
        - name: cogneuro
          hostPath:
            path: /data/homes/prod/_cogneuro
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
        - name: cogneuro
          mountPath: /data/cogneuro
          readOnly: True
