jupyterhub:

  hub:
    services:
      data8-staging.datahub.berkeley.edu:
        name: data8-staging.datahub.berkeley.edu
        oauth_redirect_uri: https://data8-staging.datahub.berkeley.edu/hub/oauth_callback
      ischool-staging.datahub.berkeley.edu:
        name: ischool-staging.datahub.berkeley.edu
        oauth_redirect_uri: https://ischool-staging.datahub.berkeley.edu/hub/oauth_callback
  scheduling:
    userPlaceholder:
      enabled: false
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 104.197.27.164
    https:
      hosts:
        - staging.datahub.berkeley.edu
