jupyterhub-ssh:
  hubUrl: https://staging.datahub.berkeley.edu

jupyterhub:
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 1
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 104.197.27.164
    https:
      hosts:
        - staging.datahub.berkeley.edu
  hub:
    extraContainers:
      # Keep templates in sync, so you can autodeploy from master
      - name: templates-sync
        image: alpine/git
        workingDir: /srv/repo
        command:
          - /bin/sh
        args:
          - -c
          # Do git reset --hard origin/master so we aren't confused by force pushes
          - "while true; do git fetch origin; git reset --hard origin/master; sleep\
            \ 5m; done"
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: custom-templates
            mountPath: /srv/repo
    extraVolumes:
      - name: custom-templates
        emptyDir: {}
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "templates"
      - mountPath: /usr/local/share/jupyterhub/static/extra-assets
        name: custom-templates
        subPath: "extra-assets"
    extraConfig:
      04-custom-theme: |
        c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
