nfsMounter:
  mounts:
    - nfsserver1:/export/pool0/homes=/data/homes/staging

jupyterhub:
  proxy:
    service:
      loadBalancerIP: 104.197.27.164
    https:
      hosts:
        - staging.datahub.berkeley.edu
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/staging/{username}
        - name: cogneuro
          hostPath:
            path: /data/homes/staging/_cogneuro
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
        - name: cogneuro
          mountPath: /data/cogneuro
          readOnly: True