nfsMounter:
  mounts:
    - nfsserver1:/export/pool0/homes=/data/homes/staging
jupyterhub:
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/staging/{username}
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 104.197.27.164
    https:
      hosts:
        - staging.datahub.berkeley.edu