jupyterhub:
  auth:
    type: google
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda

  singleuser:
    memory:
      guarantee: 512M
      limit: 2G
    image:
      name: gcr.io/ucb-datahub-2018/math124-user-image
    storage:
      type: hostPath
