nfsMounter:
  mounts:
    - nfsserver1:/export/pool0/homes/_math124=/data/homes/math124-prod

jupyterhub:
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/math124-prod/{username}
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
