version: "v0.5.0+219e37e"

hub:
  db:
    type: sqlite-memory

singleuser:
  memory:
    guarantee: 1G
    limit: 1G
  image:
    name: berkeleydsep/datahub-user
  storage:
    type: hostPath
    extraVolumes:
      - name: home
        hostPath:
          path: /data/homes/{username}
    extraVolumeMounts:
      - name: home
        mountPath: /home/jovyan
