version: "v0.5.0"


hub:
  db:
    type: postgres
  extraConfig: |
    from kubespawner import KubeSpawner
    from tornado import gen
    import yaml

    class CustomMemorySpawner(KubeSpawner):
      @gen.coroutine
      def start(self):
        with open('/etc/jupyterhub/config/custom.memory-customization') as f:
          custom_memory_lists = yaml.safe_load(f)
        for mem, users in custom_memory_lists.items():
          if self.user.name in users:
            self.mem_limit = mem
            self.mem_guarantee = mem
            break
        return (yield super().start())
    c.JupyterHub.spawner_class = CustomMemorySpawner

rbac:
    enabled: false

auth:
  type: google
  admin:
    users:
        # infrastructure
        - rylo
        - yuvipanda
        - vinitra
        - gunjan_baid
        # fa17 data 8 Professors
        - denero
        - daw
        # fa17 data 8 GSIs
        - alexku
        - fhdkmrn
        - wumadeline
        - arvindiyengar
        - chenge
        - huangjiayi0922
        - jwhughes
        - katherine.yen
        - namushegian
        - nskh
        - suraj.rampure
        - v.oikonomou
        - emmajaeger
        - inan.husain
        - j.hu
        - niraj.a.rao
        - priyanka.bhoj
        - ronald.walker
        - supadhyay
        - vienannguyen
        - wiltonwu
        - naltieri
        - juitungkuo
        - nwang97
        - acheema
        - michelleyang
        - satish.vinay
        - abalamurugan112
        - tanaynathan18
        - zdehkord
        # connector instructors
        - miladm
        - cmason
        - feehan
        - yasminal
        - samyag1
        - michael.eickenberg
        - ericvd
        - chench
        - cvacano
        - shobhana

singleuser:
  memory:
    guarantee: 1G
    limit: 1G
  image:
    name: berkeleydsep/datahub-user
  storage:
    type: hostPath
    extraVolumes:
      - name: home
        hostPath:
          path: /data/homes/{username}
      - name: cogneuro
        hostPath:
          path: /data/homes/_cogneuro
    extraVolumeMounts:
      - name: home
        mountPath: /home/jovyan
      - name: cogneuro
        mountPath: /data/cogneuro
        readOnly: True
